import { config } from 'dotenv';
import { writeFileSync } from 'fs';
import { join } from 'path';
import type { Environment } from './src/environments/environment.interface';

// Todo lo que este script lee y escribe cuelga de su propio directorio, nunca del cwd.
// Con rutas relativas, ejecutarlo desde la raíz del monorepo generaba un
// coaster/src/environments/environment.ts entero, sin leer el .env de aquí, y ese
// fichero acabó commiteado porque el .gitignore que lo tapa vive en apps/web.
const here = import.meta.dirname;

// Dos ficheros, y el orden importa: dotenv no pisa lo que ya está puesto, así que
// apps/web/.env manda y la raíz es el respaldo. La raíz existe porque es el que lee
// docker compose; sin leerla aquí, un `npm test` en el anfitrión regeneraría este
// fichero sin las variables que sí tiene el contenedor, y se las pisaría por el
// volumen montado.
config({ path: join(here, '.env') });
config({ path: join(here, '..', '..', '.env') });

if (process.env.PRODUCTION === undefined) {
  console.warn('⚠️  PRODUCTION is not set; building as development. Set it to "true" for a release bundle.');
}

const envConfig: Environment = {
  production: process.env.PRODUCTION === 'true',
  defaultLanguage: process.env.DEFAULT_LANGUAGE || 'en',
  defaultLanguagePath: process.env.DEFAULT_LANGUAGE_PATH || './i18n/',
  apiUrl:
    process.env.API_URL ||
    (process.env.PRODUCTION === 'true' ? 'https://api.coaster.business' : 'http://localhost:3000'),
  googleClientId: process.env.GOOGLE_CLIENT_ID || '',
};

const objectString = JSON.stringify(envConfig, null, 2).replace(/"([^"]+)":/g, '$1:');

const envFileContent = `import { Environment } from './environment.interface';

// GENERATED FILE - DO NOT EDIT
// Generated by set-env.ts
// modify the .env file to change the environment variables
export const environment: Environment = ${objectString};
`;

// Sin mkdir a propósito: src/environments existe siempre porque environment.interface.ts
// está en git. Si algún día esta ruta deja de ser válida, la escritura falla y se ve,
// en vez de crear un árbol nuevo en el sitio equivocado sin decir nada.
writeFileSync(join(here, 'src/environments/environment.ts'), envFileContent);

const allowIndexing = process.env.ALLOW_INDEXING !== 'false';

writeFileSync(join(here, 'public/robots.txt'), `User-agent: *\n${allowIndexing ? 'Allow' : 'Disallow'}: /\n`);

if (!envConfig.googleClientId) {
  console.warn(
    '⚠️  GOOGLE_CLIENT_ID is not set in apps/web/.env nor in the repository root .env; ' +
      'the app builds without the Google sign-in button.',
  );
}

console.log(`✅ environment.ts generado estricto. Prod: ${envConfig.production}, Indexable: ${allowIndexing}`);
