-- Categories and products were stored as translation keys. The words below are generated from the
-- same source as the starter catalogue, so re-importing matches an existing row instead of adding one.

UPDATE "Category" SET name = 'Bocadillos y Hamburguesas' WHERE name = 'templates.categories.bocadillos_y_hamburguesas';
UPDATE "Category" SET name = 'Cafetería' WHERE name = 'templates.categories.cafeteria';
UPDATE "Category" SET name = 'Cervezas' WHERE name = 'templates.categories.cervezas';
UPDATE "Category" SET name = 'Postres' WHERE name = 'templates.categories.postres';
UPDATE "Category" SET name = 'Refrescos y Aguas' WHERE name = 'templates.categories.refrescos_y_aguas';
UPDATE "Category" SET name = 'Tapas y Raciones' WHERE name = 'templates.categories.tapas_y_raciones';
UPDATE "Category" SET name = 'Vinos y Licores' WHERE name = 'templates.categories.vinos_y_licores';
UPDATE "Category" SET name = 'Tercio 1906 Reserva Especial' WHERE name = 'templates.products.beer_1906';
UPDATE "Category" SET name = 'Tercio Alhambra Reserva 1925' WHERE name = 'templates.products.beer_alhambra_1925';
UPDATE "Category" SET name = 'Tercio Coronita' WHERE name = 'templates.products.beer_corona';
UPDATE "Category" SET name = 'Doble de Cerveza (Estrella Galicia)' WHERE name = 'templates.products.beer_draught_large';
UPDATE "Category" SET name = 'Caña de Cerveza (Estrella Galicia)' WHERE name = 'templates.products.beer_draught_small';
UPDATE "Category" SET name = 'Tercio El Águila Sin Filtrar' WHERE name = 'templates.products.beer_el_aguila_unfiltered';
UPDATE "Category" SET name = 'Tercio Estrella Galicia' WHERE name = 'templates.products.beer_estrella_galicia';
UPDATE "Category" SET name = 'Tercio Heineken' WHERE name = 'templates.products.beer_heineken';
UPDATE "Category" SET name = 'Tercio Heineken 0,0' WHERE name = 'templates.products.beer_heineken_non_alc';
UPDATE "Category" SET name = 'Tercio Mahou Cinco Estrellas' WHERE name = 'templates.products.beer_mahou_5_estrellas';
UPDATE "Category" SET name = 'Tercio Mahou 0,0 Tostada' WHERE name = 'templates.products.beer_mahou_non_alc_toasted';
UPDATE "Category" SET name = 'Tercio Mahou Rosé' WHERE name = 'templates.products.beer_mahou_rose';
UPDATE "Category" SET name = 'Tercio Paulaner (Trigo)' WHERE name = 'templates.products.beer_paulaner';
UPDATE "Category" SET name = 'Tinto de Verano' WHERE name = 'templates.products.beer_tinto_verano';
UPDATE "Category" SET name = 'Café Solo' WHERE name = 'templates.products.coffee_black';
UPDATE "Category" SET name = 'Capuccino' WHERE name = 'templates.products.coffee_cappuccino';
UPDATE "Category" SET name = 'Carajillo' WHERE name = 'templates.products.coffee_carajillo';
UPDATE "Category" SET name = 'Colacao' WHERE name = 'templates.products.coffee_colacao';
UPDATE "Category" SET name = 'Café Cortado' WHERE name = 'templates.products.coffee_cortado';
UPDATE "Category" SET name = 'Café Espresso' WHERE name = 'templates.products.coffee_espresso';
UPDATE "Category" SET name = 'Infusión / Té' WHERE name = 'templates.products.coffee_tea';
UPDATE "Category" SET name = 'Café con Leche' WHERE name = 'templates.products.coffee_with_milk';
UPDATE "Category" SET name = 'Tarta de Queso' WHERE name = 'templates.products.dessert_cheesecake';
UPDATE "Category" SET name = 'Tarta de Chocolate' WHERE name = 'templates.products.dessert_chocolate_cake';
UPDATE "Category" SET name = 'Flan Casero' WHERE name = 'templates.products.dessert_flan';
UPDATE "Category" SET name = 'Helado Variado' WHERE name = 'templates.products.dessert_ice_cream';
UPDATE "Category" SET name = 'Ginebra Beefeater (Sola)' WHERE name = 'templates.products.gin_beefeater_neat';
UPDATE "Category" SET name = 'Gin Tonic Beefeater' WHERE name = 'templates.products.gin_beefeater_tonic';
UPDATE "Category" SET name = 'Ginebra Hendrick''s (Sola)' WHERE name = 'templates.products.gin_hendricks_neat';
UPDATE "Category" SET name = 'Gin Tonic Hendrick''s' WHERE name = 'templates.products.gin_hendricks_tonic';
UPDATE "Category" SET name = 'Copa de Baileys' WHERE name = 'templates.products.liqueur_baileys';
UPDATE "Category" SET name = 'Chupito de Licor de Hierbas' WHERE name = 'templates.products.liqueur_herbal_shot';
UPDATE "Category" SET name = 'Chupito de Jägermeister' WHERE name = 'templates.products.liqueur_jager_shot';
UPDATE "Category" SET name = 'Ron Barceló con Cola' WHERE name = 'templates.products.rom_barcelo_coke';
UPDATE "Category" SET name = 'Ron Barceló Añejo (Solo)' WHERE name = 'templates.products.rom_barcelo_neat';
UPDATE "Category" SET name = 'Ron Havana 7 con Cola' WHERE name = 'templates.products.rom_havana_7_coke';
UPDATE "Category" SET name = 'Ron Havana Club 7 (Solo)' WHERE name = 'templates.products.rom_havana_7_neat';
UPDATE "Category" SET name = 'Ron Santa Teresa con Cola' WHERE name = 'templates.products.rom_santa_teresa_coke';
UPDATE "Category" SET name = 'Ron Santa Teresa (Solo)' WHERE name = 'templates.products.rom_santa_teresa_neat';
UPDATE "Category" SET name = 'Bocadillo de Calamares' WHERE name = 'templates.products.sandwich_calamari';
UPDATE "Category" SET name = 'Bocadillo Chivito' WHERE name = 'templates.products.sandwich_chivito';
UPDATE "Category" SET name = 'Hamburguesa Clásica con Queso' WHERE name = 'templates.products.sandwich_classic_burger';
UPDATE "Category" SET name = 'Sándwich Mixto' WHERE name = 'templates.products.sandwich_ham_cheese';
UPDATE "Category" SET name = 'Perrito Caliente' WHERE name = 'templates.products.sandwich_hot_dog';
UPDATE "Category" SET name = 'Bocadillo Tortilla de Patatas' WHERE name = 'templates.products.sandwich_potato_omelette';
UPDATE "Category" SET name = 'Hamburguesa Especial Coaster' WHERE name = 'templates.products.sandwich_special_burger';
UPDATE "Category" SET name = 'Aquarius Limón' WHERE name = 'templates.products.soft_drink_aquarius_lemon';
UPDATE "Category" SET name = 'Coca-Cola Original' WHERE name = 'templates.products.soft_drink_coca_cola';
UPDATE "Category" SET name = 'Coca-Cola Zero' WHERE name = 'templates.products.soft_drink_coca_cola_zero';
UPDATE "Category" SET name = 'Fanta Limón' WHERE name = 'templates.products.soft_drink_fanta_lemon';
UPDATE "Category" SET name = 'Fanta Naranja' WHERE name = 'templates.products.soft_drink_fanta_orange';
UPDATE "Category" SET name = 'Nestea' WHERE name = 'templates.products.soft_drink_nestea';
UPDATE "Category" SET name = 'Agua con Gas' WHERE name = 'templates.products.soft_drink_sparkling_water';
UPDATE "Category" SET name = 'Sprite' WHERE name = 'templates.products.soft_drink_sprite';
UPDATE "Category" SET name = 'Tónica' WHERE name = 'templates.products.soft_drink_tonic';
UPDATE "Category" SET name = 'Agua Mineral 500ml' WHERE name = 'templates.products.soft_drink_water_500ml';
UPDATE "Category" SET name = 'Patatas Bravas' WHERE name = 'templates.products.tapas_bravas';
UPDATE "Category" SET name = 'Calamares a la Romana' WHERE name = 'templates.products.tapas_calamari';
UPDATE "Category" SET name = 'Tabla de Quesos' WHERE name = 'templates.products.tapas_cheese_board';
UPDATE "Category" SET name = 'Alitas de Pollo' WHERE name = 'templates.products.tapas_chicken_wings';
UPDATE "Category" SET name = 'Croquetas de Jamón (6 ud)' WHERE name = 'templates.products.tapas_croquettes_ham';
UPDATE "Category" SET name = 'Tabla de Jamón Ibérico' WHERE name = 'templates.products.tapas_iberian_ham';
UPDATE "Category" SET name = 'Pimientos del Padrón' WHERE name = 'templates.products.tapas_padron_peppers';
UPDATE "Category" SET name = 'Ensaladilla Rusa' WHERE name = 'templates.products.tapas_russian_salad';
UPDATE "Category" SET name = 'Vodka Absolut con Refresco' WHERE name = 'templates.products.vodka_absolut_coke';
UPDATE "Category" SET name = 'Vodka Absolut (Solo)' WHERE name = 'templates.products.vodka_absolut_neat';
UPDATE "Category" SET name = 'Whisky Jack Daniel''s con Cola' WHERE name = 'templates.products.whisky_jack_daniels_coke';
UPDATE "Category" SET name = 'Whisky Jack Daniel''s (Solo)' WHERE name = 'templates.products.whisky_jack_daniels_neat';
UPDATE "Category" SET name = 'Whisky J&B con Refresco' WHERE name = 'templates.products.whisky_jb_coke';
UPDATE "Category" SET name = 'Whisky J&B (Solo)' WHERE name = 'templates.products.whisky_jb_neat';
UPDATE "Category" SET name = 'Whisky Macallan 12 (Solo)' WHERE name = 'templates.products.whisky_macallan_neat';
UPDATE "Category" SET name = 'Botella de Vino Tinto (Rioja)' WHERE name = 'templates.products.wine_red_bottle';
UPDATE "Category" SET name = 'Copa de Vino Tinto (Rioja)' WHERE name = 'templates.products.wine_red_glass';
UPDATE "Category" SET name = 'Copa de Vermut de la Casa' WHERE name = 'templates.products.wine_vermouth_glass';
UPDATE "Category" SET name = 'Botella de Vino Blanco (Rueda)' WHERE name = 'templates.products.wine_white_bottle';
UPDATE "Category" SET name = 'Copa de Vino Blanco (Rueda)' WHERE name = 'templates.products.wine_white_glass';

UPDATE "Product" SET name = 'Bocadillos y Hamburguesas' WHERE name = 'templates.categories.bocadillos_y_hamburguesas';
UPDATE "Product" SET name = 'Cafetería' WHERE name = 'templates.categories.cafeteria';
UPDATE "Product" SET name = 'Cervezas' WHERE name = 'templates.categories.cervezas';
UPDATE "Product" SET name = 'Postres' WHERE name = 'templates.categories.postres';
UPDATE "Product" SET name = 'Refrescos y Aguas' WHERE name = 'templates.categories.refrescos_y_aguas';
UPDATE "Product" SET name = 'Tapas y Raciones' WHERE name = 'templates.categories.tapas_y_raciones';
UPDATE "Product" SET name = 'Vinos y Licores' WHERE name = 'templates.categories.vinos_y_licores';
UPDATE "Product" SET name = 'Tercio 1906 Reserva Especial' WHERE name = 'templates.products.beer_1906';
UPDATE "Product" SET name = 'Tercio Alhambra Reserva 1925' WHERE name = 'templates.products.beer_alhambra_1925';
UPDATE "Product" SET name = 'Tercio Coronita' WHERE name = 'templates.products.beer_corona';
UPDATE "Product" SET name = 'Doble de Cerveza (Estrella Galicia)' WHERE name = 'templates.products.beer_draught_large';
UPDATE "Product" SET name = 'Caña de Cerveza (Estrella Galicia)' WHERE name = 'templates.products.beer_draught_small';
UPDATE "Product" SET name = 'Tercio El Águila Sin Filtrar' WHERE name = 'templates.products.beer_el_aguila_unfiltered';
UPDATE "Product" SET name = 'Tercio Estrella Galicia' WHERE name = 'templates.products.beer_estrella_galicia';
UPDATE "Product" SET name = 'Tercio Heineken' WHERE name = 'templates.products.beer_heineken';
UPDATE "Product" SET name = 'Tercio Heineken 0,0' WHERE name = 'templates.products.beer_heineken_non_alc';
UPDATE "Product" SET name = 'Tercio Mahou Cinco Estrellas' WHERE name = 'templates.products.beer_mahou_5_estrellas';
UPDATE "Product" SET name = 'Tercio Mahou 0,0 Tostada' WHERE name = 'templates.products.beer_mahou_non_alc_toasted';
UPDATE "Product" SET name = 'Tercio Mahou Rosé' WHERE name = 'templates.products.beer_mahou_rose';
UPDATE "Product" SET name = 'Tercio Paulaner (Trigo)' WHERE name = 'templates.products.beer_paulaner';
UPDATE "Product" SET name = 'Tinto de Verano' WHERE name = 'templates.products.beer_tinto_verano';
UPDATE "Product" SET name = 'Café Solo' WHERE name = 'templates.products.coffee_black';
UPDATE "Product" SET name = 'Capuccino' WHERE name = 'templates.products.coffee_cappuccino';
UPDATE "Product" SET name = 'Carajillo' WHERE name = 'templates.products.coffee_carajillo';
UPDATE "Product" SET name = 'Colacao' WHERE name = 'templates.products.coffee_colacao';
UPDATE "Product" SET name = 'Café Cortado' WHERE name = 'templates.products.coffee_cortado';
UPDATE "Product" SET name = 'Café Espresso' WHERE name = 'templates.products.coffee_espresso';
UPDATE "Product" SET name = 'Infusión / Té' WHERE name = 'templates.products.coffee_tea';
UPDATE "Product" SET name = 'Café con Leche' WHERE name = 'templates.products.coffee_with_milk';
UPDATE "Product" SET name = 'Tarta de Queso' WHERE name = 'templates.products.dessert_cheesecake';
UPDATE "Product" SET name = 'Tarta de Chocolate' WHERE name = 'templates.products.dessert_chocolate_cake';
UPDATE "Product" SET name = 'Flan Casero' WHERE name = 'templates.products.dessert_flan';
UPDATE "Product" SET name = 'Helado Variado' WHERE name = 'templates.products.dessert_ice_cream';
UPDATE "Product" SET name = 'Ginebra Beefeater (Sola)' WHERE name = 'templates.products.gin_beefeater_neat';
UPDATE "Product" SET name = 'Gin Tonic Beefeater' WHERE name = 'templates.products.gin_beefeater_tonic';
UPDATE "Product" SET name = 'Ginebra Hendrick''s (Sola)' WHERE name = 'templates.products.gin_hendricks_neat';
UPDATE "Product" SET name = 'Gin Tonic Hendrick''s' WHERE name = 'templates.products.gin_hendricks_tonic';
UPDATE "Product" SET name = 'Copa de Baileys' WHERE name = 'templates.products.liqueur_baileys';
UPDATE "Product" SET name = 'Chupito de Licor de Hierbas' WHERE name = 'templates.products.liqueur_herbal_shot';
UPDATE "Product" SET name = 'Chupito de Jägermeister' WHERE name = 'templates.products.liqueur_jager_shot';
UPDATE "Product" SET name = 'Ron Barceló con Cola' WHERE name = 'templates.products.rom_barcelo_coke';
UPDATE "Product" SET name = 'Ron Barceló Añejo (Solo)' WHERE name = 'templates.products.rom_barcelo_neat';
UPDATE "Product" SET name = 'Ron Havana 7 con Cola' WHERE name = 'templates.products.rom_havana_7_coke';
UPDATE "Product" SET name = 'Ron Havana Club 7 (Solo)' WHERE name = 'templates.products.rom_havana_7_neat';
UPDATE "Product" SET name = 'Ron Santa Teresa con Cola' WHERE name = 'templates.products.rom_santa_teresa_coke';
UPDATE "Product" SET name = 'Ron Santa Teresa (Solo)' WHERE name = 'templates.products.rom_santa_teresa_neat';
UPDATE "Product" SET name = 'Bocadillo de Calamares' WHERE name = 'templates.products.sandwich_calamari';
UPDATE "Product" SET name = 'Bocadillo Chivito' WHERE name = 'templates.products.sandwich_chivito';
UPDATE "Product" SET name = 'Hamburguesa Clásica con Queso' WHERE name = 'templates.products.sandwich_classic_burger';
UPDATE "Product" SET name = 'Sándwich Mixto' WHERE name = 'templates.products.sandwich_ham_cheese';
UPDATE "Product" SET name = 'Perrito Caliente' WHERE name = 'templates.products.sandwich_hot_dog';
UPDATE "Product" SET name = 'Bocadillo Tortilla de Patatas' WHERE name = 'templates.products.sandwich_potato_omelette';
UPDATE "Product" SET name = 'Hamburguesa Especial Coaster' WHERE name = 'templates.products.sandwich_special_burger';
UPDATE "Product" SET name = 'Aquarius Limón' WHERE name = 'templates.products.soft_drink_aquarius_lemon';
UPDATE "Product" SET name = 'Coca-Cola Original' WHERE name = 'templates.products.soft_drink_coca_cola';
UPDATE "Product" SET name = 'Coca-Cola Zero' WHERE name = 'templates.products.soft_drink_coca_cola_zero';
UPDATE "Product" SET name = 'Fanta Limón' WHERE name = 'templates.products.soft_drink_fanta_lemon';
UPDATE "Product" SET name = 'Fanta Naranja' WHERE name = 'templates.products.soft_drink_fanta_orange';
UPDATE "Product" SET name = 'Nestea' WHERE name = 'templates.products.soft_drink_nestea';
UPDATE "Product" SET name = 'Agua con Gas' WHERE name = 'templates.products.soft_drink_sparkling_water';
UPDATE "Product" SET name = 'Sprite' WHERE name = 'templates.products.soft_drink_sprite';
UPDATE "Product" SET name = 'Tónica' WHERE name = 'templates.products.soft_drink_tonic';
UPDATE "Product" SET name = 'Agua Mineral 500ml' WHERE name = 'templates.products.soft_drink_water_500ml';
UPDATE "Product" SET name = 'Patatas Bravas' WHERE name = 'templates.products.tapas_bravas';
UPDATE "Product" SET name = 'Calamares a la Romana' WHERE name = 'templates.products.tapas_calamari';
UPDATE "Product" SET name = 'Tabla de Quesos' WHERE name = 'templates.products.tapas_cheese_board';
UPDATE "Product" SET name = 'Alitas de Pollo' WHERE name = 'templates.products.tapas_chicken_wings';
UPDATE "Product" SET name = 'Croquetas de Jamón (6 ud)' WHERE name = 'templates.products.tapas_croquettes_ham';
UPDATE "Product" SET name = 'Tabla de Jamón Ibérico' WHERE name = 'templates.products.tapas_iberian_ham';
UPDATE "Product" SET name = 'Pimientos del Padrón' WHERE name = 'templates.products.tapas_padron_peppers';
UPDATE "Product" SET name = 'Ensaladilla Rusa' WHERE name = 'templates.products.tapas_russian_salad';
UPDATE "Product" SET name = 'Vodka Absolut con Refresco' WHERE name = 'templates.products.vodka_absolut_coke';
UPDATE "Product" SET name = 'Vodka Absolut (Solo)' WHERE name = 'templates.products.vodka_absolut_neat';
UPDATE "Product" SET name = 'Whisky Jack Daniel''s con Cola' WHERE name = 'templates.products.whisky_jack_daniels_coke';
UPDATE "Product" SET name = 'Whisky Jack Daniel''s (Solo)' WHERE name = 'templates.products.whisky_jack_daniels_neat';
UPDATE "Product" SET name = 'Whisky J&B con Refresco' WHERE name = 'templates.products.whisky_jb_coke';
UPDATE "Product" SET name = 'Whisky J&B (Solo)' WHERE name = 'templates.products.whisky_jb_neat';
UPDATE "Product" SET name = 'Whisky Macallan 12 (Solo)' WHERE name = 'templates.products.whisky_macallan_neat';
UPDATE "Product" SET name = 'Botella de Vino Tinto (Rioja)' WHERE name = 'templates.products.wine_red_bottle';
UPDATE "Product" SET name = 'Copa de Vino Tinto (Rioja)' WHERE name = 'templates.products.wine_red_glass';
UPDATE "Product" SET name = 'Copa de Vermut de la Casa' WHERE name = 'templates.products.wine_vermouth_glass';
UPDATE "Product" SET name = 'Botella de Vino Blanco (Rueda)' WHERE name = 'templates.products.wine_white_bottle';
UPDATE "Product" SET name = 'Copa de Vino Blanco (Rueda)' WHERE name = 'templates.products.wine_white_glass';
