export const SocketEvents = {
  JOIN_BAR: 'joinBar',
  LEAVE_BAR: 'leaveBar',
  JOINED: 'joined',
  LEFT: 'left',
  PRODUCT_CREATED: 'productCreated',
  PRODUCT_STOCK_CHANGED: 'productStockChanged',
  PRODUCT_UPDATED: 'productUpdated',
  PRODUCT_DELETED: 'productDeleted',
  CATEGORY_CREATED: 'categoryCreated',
  CATEGORY_UPDATED: 'categoryUpdated',
  CATEGORY_DELETED: 'categoryDeleted',
  MEMBER_INVITED: 'memberInvited',
  MEMBER_REMOVED: 'memberRemoved',
  TABLE_STATUS_CHANGED: 'tableStatusChanged',
  TABLE_CREATED: 'tableCreated',
  TABLE_UPDATED: 'tableUpdated',
  TABLE_DELETED: 'tableDeleted',
  ORDER_CREATED: 'orderCreated',
  ORDER_UPDATED: 'orderUpdated',
  ORDER_ITEM_ADDED: 'orderItemAdded',
  ORDER_CLOSED: 'orderClosed',
  ORDER_CANCELLED: 'orderCancelled',
  ORDER_DELETED: 'orderDeleted',
  SHIFT_CREATED: 'shiftCreated',
  SHIFT_DELETED: 'shiftDeleted',
} as const;

export const ErrorCodes = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_CREATION_FAILED: 'USER_CREATION_FAILED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  MISSING_BAR_ID: 'MISSING_BAR_ID',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  BAR_NOT_FOUND: 'BAR_NOT_FOUND',
  USER_ALREADY_MEMBER: 'USER_ALREADY_MEMBER',
  CANNOT_REMOVE_LAST_OWNER: 'CANNOT_REMOVE_LAST_OWNER',
  INVALID_TYPE: 'INVALID_TYPE',
  MIN_LENGTH: 'MIN_LENGTH',
  MAX_LENGTH: 'MAX_LENGTH',
  INVALID_EMAIL: 'INVALID_EMAIL',
  REQUIRED: 'REQUIRED',
  INVALID_ROLE: 'INVALID_ROLE',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  INVALID_DATE: 'INVALID_DATE',
  SHIFT_NOT_FOUND: 'SHIFT_NOT_FOUND',
  EXCHANGE_NOT_FOUND: 'EXCHANGE_NOT_FOUND',
  INVALID_EXCHANGE: 'INVALID_EXCHANGE',
  NOT_YOUR_SHIFT: 'NOT_YOUR_SHIFT',
  UNAUTHORIZED_SHIFT_ACTION: 'UNAUTHORIZED_SHIFT_ACTION',
  EXCHANGE_ALREADY_PENDING: 'EXCHANGE_ALREADY_PENDING',
  INVALID_BAR_ID: 'INVALID_BAR_ID',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  TABLE_ALREADY_OCCUPIED: 'TABLE_ALREADY_OCCUPIED',
  TABLE_NOT_OCCUPIED: 'TABLE_NOT_OCCUPIED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_OPEN: 'ORDER_NOT_OPEN',
  ORDER_ITEM_NOT_FOUND: 'ORDER_ITEM_NOT_FOUND',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',
  INVALID_ORDER_IDS: 'INVALID_ORDER_IDS',
} as const;

export const BarPermission = {
  INVITE_MEMBER: 'bar:invite-member',
  REMOVE_MEMBER: 'bar:remove-member',
  VIEW_MEMBERS: 'bar:view-members',
  OPEN_TABLE: 'bar:open-table',
  VIEW_TABLES: 'bar:view-tables',
  CREATE_TABLE: 'bar:create-table',
  UPDATE_TABLE: 'bar:update-table',
  DELETE_TABLE: 'bar:delete-table',
  CREATE_ORDER: 'bar:create-order',
  VIEW_ORDERS: 'bar:view-orders',
  UPDATE_ORDER: 'bar:update-order',
  DELETE_ORDER: 'bar:delete-order',
  DELETE_ORDER_ITEM: 'bar:delete-order-item',
  CHECKOUT_ORDER: 'bar:checkout-order',
  CANCEL_ORDER: 'bar:cancel-order',
  MOVE_ORDER_TABLE: 'bar:move-order-table',
  MERGE_ORDERS: 'bar:merge-orders',
  VIEW_PRODUCTS: 'bar:view-products',
  CREATE_PRODUCT: 'bar:create-product',
  UPDATE_PRODUCT: 'bar:update-product',
  UPDATE_PRODUCT_STOCK: 'bar:update-product-stock',
  DELETE_PRODUCT: 'bar:delete-product',
  VIEW_CATEGORIES: 'bar:view-categories',
  CREATE_CATEGORY: 'bar:create-category',
  UPDATE_CATEGORY: 'bar:update-category',
  DELETE_CATEGORY: 'bar:delete-category',
  VIEW_SHIFTS: 'bar:view-shifts',
  CREATE_SHIFT: 'bar:create-shift',
  DELETE_SHIFT: 'bar:delete-shift',
  VIEW_EXCHANGES: 'bar:view-exchanges',
  CREATE_EXCHANGE: 'bar:create-exchange',
  ACCEPT_EXCHANGE: 'bar:accept-exchange',
  DELETE_EXCHANGE: 'bar:delete-exchange',
  IMPORT_TEMPLATES: 'bar:import-templates',
} as const;

export const ShiftExchangeStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
