
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DbCashClose` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DbCashClose
 * 
 */
export type DbCashCloseModel = runtime.Types.Result.DefaultSelection<Prisma.$DbCashClosePayload>

export type AggregateDbCashClose = {
  _count: DbCashCloseCountAggregateOutputType | null
  _avg: DbCashCloseAvgAggregateOutputType | null
  _sum: DbCashCloseSumAggregateOutputType | null
  _min: DbCashCloseMinAggregateOutputType | null
  _max: DbCashCloseMaxAggregateOutputType | null
}

export type DbCashCloseAvgAggregateOutputType = {
  closedOrders: number | null
  cancelledOrders: number | null
  cancelledAmount: number | null
  cashAmount: number | null
  cardAmount: number | null
  tipAmount: number | null
  openingFloat: number | null
  countedCash: number | null
}

export type DbCashCloseSumAggregateOutputType = {
  closedOrders: number | null
  cancelledOrders: number | null
  cancelledAmount: number | null
  cashAmount: number | null
  cardAmount: number | null
  tipAmount: number | null
  openingFloat: number | null
  countedCash: number | null
}

export type DbCashCloseMinAggregateOutputType = {
  id: string | null
  establishmentId: string | null
  closedById: string | null
  since: Date | null
  closedAt: Date | null
  closedOrders: number | null
  cancelledOrders: number | null
  cancelledAmount: number | null
  cashAmount: number | null
  cardAmount: number | null
  tipAmount: number | null
  openingFloat: number | null
  countedCash: number | null
  notes: string | null
}

export type DbCashCloseMaxAggregateOutputType = {
  id: string | null
  establishmentId: string | null
  closedById: string | null
  since: Date | null
  closedAt: Date | null
  closedOrders: number | null
  cancelledOrders: number | null
  cancelledAmount: number | null
  cashAmount: number | null
  cardAmount: number | null
  tipAmount: number | null
  openingFloat: number | null
  countedCash: number | null
  notes: string | null
}

export type DbCashCloseCountAggregateOutputType = {
  id: number
  establishmentId: number
  closedById: number
  since: number
  closedAt: number
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes: number
  _all: number
}


export type DbCashCloseAvgAggregateInputType = {
  closedOrders?: true
  cancelledOrders?: true
  cancelledAmount?: true
  cashAmount?: true
  cardAmount?: true
  tipAmount?: true
  openingFloat?: true
  countedCash?: true
}

export type DbCashCloseSumAggregateInputType = {
  closedOrders?: true
  cancelledOrders?: true
  cancelledAmount?: true
  cashAmount?: true
  cardAmount?: true
  tipAmount?: true
  openingFloat?: true
  countedCash?: true
}

export type DbCashCloseMinAggregateInputType = {
  id?: true
  establishmentId?: true
  closedById?: true
  since?: true
  closedAt?: true
  closedOrders?: true
  cancelledOrders?: true
  cancelledAmount?: true
  cashAmount?: true
  cardAmount?: true
  tipAmount?: true
  openingFloat?: true
  countedCash?: true
  notes?: true
}

export type DbCashCloseMaxAggregateInputType = {
  id?: true
  establishmentId?: true
  closedById?: true
  since?: true
  closedAt?: true
  closedOrders?: true
  cancelledOrders?: true
  cancelledAmount?: true
  cashAmount?: true
  cardAmount?: true
  tipAmount?: true
  openingFloat?: true
  countedCash?: true
  notes?: true
}

export type DbCashCloseCountAggregateInputType = {
  id?: true
  establishmentId?: true
  closedById?: true
  since?: true
  closedAt?: true
  closedOrders?: true
  cancelledOrders?: true
  cancelledAmount?: true
  cashAmount?: true
  cardAmount?: true
  tipAmount?: true
  openingFloat?: true
  countedCash?: true
  notes?: true
  _all?: true
}

export type DbCashCloseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbCashClose to aggregate.
   */
  where?: Prisma.DbCashCloseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbCashCloses to fetch.
   */
  orderBy?: Prisma.DbCashCloseOrderByWithRelationInput | Prisma.DbCashCloseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DbCashCloseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbCashCloses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbCashCloses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DbCashCloses
  **/
  _count?: true | DbCashCloseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DbCashCloseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DbCashCloseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DbCashCloseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DbCashCloseMaxAggregateInputType
}

export type GetDbCashCloseAggregateType<T extends DbCashCloseAggregateArgs> = {
      [P in keyof T & keyof AggregateDbCashClose]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDbCashClose[P]>
    : Prisma.GetScalarType<T[P], AggregateDbCashClose[P]>
}




export type DbCashCloseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DbCashCloseWhereInput
  orderBy?: Prisma.DbCashCloseOrderByWithAggregationInput | Prisma.DbCashCloseOrderByWithAggregationInput[]
  by: Prisma.DbCashCloseScalarFieldEnum[] | Prisma.DbCashCloseScalarFieldEnum
  having?: Prisma.DbCashCloseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DbCashCloseCountAggregateInputType | true
  _avg?: DbCashCloseAvgAggregateInputType
  _sum?: DbCashCloseSumAggregateInputType
  _min?: DbCashCloseMinAggregateInputType
  _max?: DbCashCloseMaxAggregateInputType
}

export type DbCashCloseGroupByOutputType = {
  id: string
  establishmentId: string
  closedById: string
  since: Date | null
  closedAt: Date
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes: string | null
  _count: DbCashCloseCountAggregateOutputType | null
  _avg: DbCashCloseAvgAggregateOutputType | null
  _sum: DbCashCloseSumAggregateOutputType | null
  _min: DbCashCloseMinAggregateOutputType | null
  _max: DbCashCloseMaxAggregateOutputType | null
}

export type GetDbCashCloseGroupByPayload<T extends DbCashCloseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DbCashCloseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DbCashCloseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DbCashCloseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DbCashCloseGroupByOutputType[P]>
      }
    >
  >



export type DbCashCloseWhereInput = {
  AND?: Prisma.DbCashCloseWhereInput | Prisma.DbCashCloseWhereInput[]
  OR?: Prisma.DbCashCloseWhereInput[]
  NOT?: Prisma.DbCashCloseWhereInput | Prisma.DbCashCloseWhereInput[]
  id?: Prisma.StringFilter<"DbCashClose"> | string
  establishmentId?: Prisma.StringFilter<"DbCashClose"> | string
  closedById?: Prisma.StringFilter<"DbCashClose"> | string
  since?: Prisma.DateTimeNullableFilter<"DbCashClose"> | Date | string | null
  closedAt?: Prisma.DateTimeFilter<"DbCashClose"> | Date | string
  closedOrders?: Prisma.IntFilter<"DbCashClose"> | number
  cancelledOrders?: Prisma.IntFilter<"DbCashClose"> | number
  cancelledAmount?: Prisma.IntFilter<"DbCashClose"> | number
  cashAmount?: Prisma.IntFilter<"DbCashClose"> | number
  cardAmount?: Prisma.IntFilter<"DbCashClose"> | number
  tipAmount?: Prisma.IntFilter<"DbCashClose"> | number
  openingFloat?: Prisma.IntFilter<"DbCashClose"> | number
  countedCash?: Prisma.IntFilter<"DbCashClose"> | number
  notes?: Prisma.StringNullableFilter<"DbCashClose"> | string | null
  establishment?: Prisma.XOR<Prisma.DbEstablishmentScalarRelationFilter, Prisma.DbEstablishmentWhereInput>
  closedBy?: Prisma.XOR<Prisma.DbUserScalarRelationFilter, Prisma.DbUserWhereInput>
  orders?: Prisma.DbOrderListRelationFilter
}

export type DbCashCloseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  establishmentId?: Prisma.SortOrder
  closedById?: Prisma.SortOrder
  since?: Prisma.SortOrderInput | Prisma.SortOrder
  closedAt?: Prisma.SortOrder
  closedOrders?: Prisma.SortOrder
  cancelledOrders?: Prisma.SortOrder
  cancelledAmount?: Prisma.SortOrder
  cashAmount?: Prisma.SortOrder
  cardAmount?: Prisma.SortOrder
  tipAmount?: Prisma.SortOrder
  openingFloat?: Prisma.SortOrder
  countedCash?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  establishment?: Prisma.DbEstablishmentOrderByWithRelationInput
  closedBy?: Prisma.DbUserOrderByWithRelationInput
  orders?: Prisma.DbOrderOrderByRelationAggregateInput
}

export type DbCashCloseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DbCashCloseWhereInput | Prisma.DbCashCloseWhereInput[]
  OR?: Prisma.DbCashCloseWhereInput[]
  NOT?: Prisma.DbCashCloseWhereInput | Prisma.DbCashCloseWhereInput[]
  establishmentId?: Prisma.StringFilter<"DbCashClose"> | string
  closedById?: Prisma.StringFilter<"DbCashClose"> | string
  since?: Prisma.DateTimeNullableFilter<"DbCashClose"> | Date | string | null
  closedAt?: Prisma.DateTimeFilter<"DbCashClose"> | Date | string
  closedOrders?: Prisma.IntFilter<"DbCashClose"> | number
  cancelledOrders?: Prisma.IntFilter<"DbCashClose"> | number
  cancelledAmount?: Prisma.IntFilter<"DbCashClose"> | number
  cashAmount?: Prisma.IntFilter<"DbCashClose"> | number
  cardAmount?: Prisma.IntFilter<"DbCashClose"> | number
  tipAmount?: Prisma.IntFilter<"DbCashClose"> | number
  openingFloat?: Prisma.IntFilter<"DbCashClose"> | number
  countedCash?: Prisma.IntFilter<"DbCashClose"> | number
  notes?: Prisma.StringNullableFilter<"DbCashClose"> | string | null
  establishment?: Prisma.XOR<Prisma.DbEstablishmentScalarRelationFilter, Prisma.DbEstablishmentWhereInput>
  closedBy?: Prisma.XOR<Prisma.DbUserScalarRelationFilter, Prisma.DbUserWhereInput>
  orders?: Prisma.DbOrderListRelationFilter
}, "id">

export type DbCashCloseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  establishmentId?: Prisma.SortOrder
  closedById?: Prisma.SortOrder
  since?: Prisma.SortOrderInput | Prisma.SortOrder
  closedAt?: Prisma.SortOrder
  closedOrders?: Prisma.SortOrder
  cancelledOrders?: Prisma.SortOrder
  cancelledAmount?: Prisma.SortOrder
  cashAmount?: Prisma.SortOrder
  cardAmount?: Prisma.SortOrder
  tipAmount?: Prisma.SortOrder
  openingFloat?: Prisma.SortOrder
  countedCash?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DbCashCloseCountOrderByAggregateInput
  _avg?: Prisma.DbCashCloseAvgOrderByAggregateInput
  _max?: Prisma.DbCashCloseMaxOrderByAggregateInput
  _min?: Prisma.DbCashCloseMinOrderByAggregateInput
  _sum?: Prisma.DbCashCloseSumOrderByAggregateInput
}

export type DbCashCloseScalarWhereWithAggregatesInput = {
  AND?: Prisma.DbCashCloseScalarWhereWithAggregatesInput | Prisma.DbCashCloseScalarWhereWithAggregatesInput[]
  OR?: Prisma.DbCashCloseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DbCashCloseScalarWhereWithAggregatesInput | Prisma.DbCashCloseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DbCashClose"> | string
  establishmentId?: Prisma.StringWithAggregatesFilter<"DbCashClose"> | string
  closedById?: Prisma.StringWithAggregatesFilter<"DbCashClose"> | string
  since?: Prisma.DateTimeNullableWithAggregatesFilter<"DbCashClose"> | Date | string | null
  closedAt?: Prisma.DateTimeWithAggregatesFilter<"DbCashClose"> | Date | string
  closedOrders?: Prisma.IntWithAggregatesFilter<"DbCashClose"> | number
  cancelledOrders?: Prisma.IntWithAggregatesFilter<"DbCashClose"> | number
  cancelledAmount?: Prisma.IntWithAggregatesFilter<"DbCashClose"> | number
  cashAmount?: Prisma.IntWithAggregatesFilter<"DbCashClose"> | number
  cardAmount?: Prisma.IntWithAggregatesFilter<"DbCashClose"> | number
  tipAmount?: Prisma.IntWithAggregatesFilter<"DbCashClose"> | number
  openingFloat?: Prisma.IntWithAggregatesFilter<"DbCashClose"> | number
  countedCash?: Prisma.IntWithAggregatesFilter<"DbCashClose"> | number
  notes?: Prisma.StringNullableWithAggregatesFilter<"DbCashClose"> | string | null
}

export type DbCashCloseCreateInput = {
  id?: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
  establishment: Prisma.DbEstablishmentCreateNestedOneWithoutCashClosesInput
  closedBy: Prisma.DbUserCreateNestedOneWithoutCashClosesInput
  orders?: Prisma.DbOrderCreateNestedManyWithoutCashCloseInput
}

export type DbCashCloseUncheckedCreateInput = {
  id?: string
  establishmentId: string
  closedById: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
  orders?: Prisma.DbOrderUncheckedCreateNestedManyWithoutCashCloseInput
}

export type DbCashCloseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  establishment?: Prisma.DbEstablishmentUpdateOneRequiredWithoutCashClosesNestedInput
  closedBy?: Prisma.DbUserUpdateOneRequiredWithoutCashClosesNestedInput
  orders?: Prisma.DbOrderUpdateManyWithoutCashCloseNestedInput
}

export type DbCashCloseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  establishmentId?: Prisma.StringFieldUpdateOperationsInput | string
  closedById?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orders?: Prisma.DbOrderUncheckedUpdateManyWithoutCashCloseNestedInput
}

export type DbCashCloseCreateManyInput = {
  id?: string
  establishmentId: string
  closedById: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
}

export type DbCashCloseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DbCashCloseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  establishmentId?: Prisma.StringFieldUpdateOperationsInput | string
  closedById?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DbCashCloseListRelationFilter = {
  every?: Prisma.DbCashCloseWhereInput
  some?: Prisma.DbCashCloseWhereInput
  none?: Prisma.DbCashCloseWhereInput
}

export type DbCashCloseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DbCashCloseNullableScalarRelationFilter = {
  is?: Prisma.DbCashCloseWhereInput | null
  isNot?: Prisma.DbCashCloseWhereInput | null
}

export type DbCashCloseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  establishmentId?: Prisma.SortOrder
  closedById?: Prisma.SortOrder
  since?: Prisma.SortOrder
  closedAt?: Prisma.SortOrder
  closedOrders?: Prisma.SortOrder
  cancelledOrders?: Prisma.SortOrder
  cancelledAmount?: Prisma.SortOrder
  cashAmount?: Prisma.SortOrder
  cardAmount?: Prisma.SortOrder
  tipAmount?: Prisma.SortOrder
  openingFloat?: Prisma.SortOrder
  countedCash?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type DbCashCloseAvgOrderByAggregateInput = {
  closedOrders?: Prisma.SortOrder
  cancelledOrders?: Prisma.SortOrder
  cancelledAmount?: Prisma.SortOrder
  cashAmount?: Prisma.SortOrder
  cardAmount?: Prisma.SortOrder
  tipAmount?: Prisma.SortOrder
  openingFloat?: Prisma.SortOrder
  countedCash?: Prisma.SortOrder
}

export type DbCashCloseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  establishmentId?: Prisma.SortOrder
  closedById?: Prisma.SortOrder
  since?: Prisma.SortOrder
  closedAt?: Prisma.SortOrder
  closedOrders?: Prisma.SortOrder
  cancelledOrders?: Prisma.SortOrder
  cancelledAmount?: Prisma.SortOrder
  cashAmount?: Prisma.SortOrder
  cardAmount?: Prisma.SortOrder
  tipAmount?: Prisma.SortOrder
  openingFloat?: Prisma.SortOrder
  countedCash?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type DbCashCloseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  establishmentId?: Prisma.SortOrder
  closedById?: Prisma.SortOrder
  since?: Prisma.SortOrder
  closedAt?: Prisma.SortOrder
  closedOrders?: Prisma.SortOrder
  cancelledOrders?: Prisma.SortOrder
  cancelledAmount?: Prisma.SortOrder
  cashAmount?: Prisma.SortOrder
  cardAmount?: Prisma.SortOrder
  tipAmount?: Prisma.SortOrder
  openingFloat?: Prisma.SortOrder
  countedCash?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type DbCashCloseSumOrderByAggregateInput = {
  closedOrders?: Prisma.SortOrder
  cancelledOrders?: Prisma.SortOrder
  cancelledAmount?: Prisma.SortOrder
  cashAmount?: Prisma.SortOrder
  cardAmount?: Prisma.SortOrder
  tipAmount?: Prisma.SortOrder
  openingFloat?: Prisma.SortOrder
  countedCash?: Prisma.SortOrder
}

export type DbCashCloseCreateNestedManyWithoutClosedByInput = {
  create?: Prisma.XOR<Prisma.DbCashCloseCreateWithoutClosedByInput, Prisma.DbCashCloseUncheckedCreateWithoutClosedByInput> | Prisma.DbCashCloseCreateWithoutClosedByInput[] | Prisma.DbCashCloseUncheckedCreateWithoutClosedByInput[]
  connectOrCreate?: Prisma.DbCashCloseCreateOrConnectWithoutClosedByInput | Prisma.DbCashCloseCreateOrConnectWithoutClosedByInput[]
  createMany?: Prisma.DbCashCloseCreateManyClosedByInputEnvelope
  connect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
}

export type DbCashCloseUncheckedCreateNestedManyWithoutClosedByInput = {
  create?: Prisma.XOR<Prisma.DbCashCloseCreateWithoutClosedByInput, Prisma.DbCashCloseUncheckedCreateWithoutClosedByInput> | Prisma.DbCashCloseCreateWithoutClosedByInput[] | Prisma.DbCashCloseUncheckedCreateWithoutClosedByInput[]
  connectOrCreate?: Prisma.DbCashCloseCreateOrConnectWithoutClosedByInput | Prisma.DbCashCloseCreateOrConnectWithoutClosedByInput[]
  createMany?: Prisma.DbCashCloseCreateManyClosedByInputEnvelope
  connect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
}

export type DbCashCloseUpdateManyWithoutClosedByNestedInput = {
  create?: Prisma.XOR<Prisma.DbCashCloseCreateWithoutClosedByInput, Prisma.DbCashCloseUncheckedCreateWithoutClosedByInput> | Prisma.DbCashCloseCreateWithoutClosedByInput[] | Prisma.DbCashCloseUncheckedCreateWithoutClosedByInput[]
  connectOrCreate?: Prisma.DbCashCloseCreateOrConnectWithoutClosedByInput | Prisma.DbCashCloseCreateOrConnectWithoutClosedByInput[]
  upsert?: Prisma.DbCashCloseUpsertWithWhereUniqueWithoutClosedByInput | Prisma.DbCashCloseUpsertWithWhereUniqueWithoutClosedByInput[]
  createMany?: Prisma.DbCashCloseCreateManyClosedByInputEnvelope
  set?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  disconnect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  delete?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  connect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  update?: Prisma.DbCashCloseUpdateWithWhereUniqueWithoutClosedByInput | Prisma.DbCashCloseUpdateWithWhereUniqueWithoutClosedByInput[]
  updateMany?: Prisma.DbCashCloseUpdateManyWithWhereWithoutClosedByInput | Prisma.DbCashCloseUpdateManyWithWhereWithoutClosedByInput[]
  deleteMany?: Prisma.DbCashCloseScalarWhereInput | Prisma.DbCashCloseScalarWhereInput[]
}

export type DbCashCloseUncheckedUpdateManyWithoutClosedByNestedInput = {
  create?: Prisma.XOR<Prisma.DbCashCloseCreateWithoutClosedByInput, Prisma.DbCashCloseUncheckedCreateWithoutClosedByInput> | Prisma.DbCashCloseCreateWithoutClosedByInput[] | Prisma.DbCashCloseUncheckedCreateWithoutClosedByInput[]
  connectOrCreate?: Prisma.DbCashCloseCreateOrConnectWithoutClosedByInput | Prisma.DbCashCloseCreateOrConnectWithoutClosedByInput[]
  upsert?: Prisma.DbCashCloseUpsertWithWhereUniqueWithoutClosedByInput | Prisma.DbCashCloseUpsertWithWhereUniqueWithoutClosedByInput[]
  createMany?: Prisma.DbCashCloseCreateManyClosedByInputEnvelope
  set?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  disconnect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  delete?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  connect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  update?: Prisma.DbCashCloseUpdateWithWhereUniqueWithoutClosedByInput | Prisma.DbCashCloseUpdateWithWhereUniqueWithoutClosedByInput[]
  updateMany?: Prisma.DbCashCloseUpdateManyWithWhereWithoutClosedByInput | Prisma.DbCashCloseUpdateManyWithWhereWithoutClosedByInput[]
  deleteMany?: Prisma.DbCashCloseScalarWhereInput | Prisma.DbCashCloseScalarWhereInput[]
}

export type DbCashCloseCreateNestedManyWithoutEstablishmentInput = {
  create?: Prisma.XOR<Prisma.DbCashCloseCreateWithoutEstablishmentInput, Prisma.DbCashCloseUncheckedCreateWithoutEstablishmentInput> | Prisma.DbCashCloseCreateWithoutEstablishmentInput[] | Prisma.DbCashCloseUncheckedCreateWithoutEstablishmentInput[]
  connectOrCreate?: Prisma.DbCashCloseCreateOrConnectWithoutEstablishmentInput | Prisma.DbCashCloseCreateOrConnectWithoutEstablishmentInput[]
  createMany?: Prisma.DbCashCloseCreateManyEstablishmentInputEnvelope
  connect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
}

export type DbCashCloseUncheckedCreateNestedManyWithoutEstablishmentInput = {
  create?: Prisma.XOR<Prisma.DbCashCloseCreateWithoutEstablishmentInput, Prisma.DbCashCloseUncheckedCreateWithoutEstablishmentInput> | Prisma.DbCashCloseCreateWithoutEstablishmentInput[] | Prisma.DbCashCloseUncheckedCreateWithoutEstablishmentInput[]
  connectOrCreate?: Prisma.DbCashCloseCreateOrConnectWithoutEstablishmentInput | Prisma.DbCashCloseCreateOrConnectWithoutEstablishmentInput[]
  createMany?: Prisma.DbCashCloseCreateManyEstablishmentInputEnvelope
  connect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
}

export type DbCashCloseUpdateManyWithoutEstablishmentNestedInput = {
  create?: Prisma.XOR<Prisma.DbCashCloseCreateWithoutEstablishmentInput, Prisma.DbCashCloseUncheckedCreateWithoutEstablishmentInput> | Prisma.DbCashCloseCreateWithoutEstablishmentInput[] | Prisma.DbCashCloseUncheckedCreateWithoutEstablishmentInput[]
  connectOrCreate?: Prisma.DbCashCloseCreateOrConnectWithoutEstablishmentInput | Prisma.DbCashCloseCreateOrConnectWithoutEstablishmentInput[]
  upsert?: Prisma.DbCashCloseUpsertWithWhereUniqueWithoutEstablishmentInput | Prisma.DbCashCloseUpsertWithWhereUniqueWithoutEstablishmentInput[]
  createMany?: Prisma.DbCashCloseCreateManyEstablishmentInputEnvelope
  set?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  disconnect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  delete?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  connect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  update?: Prisma.DbCashCloseUpdateWithWhereUniqueWithoutEstablishmentInput | Prisma.DbCashCloseUpdateWithWhereUniqueWithoutEstablishmentInput[]
  updateMany?: Prisma.DbCashCloseUpdateManyWithWhereWithoutEstablishmentInput | Prisma.DbCashCloseUpdateManyWithWhereWithoutEstablishmentInput[]
  deleteMany?: Prisma.DbCashCloseScalarWhereInput | Prisma.DbCashCloseScalarWhereInput[]
}

export type DbCashCloseUncheckedUpdateManyWithoutEstablishmentNestedInput = {
  create?: Prisma.XOR<Prisma.DbCashCloseCreateWithoutEstablishmentInput, Prisma.DbCashCloseUncheckedCreateWithoutEstablishmentInput> | Prisma.DbCashCloseCreateWithoutEstablishmentInput[] | Prisma.DbCashCloseUncheckedCreateWithoutEstablishmentInput[]
  connectOrCreate?: Prisma.DbCashCloseCreateOrConnectWithoutEstablishmentInput | Prisma.DbCashCloseCreateOrConnectWithoutEstablishmentInput[]
  upsert?: Prisma.DbCashCloseUpsertWithWhereUniqueWithoutEstablishmentInput | Prisma.DbCashCloseUpsertWithWhereUniqueWithoutEstablishmentInput[]
  createMany?: Prisma.DbCashCloseCreateManyEstablishmentInputEnvelope
  set?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  disconnect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  delete?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  connect?: Prisma.DbCashCloseWhereUniqueInput | Prisma.DbCashCloseWhereUniqueInput[]
  update?: Prisma.DbCashCloseUpdateWithWhereUniqueWithoutEstablishmentInput | Prisma.DbCashCloseUpdateWithWhereUniqueWithoutEstablishmentInput[]
  updateMany?: Prisma.DbCashCloseUpdateManyWithWhereWithoutEstablishmentInput | Prisma.DbCashCloseUpdateManyWithWhereWithoutEstablishmentInput[]
  deleteMany?: Prisma.DbCashCloseScalarWhereInput | Prisma.DbCashCloseScalarWhereInput[]
}

export type DbCashCloseCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.DbCashCloseCreateWithoutOrdersInput, Prisma.DbCashCloseUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.DbCashCloseCreateOrConnectWithoutOrdersInput
  connect?: Prisma.DbCashCloseWhereUniqueInput
}

export type DbCashCloseUpdateOneWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.DbCashCloseCreateWithoutOrdersInput, Prisma.DbCashCloseUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.DbCashCloseCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.DbCashCloseUpsertWithoutOrdersInput
  disconnect?: Prisma.DbCashCloseWhereInput | boolean
  delete?: Prisma.DbCashCloseWhereInput | boolean
  connect?: Prisma.DbCashCloseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DbCashCloseUpdateToOneWithWhereWithoutOrdersInput, Prisma.DbCashCloseUpdateWithoutOrdersInput>, Prisma.DbCashCloseUncheckedUpdateWithoutOrdersInput>
}

export type DbCashCloseCreateWithoutClosedByInput = {
  id?: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
  establishment: Prisma.DbEstablishmentCreateNestedOneWithoutCashClosesInput
  orders?: Prisma.DbOrderCreateNestedManyWithoutCashCloseInput
}

export type DbCashCloseUncheckedCreateWithoutClosedByInput = {
  id?: string
  establishmentId: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
  orders?: Prisma.DbOrderUncheckedCreateNestedManyWithoutCashCloseInput
}

export type DbCashCloseCreateOrConnectWithoutClosedByInput = {
  where: Prisma.DbCashCloseWhereUniqueInput
  create: Prisma.XOR<Prisma.DbCashCloseCreateWithoutClosedByInput, Prisma.DbCashCloseUncheckedCreateWithoutClosedByInput>
}

export type DbCashCloseCreateManyClosedByInputEnvelope = {
  data: Prisma.DbCashCloseCreateManyClosedByInput | Prisma.DbCashCloseCreateManyClosedByInput[]
  skipDuplicates?: boolean
}

export type DbCashCloseUpsertWithWhereUniqueWithoutClosedByInput = {
  where: Prisma.DbCashCloseWhereUniqueInput
  update: Prisma.XOR<Prisma.DbCashCloseUpdateWithoutClosedByInput, Prisma.DbCashCloseUncheckedUpdateWithoutClosedByInput>
  create: Prisma.XOR<Prisma.DbCashCloseCreateWithoutClosedByInput, Prisma.DbCashCloseUncheckedCreateWithoutClosedByInput>
}

export type DbCashCloseUpdateWithWhereUniqueWithoutClosedByInput = {
  where: Prisma.DbCashCloseWhereUniqueInput
  data: Prisma.XOR<Prisma.DbCashCloseUpdateWithoutClosedByInput, Prisma.DbCashCloseUncheckedUpdateWithoutClosedByInput>
}

export type DbCashCloseUpdateManyWithWhereWithoutClosedByInput = {
  where: Prisma.DbCashCloseScalarWhereInput
  data: Prisma.XOR<Prisma.DbCashCloseUpdateManyMutationInput, Prisma.DbCashCloseUncheckedUpdateManyWithoutClosedByInput>
}

export type DbCashCloseScalarWhereInput = {
  AND?: Prisma.DbCashCloseScalarWhereInput | Prisma.DbCashCloseScalarWhereInput[]
  OR?: Prisma.DbCashCloseScalarWhereInput[]
  NOT?: Prisma.DbCashCloseScalarWhereInput | Prisma.DbCashCloseScalarWhereInput[]
  id?: Prisma.StringFilter<"DbCashClose"> | string
  establishmentId?: Prisma.StringFilter<"DbCashClose"> | string
  closedById?: Prisma.StringFilter<"DbCashClose"> | string
  since?: Prisma.DateTimeNullableFilter<"DbCashClose"> | Date | string | null
  closedAt?: Prisma.DateTimeFilter<"DbCashClose"> | Date | string
  closedOrders?: Prisma.IntFilter<"DbCashClose"> | number
  cancelledOrders?: Prisma.IntFilter<"DbCashClose"> | number
  cancelledAmount?: Prisma.IntFilter<"DbCashClose"> | number
  cashAmount?: Prisma.IntFilter<"DbCashClose"> | number
  cardAmount?: Prisma.IntFilter<"DbCashClose"> | number
  tipAmount?: Prisma.IntFilter<"DbCashClose"> | number
  openingFloat?: Prisma.IntFilter<"DbCashClose"> | number
  countedCash?: Prisma.IntFilter<"DbCashClose"> | number
  notes?: Prisma.StringNullableFilter<"DbCashClose"> | string | null
}

export type DbCashCloseCreateWithoutEstablishmentInput = {
  id?: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
  closedBy: Prisma.DbUserCreateNestedOneWithoutCashClosesInput
  orders?: Prisma.DbOrderCreateNestedManyWithoutCashCloseInput
}

export type DbCashCloseUncheckedCreateWithoutEstablishmentInput = {
  id?: string
  closedById: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
  orders?: Prisma.DbOrderUncheckedCreateNestedManyWithoutCashCloseInput
}

export type DbCashCloseCreateOrConnectWithoutEstablishmentInput = {
  where: Prisma.DbCashCloseWhereUniqueInput
  create: Prisma.XOR<Prisma.DbCashCloseCreateWithoutEstablishmentInput, Prisma.DbCashCloseUncheckedCreateWithoutEstablishmentInput>
}

export type DbCashCloseCreateManyEstablishmentInputEnvelope = {
  data: Prisma.DbCashCloseCreateManyEstablishmentInput | Prisma.DbCashCloseCreateManyEstablishmentInput[]
  skipDuplicates?: boolean
}

export type DbCashCloseUpsertWithWhereUniqueWithoutEstablishmentInput = {
  where: Prisma.DbCashCloseWhereUniqueInput
  update: Prisma.XOR<Prisma.DbCashCloseUpdateWithoutEstablishmentInput, Prisma.DbCashCloseUncheckedUpdateWithoutEstablishmentInput>
  create: Prisma.XOR<Prisma.DbCashCloseCreateWithoutEstablishmentInput, Prisma.DbCashCloseUncheckedCreateWithoutEstablishmentInput>
}

export type DbCashCloseUpdateWithWhereUniqueWithoutEstablishmentInput = {
  where: Prisma.DbCashCloseWhereUniqueInput
  data: Prisma.XOR<Prisma.DbCashCloseUpdateWithoutEstablishmentInput, Prisma.DbCashCloseUncheckedUpdateWithoutEstablishmentInput>
}

export type DbCashCloseUpdateManyWithWhereWithoutEstablishmentInput = {
  where: Prisma.DbCashCloseScalarWhereInput
  data: Prisma.XOR<Prisma.DbCashCloseUpdateManyMutationInput, Prisma.DbCashCloseUncheckedUpdateManyWithoutEstablishmentInput>
}

export type DbCashCloseCreateWithoutOrdersInput = {
  id?: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
  establishment: Prisma.DbEstablishmentCreateNestedOneWithoutCashClosesInput
  closedBy: Prisma.DbUserCreateNestedOneWithoutCashClosesInput
}

export type DbCashCloseUncheckedCreateWithoutOrdersInput = {
  id?: string
  establishmentId: string
  closedById: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
}

export type DbCashCloseCreateOrConnectWithoutOrdersInput = {
  where: Prisma.DbCashCloseWhereUniqueInput
  create: Prisma.XOR<Prisma.DbCashCloseCreateWithoutOrdersInput, Prisma.DbCashCloseUncheckedCreateWithoutOrdersInput>
}

export type DbCashCloseUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.DbCashCloseUpdateWithoutOrdersInput, Prisma.DbCashCloseUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.DbCashCloseCreateWithoutOrdersInput, Prisma.DbCashCloseUncheckedCreateWithoutOrdersInput>
  where?: Prisma.DbCashCloseWhereInput
}

export type DbCashCloseUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.DbCashCloseWhereInput
  data: Prisma.XOR<Prisma.DbCashCloseUpdateWithoutOrdersInput, Prisma.DbCashCloseUncheckedUpdateWithoutOrdersInput>
}

export type DbCashCloseUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  establishment?: Prisma.DbEstablishmentUpdateOneRequiredWithoutCashClosesNestedInput
  closedBy?: Prisma.DbUserUpdateOneRequiredWithoutCashClosesNestedInput
}

export type DbCashCloseUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  establishmentId?: Prisma.StringFieldUpdateOperationsInput | string
  closedById?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DbCashCloseCreateManyClosedByInput = {
  id?: string
  establishmentId: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
}

export type DbCashCloseUpdateWithoutClosedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  establishment?: Prisma.DbEstablishmentUpdateOneRequiredWithoutCashClosesNestedInput
  orders?: Prisma.DbOrderUpdateManyWithoutCashCloseNestedInput
}

export type DbCashCloseUncheckedUpdateWithoutClosedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  establishmentId?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orders?: Prisma.DbOrderUncheckedUpdateManyWithoutCashCloseNestedInput
}

export type DbCashCloseUncheckedUpdateManyWithoutClosedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  establishmentId?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DbCashCloseCreateManyEstablishmentInput = {
  id?: string
  closedById: string
  since?: Date | string | null
  closedAt?: Date | string
  closedOrders: number
  cancelledOrders: number
  cancelledAmount: number
  cashAmount: number
  cardAmount: number
  tipAmount: number
  openingFloat: number
  countedCash: number
  notes?: string | null
}

export type DbCashCloseUpdateWithoutEstablishmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  closedBy?: Prisma.DbUserUpdateOneRequiredWithoutCashClosesNestedInput
  orders?: Prisma.DbOrderUpdateManyWithoutCashCloseNestedInput
}

export type DbCashCloseUncheckedUpdateWithoutEstablishmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  closedById?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orders?: Prisma.DbOrderUncheckedUpdateManyWithoutCashCloseNestedInput
}

export type DbCashCloseUncheckedUpdateManyWithoutEstablishmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  closedById?: Prisma.StringFieldUpdateOperationsInput | string
  since?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  closedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closedOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledOrders?: Prisma.IntFieldUpdateOperationsInput | number
  cancelledAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cashAmount?: Prisma.IntFieldUpdateOperationsInput | number
  cardAmount?: Prisma.IntFieldUpdateOperationsInput | number
  tipAmount?: Prisma.IntFieldUpdateOperationsInput | number
  openingFloat?: Prisma.IntFieldUpdateOperationsInput | number
  countedCash?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type DbCashCloseCountOutputType
 */

export type DbCashCloseCountOutputType = {
  orders: number
}

export type DbCashCloseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  orders?: boolean | DbCashCloseCountOutputTypeCountOrdersArgs
}

/**
 * DbCashCloseCountOutputType without action
 */
export type DbCashCloseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashCloseCountOutputType
   */
  select?: Prisma.DbCashCloseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DbCashCloseCountOutputType without action
 */
export type DbCashCloseCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DbOrderWhereInput
}


export type DbCashCloseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  establishmentId?: boolean
  closedById?: boolean
  since?: boolean
  closedAt?: boolean
  closedOrders?: boolean
  cancelledOrders?: boolean
  cancelledAmount?: boolean
  cashAmount?: boolean
  cardAmount?: boolean
  tipAmount?: boolean
  openingFloat?: boolean
  countedCash?: boolean
  notes?: boolean
  establishment?: boolean | Prisma.DbEstablishmentDefaultArgs<ExtArgs>
  closedBy?: boolean | Prisma.DbUserDefaultArgs<ExtArgs>
  orders?: boolean | Prisma.DbCashClose$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.DbCashCloseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dbCashClose"]>

export type DbCashCloseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  establishmentId?: boolean
  closedById?: boolean
  since?: boolean
  closedAt?: boolean
  closedOrders?: boolean
  cancelledOrders?: boolean
  cancelledAmount?: boolean
  cashAmount?: boolean
  cardAmount?: boolean
  tipAmount?: boolean
  openingFloat?: boolean
  countedCash?: boolean
  notes?: boolean
  establishment?: boolean | Prisma.DbEstablishmentDefaultArgs<ExtArgs>
  closedBy?: boolean | Prisma.DbUserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dbCashClose"]>

export type DbCashCloseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  establishmentId?: boolean
  closedById?: boolean
  since?: boolean
  closedAt?: boolean
  closedOrders?: boolean
  cancelledOrders?: boolean
  cancelledAmount?: boolean
  cashAmount?: boolean
  cardAmount?: boolean
  tipAmount?: boolean
  openingFloat?: boolean
  countedCash?: boolean
  notes?: boolean
  establishment?: boolean | Prisma.DbEstablishmentDefaultArgs<ExtArgs>
  closedBy?: boolean | Prisma.DbUserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dbCashClose"]>

export type DbCashCloseSelectScalar = {
  id?: boolean
  establishmentId?: boolean
  closedById?: boolean
  since?: boolean
  closedAt?: boolean
  closedOrders?: boolean
  cancelledOrders?: boolean
  cancelledAmount?: boolean
  cashAmount?: boolean
  cardAmount?: boolean
  tipAmount?: boolean
  openingFloat?: boolean
  countedCash?: boolean
  notes?: boolean
}

export type DbCashCloseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "establishmentId" | "closedById" | "since" | "closedAt" | "closedOrders" | "cancelledOrders" | "cancelledAmount" | "cashAmount" | "cardAmount" | "tipAmount" | "openingFloat" | "countedCash" | "notes", ExtArgs["result"]["dbCashClose"]>
export type DbCashCloseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  establishment?: boolean | Prisma.DbEstablishmentDefaultArgs<ExtArgs>
  closedBy?: boolean | Prisma.DbUserDefaultArgs<ExtArgs>
  orders?: boolean | Prisma.DbCashClose$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.DbCashCloseCountOutputTypeDefaultArgs<ExtArgs>
}
export type DbCashCloseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  establishment?: boolean | Prisma.DbEstablishmentDefaultArgs<ExtArgs>
  closedBy?: boolean | Prisma.DbUserDefaultArgs<ExtArgs>
}
export type DbCashCloseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  establishment?: boolean | Prisma.DbEstablishmentDefaultArgs<ExtArgs>
  closedBy?: boolean | Prisma.DbUserDefaultArgs<ExtArgs>
}

export type $DbCashClosePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DbCashClose"
  objects: {
    establishment: Prisma.$DbEstablishmentPayload<ExtArgs>
    closedBy: Prisma.$DbUserPayload<ExtArgs>
    orders: Prisma.$DbOrderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    establishmentId: string
    closedById: string
    since: Date | null
    closedAt: Date
    closedOrders: number
    cancelledOrders: number
    cancelledAmount: number
    cashAmount: number
    cardAmount: number
    tipAmount: number
    openingFloat: number
    countedCash: number
    notes: string | null
  }, ExtArgs["result"]["dbCashClose"]>
  composites: {}
}

export type DbCashCloseGetPayload<S extends boolean | null | undefined | DbCashCloseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload, S>

export type DbCashCloseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DbCashCloseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DbCashCloseCountAggregateInputType | true
  }

export interface DbCashCloseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DbCashClose'], meta: { name: 'DbCashClose' } }
  /**
   * Find zero or one DbCashClose that matches the filter.
   * @param {DbCashCloseFindUniqueArgs} args - Arguments to find a DbCashClose
   * @example
   * // Get one DbCashClose
   * const dbCashClose = await prisma.dbCashClose.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DbCashCloseFindUniqueArgs>(args: Prisma.SelectSubset<T, DbCashCloseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DbCashCloseClient<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DbCashClose that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DbCashCloseFindUniqueOrThrowArgs} args - Arguments to find a DbCashClose
   * @example
   * // Get one DbCashClose
   * const dbCashClose = await prisma.dbCashClose.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DbCashCloseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DbCashCloseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbCashCloseClient<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbCashClose that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbCashCloseFindFirstArgs} args - Arguments to find a DbCashClose
   * @example
   * // Get one DbCashClose
   * const dbCashClose = await prisma.dbCashClose.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DbCashCloseFindFirstArgs>(args?: Prisma.SelectSubset<T, DbCashCloseFindFirstArgs<ExtArgs>>): Prisma.Prisma__DbCashCloseClient<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbCashClose that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbCashCloseFindFirstOrThrowArgs} args - Arguments to find a DbCashClose
   * @example
   * // Get one DbCashClose
   * const dbCashClose = await prisma.dbCashClose.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DbCashCloseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DbCashCloseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbCashCloseClient<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DbCashCloses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbCashCloseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DbCashCloses
   * const dbCashCloses = await prisma.dbCashClose.findMany()
   * 
   * // Get first 10 DbCashCloses
   * const dbCashCloses = await prisma.dbCashClose.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dbCashCloseWithIdOnly = await prisma.dbCashClose.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DbCashCloseFindManyArgs>(args?: Prisma.SelectSubset<T, DbCashCloseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DbCashClose.
   * @param {DbCashCloseCreateArgs} args - Arguments to create a DbCashClose.
   * @example
   * // Create one DbCashClose
   * const DbCashClose = await prisma.dbCashClose.create({
   *   data: {
   *     // ... data to create a DbCashClose
   *   }
   * })
   * 
   */
  create<T extends DbCashCloseCreateArgs>(args: Prisma.SelectSubset<T, DbCashCloseCreateArgs<ExtArgs>>): Prisma.Prisma__DbCashCloseClient<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DbCashCloses.
   * @param {DbCashCloseCreateManyArgs} args - Arguments to create many DbCashCloses.
   * @example
   * // Create many DbCashCloses
   * const dbCashClose = await prisma.dbCashClose.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DbCashCloseCreateManyArgs>(args?: Prisma.SelectSubset<T, DbCashCloseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DbCashCloses and returns the data saved in the database.
   * @param {DbCashCloseCreateManyAndReturnArgs} args - Arguments to create many DbCashCloses.
   * @example
   * // Create many DbCashCloses
   * const dbCashClose = await prisma.dbCashClose.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DbCashCloses and only return the `id`
   * const dbCashCloseWithIdOnly = await prisma.dbCashClose.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DbCashCloseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DbCashCloseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DbCashClose.
   * @param {DbCashCloseDeleteArgs} args - Arguments to delete one DbCashClose.
   * @example
   * // Delete one DbCashClose
   * const DbCashClose = await prisma.dbCashClose.delete({
   *   where: {
   *     // ... filter to delete one DbCashClose
   *   }
   * })
   * 
   */
  delete<T extends DbCashCloseDeleteArgs>(args: Prisma.SelectSubset<T, DbCashCloseDeleteArgs<ExtArgs>>): Prisma.Prisma__DbCashCloseClient<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DbCashClose.
   * @param {DbCashCloseUpdateArgs} args - Arguments to update one DbCashClose.
   * @example
   * // Update one DbCashClose
   * const dbCashClose = await prisma.dbCashClose.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DbCashCloseUpdateArgs>(args: Prisma.SelectSubset<T, DbCashCloseUpdateArgs<ExtArgs>>): Prisma.Prisma__DbCashCloseClient<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DbCashCloses.
   * @param {DbCashCloseDeleteManyArgs} args - Arguments to filter DbCashCloses to delete.
   * @example
   * // Delete a few DbCashCloses
   * const { count } = await prisma.dbCashClose.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DbCashCloseDeleteManyArgs>(args?: Prisma.SelectSubset<T, DbCashCloseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbCashCloses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbCashCloseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DbCashCloses
   * const dbCashClose = await prisma.dbCashClose.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DbCashCloseUpdateManyArgs>(args: Prisma.SelectSubset<T, DbCashCloseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbCashCloses and returns the data updated in the database.
   * @param {DbCashCloseUpdateManyAndReturnArgs} args - Arguments to update many DbCashCloses.
   * @example
   * // Update many DbCashCloses
   * const dbCashClose = await prisma.dbCashClose.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DbCashCloses and only return the `id`
   * const dbCashCloseWithIdOnly = await prisma.dbCashClose.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DbCashCloseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DbCashCloseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DbCashClose.
   * @param {DbCashCloseUpsertArgs} args - Arguments to update or create a DbCashClose.
   * @example
   * // Update or create a DbCashClose
   * const dbCashClose = await prisma.dbCashClose.upsert({
   *   create: {
   *     // ... data to create a DbCashClose
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DbCashClose we want to update
   *   }
   * })
   */
  upsert<T extends DbCashCloseUpsertArgs>(args: Prisma.SelectSubset<T, DbCashCloseUpsertArgs<ExtArgs>>): Prisma.Prisma__DbCashCloseClient<runtime.Types.Result.GetResult<Prisma.$DbCashClosePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DbCashCloses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbCashCloseCountArgs} args - Arguments to filter DbCashCloses to count.
   * @example
   * // Count the number of DbCashCloses
   * const count = await prisma.dbCashClose.count({
   *   where: {
   *     // ... the filter for the DbCashCloses we want to count
   *   }
   * })
  **/
  count<T extends DbCashCloseCountArgs>(
    args?: Prisma.Subset<T, DbCashCloseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DbCashCloseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DbCashClose.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbCashCloseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DbCashCloseAggregateArgs>(args: Prisma.Subset<T, DbCashCloseAggregateArgs>): Prisma.PrismaPromise<GetDbCashCloseAggregateType<T>>

  /**
   * Group by DbCashClose.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbCashCloseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DbCashCloseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DbCashCloseGroupByArgs['orderBy'] }
      : { orderBy?: DbCashCloseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DbCashCloseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDbCashCloseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DbCashClose model
 */
readonly fields: DbCashCloseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DbCashClose.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DbCashCloseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  establishment<T extends Prisma.DbEstablishmentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DbEstablishmentDefaultArgs<ExtArgs>>): Prisma.Prisma__DbEstablishmentClient<runtime.Types.Result.GetResult<Prisma.$DbEstablishmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  closedBy<T extends Prisma.DbUserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DbUserDefaultArgs<ExtArgs>>): Prisma.Prisma__DbUserClient<runtime.Types.Result.GetResult<Prisma.$DbUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  orders<T extends Prisma.DbCashClose$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DbCashClose$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DbCashClose model
 */
export interface DbCashCloseFieldRefs {
  readonly id: Prisma.FieldRef<"DbCashClose", 'String'>
  readonly establishmentId: Prisma.FieldRef<"DbCashClose", 'String'>
  readonly closedById: Prisma.FieldRef<"DbCashClose", 'String'>
  readonly since: Prisma.FieldRef<"DbCashClose", 'DateTime'>
  readonly closedAt: Prisma.FieldRef<"DbCashClose", 'DateTime'>
  readonly closedOrders: Prisma.FieldRef<"DbCashClose", 'Int'>
  readonly cancelledOrders: Prisma.FieldRef<"DbCashClose", 'Int'>
  readonly cancelledAmount: Prisma.FieldRef<"DbCashClose", 'Int'>
  readonly cashAmount: Prisma.FieldRef<"DbCashClose", 'Int'>
  readonly cardAmount: Prisma.FieldRef<"DbCashClose", 'Int'>
  readonly tipAmount: Prisma.FieldRef<"DbCashClose", 'Int'>
  readonly openingFloat: Prisma.FieldRef<"DbCashClose", 'Int'>
  readonly countedCash: Prisma.FieldRef<"DbCashClose", 'Int'>
  readonly notes: Prisma.FieldRef<"DbCashClose", 'String'>
}
    

// Custom InputTypes
/**
 * DbCashClose findUnique
 */
export type DbCashCloseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseInclude<ExtArgs> | null
  /**
   * Filter, which DbCashClose to fetch.
   */
  where: Prisma.DbCashCloseWhereUniqueInput
}

/**
 * DbCashClose findUniqueOrThrow
 */
export type DbCashCloseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseInclude<ExtArgs> | null
  /**
   * Filter, which DbCashClose to fetch.
   */
  where: Prisma.DbCashCloseWhereUniqueInput
}

/**
 * DbCashClose findFirst
 */
export type DbCashCloseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseInclude<ExtArgs> | null
  /**
   * Filter, which DbCashClose to fetch.
   */
  where?: Prisma.DbCashCloseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbCashCloses to fetch.
   */
  orderBy?: Prisma.DbCashCloseOrderByWithRelationInput | Prisma.DbCashCloseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbCashCloses.
   */
  cursor?: Prisma.DbCashCloseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbCashCloses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbCashCloses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbCashCloses.
   */
  distinct?: Prisma.DbCashCloseScalarFieldEnum | Prisma.DbCashCloseScalarFieldEnum[]
}

/**
 * DbCashClose findFirstOrThrow
 */
export type DbCashCloseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseInclude<ExtArgs> | null
  /**
   * Filter, which DbCashClose to fetch.
   */
  where?: Prisma.DbCashCloseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbCashCloses to fetch.
   */
  orderBy?: Prisma.DbCashCloseOrderByWithRelationInput | Prisma.DbCashCloseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbCashCloses.
   */
  cursor?: Prisma.DbCashCloseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbCashCloses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbCashCloses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbCashCloses.
   */
  distinct?: Prisma.DbCashCloseScalarFieldEnum | Prisma.DbCashCloseScalarFieldEnum[]
}

/**
 * DbCashClose findMany
 */
export type DbCashCloseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseInclude<ExtArgs> | null
  /**
   * Filter, which DbCashCloses to fetch.
   */
  where?: Prisma.DbCashCloseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbCashCloses to fetch.
   */
  orderBy?: Prisma.DbCashCloseOrderByWithRelationInput | Prisma.DbCashCloseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DbCashCloses.
   */
  cursor?: Prisma.DbCashCloseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbCashCloses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbCashCloses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbCashCloses.
   */
  distinct?: Prisma.DbCashCloseScalarFieldEnum | Prisma.DbCashCloseScalarFieldEnum[]
}

/**
 * DbCashClose create
 */
export type DbCashCloseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseInclude<ExtArgs> | null
  /**
   * The data needed to create a DbCashClose.
   */
  data: Prisma.XOR<Prisma.DbCashCloseCreateInput, Prisma.DbCashCloseUncheckedCreateInput>
}

/**
 * DbCashClose createMany
 */
export type DbCashCloseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DbCashCloses.
   */
  data: Prisma.DbCashCloseCreateManyInput | Prisma.DbCashCloseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DbCashClose createManyAndReturn
 */
export type DbCashCloseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * The data used to create many DbCashCloses.
   */
  data: Prisma.DbCashCloseCreateManyInput | Prisma.DbCashCloseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DbCashClose update
 */
export type DbCashCloseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseInclude<ExtArgs> | null
  /**
   * The data needed to update a DbCashClose.
   */
  data: Prisma.XOR<Prisma.DbCashCloseUpdateInput, Prisma.DbCashCloseUncheckedUpdateInput>
  /**
   * Choose, which DbCashClose to update.
   */
  where: Prisma.DbCashCloseWhereUniqueInput
}

/**
 * DbCashClose updateMany
 */
export type DbCashCloseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DbCashCloses.
   */
  data: Prisma.XOR<Prisma.DbCashCloseUpdateManyMutationInput, Prisma.DbCashCloseUncheckedUpdateManyInput>
  /**
   * Filter which DbCashCloses to update
   */
  where?: Prisma.DbCashCloseWhereInput
  /**
   * Limit how many DbCashCloses to update.
   */
  limit?: number
}

/**
 * DbCashClose updateManyAndReturn
 */
export type DbCashCloseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * The data used to update DbCashCloses.
   */
  data: Prisma.XOR<Prisma.DbCashCloseUpdateManyMutationInput, Prisma.DbCashCloseUncheckedUpdateManyInput>
  /**
   * Filter which DbCashCloses to update
   */
  where?: Prisma.DbCashCloseWhereInput
  /**
   * Limit how many DbCashCloses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DbCashClose upsert
 */
export type DbCashCloseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseInclude<ExtArgs> | null
  /**
   * The filter to search for the DbCashClose to update in case it exists.
   */
  where: Prisma.DbCashCloseWhereUniqueInput
  /**
   * In case the DbCashClose found by the `where` argument doesn't exist, create a new DbCashClose with this data.
   */
  create: Prisma.XOR<Prisma.DbCashCloseCreateInput, Prisma.DbCashCloseUncheckedCreateInput>
  /**
   * In case the DbCashClose was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DbCashCloseUpdateInput, Prisma.DbCashCloseUncheckedUpdateInput>
}

/**
 * DbCashClose delete
 */
export type DbCashCloseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseInclude<ExtArgs> | null
  /**
   * Filter which DbCashClose to delete.
   */
  where: Prisma.DbCashCloseWhereUniqueInput
}

/**
 * DbCashClose deleteMany
 */
export type DbCashCloseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbCashCloses to delete
   */
  where?: Prisma.DbCashCloseWhereInput
  /**
   * Limit how many DbCashCloses to delete.
   */
  limit?: number
}

/**
 * DbCashClose.orders
 */
export type DbCashClose$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrder
   */
  select?: Prisma.DbOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrder
   */
  omit?: Prisma.DbOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderInclude<ExtArgs> | null
  where?: Prisma.DbOrderWhereInput
  orderBy?: Prisma.DbOrderOrderByWithRelationInput | Prisma.DbOrderOrderByWithRelationInput[]
  cursor?: Prisma.DbOrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DbOrderScalarFieldEnum | Prisma.DbOrderScalarFieldEnum[]
}

/**
 * DbCashClose without action
 */
export type DbCashCloseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbCashClose
   */
  select?: Prisma.DbCashCloseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbCashClose
   */
  omit?: Prisma.DbCashCloseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbCashCloseInclude<ExtArgs> | null
}
