
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DbFichitSettings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DbFichitSettings
 * 
 */
export type DbFichitSettingsModel = runtime.Types.Result.DefaultSelection<Prisma.$DbFichitSettingsPayload>

export type AggregateDbFichitSettings = {
  _count: DbFichitSettingsCountAggregateOutputType | null
  _min: DbFichitSettingsMinAggregateOutputType | null
  _max: DbFichitSettingsMaxAggregateOutputType | null
}

export type DbFichitSettingsMinAggregateOutputType = {
  id: string | null
  apiUrl: string | null
  apiKeyCipher: string | null
  updatedById: string | null
  updatedAt: Date | null
}

export type DbFichitSettingsMaxAggregateOutputType = {
  id: string | null
  apiUrl: string | null
  apiKeyCipher: string | null
  updatedById: string | null
  updatedAt: Date | null
}

export type DbFichitSettingsCountAggregateOutputType = {
  id: number
  apiUrl: number
  apiKeyCipher: number
  updatedById: number
  updatedAt: number
  _all: number
}


export type DbFichitSettingsMinAggregateInputType = {
  id?: true
  apiUrl?: true
  apiKeyCipher?: true
  updatedById?: true
  updatedAt?: true
}

export type DbFichitSettingsMaxAggregateInputType = {
  id?: true
  apiUrl?: true
  apiKeyCipher?: true
  updatedById?: true
  updatedAt?: true
}

export type DbFichitSettingsCountAggregateInputType = {
  id?: true
  apiUrl?: true
  apiKeyCipher?: true
  updatedById?: true
  updatedAt?: true
  _all?: true
}

export type DbFichitSettingsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbFichitSettings to aggregate.
   */
  where?: Prisma.DbFichitSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbFichitSettings to fetch.
   */
  orderBy?: Prisma.DbFichitSettingsOrderByWithRelationInput | Prisma.DbFichitSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DbFichitSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbFichitSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbFichitSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DbFichitSettings
  **/
  _count?: true | DbFichitSettingsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DbFichitSettingsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DbFichitSettingsMaxAggregateInputType
}

export type GetDbFichitSettingsAggregateType<T extends DbFichitSettingsAggregateArgs> = {
      [P in keyof T & keyof AggregateDbFichitSettings]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDbFichitSettings[P]>
    : Prisma.GetScalarType<T[P], AggregateDbFichitSettings[P]>
}




export type DbFichitSettingsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DbFichitSettingsWhereInput
  orderBy?: Prisma.DbFichitSettingsOrderByWithAggregationInput | Prisma.DbFichitSettingsOrderByWithAggregationInput[]
  by: Prisma.DbFichitSettingsScalarFieldEnum[] | Prisma.DbFichitSettingsScalarFieldEnum
  having?: Prisma.DbFichitSettingsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DbFichitSettingsCountAggregateInputType | true
  _min?: DbFichitSettingsMinAggregateInputType
  _max?: DbFichitSettingsMaxAggregateInputType
}

export type DbFichitSettingsGroupByOutputType = {
  id: string
  apiUrl: string | null
  apiKeyCipher: string | null
  updatedById: string | null
  updatedAt: Date
  _count: DbFichitSettingsCountAggregateOutputType | null
  _min: DbFichitSettingsMinAggregateOutputType | null
  _max: DbFichitSettingsMaxAggregateOutputType | null
}

export type GetDbFichitSettingsGroupByPayload<T extends DbFichitSettingsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DbFichitSettingsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DbFichitSettingsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DbFichitSettingsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DbFichitSettingsGroupByOutputType[P]>
      }
    >
  >



export type DbFichitSettingsWhereInput = {
  AND?: Prisma.DbFichitSettingsWhereInput | Prisma.DbFichitSettingsWhereInput[]
  OR?: Prisma.DbFichitSettingsWhereInput[]
  NOT?: Prisma.DbFichitSettingsWhereInput | Prisma.DbFichitSettingsWhereInput[]
  id?: Prisma.StringFilter<"DbFichitSettings"> | string
  apiUrl?: Prisma.StringNullableFilter<"DbFichitSettings"> | string | null
  apiKeyCipher?: Prisma.StringNullableFilter<"DbFichitSettings"> | string | null
  updatedById?: Prisma.StringNullableFilter<"DbFichitSettings"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"DbFichitSettings"> | Date | string
  updatedBy?: Prisma.XOR<Prisma.DbUserNullableScalarRelationFilter, Prisma.DbUserWhereInput> | null
}

export type DbFichitSettingsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  apiUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  apiKeyCipher?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedById?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedBy?: Prisma.DbUserOrderByWithRelationInput
}

export type DbFichitSettingsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DbFichitSettingsWhereInput | Prisma.DbFichitSettingsWhereInput[]
  OR?: Prisma.DbFichitSettingsWhereInput[]
  NOT?: Prisma.DbFichitSettingsWhereInput | Prisma.DbFichitSettingsWhereInput[]
  apiUrl?: Prisma.StringNullableFilter<"DbFichitSettings"> | string | null
  apiKeyCipher?: Prisma.StringNullableFilter<"DbFichitSettings"> | string | null
  updatedById?: Prisma.StringNullableFilter<"DbFichitSettings"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"DbFichitSettings"> | Date | string
  updatedBy?: Prisma.XOR<Prisma.DbUserNullableScalarRelationFilter, Prisma.DbUserWhereInput> | null
}, "id">

export type DbFichitSettingsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  apiUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  apiKeyCipher?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedById?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DbFichitSettingsCountOrderByAggregateInput
  _max?: Prisma.DbFichitSettingsMaxOrderByAggregateInput
  _min?: Prisma.DbFichitSettingsMinOrderByAggregateInput
}

export type DbFichitSettingsScalarWhereWithAggregatesInput = {
  AND?: Prisma.DbFichitSettingsScalarWhereWithAggregatesInput | Prisma.DbFichitSettingsScalarWhereWithAggregatesInput[]
  OR?: Prisma.DbFichitSettingsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DbFichitSettingsScalarWhereWithAggregatesInput | Prisma.DbFichitSettingsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DbFichitSettings"> | string
  apiUrl?: Prisma.StringNullableWithAggregatesFilter<"DbFichitSettings"> | string | null
  apiKeyCipher?: Prisma.StringNullableWithAggregatesFilter<"DbFichitSettings"> | string | null
  updatedById?: Prisma.StringNullableWithAggregatesFilter<"DbFichitSettings"> | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DbFichitSettings"> | Date | string
}

export type DbFichitSettingsCreateInput = {
  id?: string
  apiUrl?: string | null
  apiKeyCipher?: string | null
  updatedAt?: Date | string
  updatedBy?: Prisma.DbUserCreateNestedOneWithoutFichitSettingsInput
}

export type DbFichitSettingsUncheckedCreateInput = {
  id?: string
  apiUrl?: string | null
  apiKeyCipher?: string | null
  updatedById?: string | null
  updatedAt?: Date | string
}

export type DbFichitSettingsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiKeyCipher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.DbUserUpdateOneWithoutFichitSettingsNestedInput
}

export type DbFichitSettingsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiKeyCipher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbFichitSettingsCreateManyInput = {
  id?: string
  apiUrl?: string | null
  apiKeyCipher?: string | null
  updatedById?: string | null
  updatedAt?: Date | string
}

export type DbFichitSettingsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiKeyCipher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbFichitSettingsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiKeyCipher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbFichitSettingsListRelationFilter = {
  every?: Prisma.DbFichitSettingsWhereInput
  some?: Prisma.DbFichitSettingsWhereInput
  none?: Prisma.DbFichitSettingsWhereInput
}

export type DbFichitSettingsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DbFichitSettingsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  apiUrl?: Prisma.SortOrder
  apiKeyCipher?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DbFichitSettingsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  apiUrl?: Prisma.SortOrder
  apiKeyCipher?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DbFichitSettingsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  apiUrl?: Prisma.SortOrder
  apiKeyCipher?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DbFichitSettingsCreateNestedManyWithoutUpdatedByInput = {
  create?: Prisma.XOR<Prisma.DbFichitSettingsCreateWithoutUpdatedByInput, Prisma.DbFichitSettingsUncheckedCreateWithoutUpdatedByInput> | Prisma.DbFichitSettingsCreateWithoutUpdatedByInput[] | Prisma.DbFichitSettingsUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.DbFichitSettingsCreateOrConnectWithoutUpdatedByInput | Prisma.DbFichitSettingsCreateOrConnectWithoutUpdatedByInput[]
  createMany?: Prisma.DbFichitSettingsCreateManyUpdatedByInputEnvelope
  connect?: Prisma.DbFichitSettingsWhereUniqueInput | Prisma.DbFichitSettingsWhereUniqueInput[]
}

export type DbFichitSettingsUncheckedCreateNestedManyWithoutUpdatedByInput = {
  create?: Prisma.XOR<Prisma.DbFichitSettingsCreateWithoutUpdatedByInput, Prisma.DbFichitSettingsUncheckedCreateWithoutUpdatedByInput> | Prisma.DbFichitSettingsCreateWithoutUpdatedByInput[] | Prisma.DbFichitSettingsUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.DbFichitSettingsCreateOrConnectWithoutUpdatedByInput | Prisma.DbFichitSettingsCreateOrConnectWithoutUpdatedByInput[]
  createMany?: Prisma.DbFichitSettingsCreateManyUpdatedByInputEnvelope
  connect?: Prisma.DbFichitSettingsWhereUniqueInput | Prisma.DbFichitSettingsWhereUniqueInput[]
}

export type DbFichitSettingsUpdateManyWithoutUpdatedByNestedInput = {
  create?: Prisma.XOR<Prisma.DbFichitSettingsCreateWithoutUpdatedByInput, Prisma.DbFichitSettingsUncheckedCreateWithoutUpdatedByInput> | Prisma.DbFichitSettingsCreateWithoutUpdatedByInput[] | Prisma.DbFichitSettingsUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.DbFichitSettingsCreateOrConnectWithoutUpdatedByInput | Prisma.DbFichitSettingsCreateOrConnectWithoutUpdatedByInput[]
  upsert?: Prisma.DbFichitSettingsUpsertWithWhereUniqueWithoutUpdatedByInput | Prisma.DbFichitSettingsUpsertWithWhereUniqueWithoutUpdatedByInput[]
  createMany?: Prisma.DbFichitSettingsCreateManyUpdatedByInputEnvelope
  set?: Prisma.DbFichitSettingsWhereUniqueInput | Prisma.DbFichitSettingsWhereUniqueInput[]
  disconnect?: Prisma.DbFichitSettingsWhereUniqueInput | Prisma.DbFichitSettingsWhereUniqueInput[]
  delete?: Prisma.DbFichitSettingsWhereUniqueInput | Prisma.DbFichitSettingsWhereUniqueInput[]
  connect?: Prisma.DbFichitSettingsWhereUniqueInput | Prisma.DbFichitSettingsWhereUniqueInput[]
  update?: Prisma.DbFichitSettingsUpdateWithWhereUniqueWithoutUpdatedByInput | Prisma.DbFichitSettingsUpdateWithWhereUniqueWithoutUpdatedByInput[]
  updateMany?: Prisma.DbFichitSettingsUpdateManyWithWhereWithoutUpdatedByInput | Prisma.DbFichitSettingsUpdateManyWithWhereWithoutUpdatedByInput[]
  deleteMany?: Prisma.DbFichitSettingsScalarWhereInput | Prisma.DbFichitSettingsScalarWhereInput[]
}

export type DbFichitSettingsUncheckedUpdateManyWithoutUpdatedByNestedInput = {
  create?: Prisma.XOR<Prisma.DbFichitSettingsCreateWithoutUpdatedByInput, Prisma.DbFichitSettingsUncheckedCreateWithoutUpdatedByInput> | Prisma.DbFichitSettingsCreateWithoutUpdatedByInput[] | Prisma.DbFichitSettingsUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.DbFichitSettingsCreateOrConnectWithoutUpdatedByInput | Prisma.DbFichitSettingsCreateOrConnectWithoutUpdatedByInput[]
  upsert?: Prisma.DbFichitSettingsUpsertWithWhereUniqueWithoutUpdatedByInput | Prisma.DbFichitSettingsUpsertWithWhereUniqueWithoutUpdatedByInput[]
  createMany?: Prisma.DbFichitSettingsCreateManyUpdatedByInputEnvelope
  set?: Prisma.DbFichitSettingsWhereUniqueInput | Prisma.DbFichitSettingsWhereUniqueInput[]
  disconnect?: Prisma.DbFichitSettingsWhereUniqueInput | Prisma.DbFichitSettingsWhereUniqueInput[]
  delete?: Prisma.DbFichitSettingsWhereUniqueInput | Prisma.DbFichitSettingsWhereUniqueInput[]
  connect?: Prisma.DbFichitSettingsWhereUniqueInput | Prisma.DbFichitSettingsWhereUniqueInput[]
  update?: Prisma.DbFichitSettingsUpdateWithWhereUniqueWithoutUpdatedByInput | Prisma.DbFichitSettingsUpdateWithWhereUniqueWithoutUpdatedByInput[]
  updateMany?: Prisma.DbFichitSettingsUpdateManyWithWhereWithoutUpdatedByInput | Prisma.DbFichitSettingsUpdateManyWithWhereWithoutUpdatedByInput[]
  deleteMany?: Prisma.DbFichitSettingsScalarWhereInput | Prisma.DbFichitSettingsScalarWhereInput[]
}

export type DbFichitSettingsCreateWithoutUpdatedByInput = {
  id?: string
  apiUrl?: string | null
  apiKeyCipher?: string | null
  updatedAt?: Date | string
}

export type DbFichitSettingsUncheckedCreateWithoutUpdatedByInput = {
  id?: string
  apiUrl?: string | null
  apiKeyCipher?: string | null
  updatedAt?: Date | string
}

export type DbFichitSettingsCreateOrConnectWithoutUpdatedByInput = {
  where: Prisma.DbFichitSettingsWhereUniqueInput
  create: Prisma.XOR<Prisma.DbFichitSettingsCreateWithoutUpdatedByInput, Prisma.DbFichitSettingsUncheckedCreateWithoutUpdatedByInput>
}

export type DbFichitSettingsCreateManyUpdatedByInputEnvelope = {
  data: Prisma.DbFichitSettingsCreateManyUpdatedByInput | Prisma.DbFichitSettingsCreateManyUpdatedByInput[]
  skipDuplicates?: boolean
}

export type DbFichitSettingsUpsertWithWhereUniqueWithoutUpdatedByInput = {
  where: Prisma.DbFichitSettingsWhereUniqueInput
  update: Prisma.XOR<Prisma.DbFichitSettingsUpdateWithoutUpdatedByInput, Prisma.DbFichitSettingsUncheckedUpdateWithoutUpdatedByInput>
  create: Prisma.XOR<Prisma.DbFichitSettingsCreateWithoutUpdatedByInput, Prisma.DbFichitSettingsUncheckedCreateWithoutUpdatedByInput>
}

export type DbFichitSettingsUpdateWithWhereUniqueWithoutUpdatedByInput = {
  where: Prisma.DbFichitSettingsWhereUniqueInput
  data: Prisma.XOR<Prisma.DbFichitSettingsUpdateWithoutUpdatedByInput, Prisma.DbFichitSettingsUncheckedUpdateWithoutUpdatedByInput>
}

export type DbFichitSettingsUpdateManyWithWhereWithoutUpdatedByInput = {
  where: Prisma.DbFichitSettingsScalarWhereInput
  data: Prisma.XOR<Prisma.DbFichitSettingsUpdateManyMutationInput, Prisma.DbFichitSettingsUncheckedUpdateManyWithoutUpdatedByInput>
}

export type DbFichitSettingsScalarWhereInput = {
  AND?: Prisma.DbFichitSettingsScalarWhereInput | Prisma.DbFichitSettingsScalarWhereInput[]
  OR?: Prisma.DbFichitSettingsScalarWhereInput[]
  NOT?: Prisma.DbFichitSettingsScalarWhereInput | Prisma.DbFichitSettingsScalarWhereInput[]
  id?: Prisma.StringFilter<"DbFichitSettings"> | string
  apiUrl?: Prisma.StringNullableFilter<"DbFichitSettings"> | string | null
  apiKeyCipher?: Prisma.StringNullableFilter<"DbFichitSettings"> | string | null
  updatedById?: Prisma.StringNullableFilter<"DbFichitSettings"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"DbFichitSettings"> | Date | string
}

export type DbFichitSettingsCreateManyUpdatedByInput = {
  id?: string
  apiUrl?: string | null
  apiKeyCipher?: string | null
  updatedAt?: Date | string
}

export type DbFichitSettingsUpdateWithoutUpdatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiKeyCipher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbFichitSettingsUncheckedUpdateWithoutUpdatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiKeyCipher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbFichitSettingsUncheckedUpdateManyWithoutUpdatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiKeyCipher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DbFichitSettingsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  apiUrl?: boolean
  apiKeyCipher?: boolean
  updatedById?: boolean
  updatedAt?: boolean
  updatedBy?: boolean | Prisma.DbFichitSettings$updatedByArgs<ExtArgs>
}, ExtArgs["result"]["dbFichitSettings"]>

export type DbFichitSettingsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  apiUrl?: boolean
  apiKeyCipher?: boolean
  updatedById?: boolean
  updatedAt?: boolean
  updatedBy?: boolean | Prisma.DbFichitSettings$updatedByArgs<ExtArgs>
}, ExtArgs["result"]["dbFichitSettings"]>

export type DbFichitSettingsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  apiUrl?: boolean
  apiKeyCipher?: boolean
  updatedById?: boolean
  updatedAt?: boolean
  updatedBy?: boolean | Prisma.DbFichitSettings$updatedByArgs<ExtArgs>
}, ExtArgs["result"]["dbFichitSettings"]>

export type DbFichitSettingsSelectScalar = {
  id?: boolean
  apiUrl?: boolean
  apiKeyCipher?: boolean
  updatedById?: boolean
  updatedAt?: boolean
}

export type DbFichitSettingsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "apiUrl" | "apiKeyCipher" | "updatedById" | "updatedAt", ExtArgs["result"]["dbFichitSettings"]>
export type DbFichitSettingsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  updatedBy?: boolean | Prisma.DbFichitSettings$updatedByArgs<ExtArgs>
}
export type DbFichitSettingsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  updatedBy?: boolean | Prisma.DbFichitSettings$updatedByArgs<ExtArgs>
}
export type DbFichitSettingsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  updatedBy?: boolean | Prisma.DbFichitSettings$updatedByArgs<ExtArgs>
}

export type $DbFichitSettingsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DbFichitSettings"
  objects: {
    updatedBy: Prisma.$DbUserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    apiUrl: string | null
    apiKeyCipher: string | null
    updatedById: string | null
    updatedAt: Date
  }, ExtArgs["result"]["dbFichitSettings"]>
  composites: {}
}

export type DbFichitSettingsGetPayload<S extends boolean | null | undefined | DbFichitSettingsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload, S>

export type DbFichitSettingsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DbFichitSettingsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DbFichitSettingsCountAggregateInputType | true
  }

export interface DbFichitSettingsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DbFichitSettings'], meta: { name: 'DbFichitSettings' } }
  /**
   * Find zero or one DbFichitSettings that matches the filter.
   * @param {DbFichitSettingsFindUniqueArgs} args - Arguments to find a DbFichitSettings
   * @example
   * // Get one DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DbFichitSettingsFindUniqueArgs>(args: Prisma.SelectSubset<T, DbFichitSettingsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DbFichitSettingsClient<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DbFichitSettings that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DbFichitSettingsFindUniqueOrThrowArgs} args - Arguments to find a DbFichitSettings
   * @example
   * // Get one DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DbFichitSettingsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DbFichitSettingsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbFichitSettingsClient<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbFichitSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbFichitSettingsFindFirstArgs} args - Arguments to find a DbFichitSettings
   * @example
   * // Get one DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DbFichitSettingsFindFirstArgs>(args?: Prisma.SelectSubset<T, DbFichitSettingsFindFirstArgs<ExtArgs>>): Prisma.Prisma__DbFichitSettingsClient<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbFichitSettings that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbFichitSettingsFindFirstOrThrowArgs} args - Arguments to find a DbFichitSettings
   * @example
   * // Get one DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DbFichitSettingsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DbFichitSettingsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbFichitSettingsClient<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DbFichitSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbFichitSettingsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.findMany()
   * 
   * // Get first 10 DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dbFichitSettingsWithIdOnly = await prisma.dbFichitSettings.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DbFichitSettingsFindManyArgs>(args?: Prisma.SelectSubset<T, DbFichitSettingsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DbFichitSettings.
   * @param {DbFichitSettingsCreateArgs} args - Arguments to create a DbFichitSettings.
   * @example
   * // Create one DbFichitSettings
   * const DbFichitSettings = await prisma.dbFichitSettings.create({
   *   data: {
   *     // ... data to create a DbFichitSettings
   *   }
   * })
   * 
   */
  create<T extends DbFichitSettingsCreateArgs>(args: Prisma.SelectSubset<T, DbFichitSettingsCreateArgs<ExtArgs>>): Prisma.Prisma__DbFichitSettingsClient<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DbFichitSettings.
   * @param {DbFichitSettingsCreateManyArgs} args - Arguments to create many DbFichitSettings.
   * @example
   * // Create many DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DbFichitSettingsCreateManyArgs>(args?: Prisma.SelectSubset<T, DbFichitSettingsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DbFichitSettings and returns the data saved in the database.
   * @param {DbFichitSettingsCreateManyAndReturnArgs} args - Arguments to create many DbFichitSettings.
   * @example
   * // Create many DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DbFichitSettings and only return the `id`
   * const dbFichitSettingsWithIdOnly = await prisma.dbFichitSettings.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DbFichitSettingsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DbFichitSettingsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DbFichitSettings.
   * @param {DbFichitSettingsDeleteArgs} args - Arguments to delete one DbFichitSettings.
   * @example
   * // Delete one DbFichitSettings
   * const DbFichitSettings = await prisma.dbFichitSettings.delete({
   *   where: {
   *     // ... filter to delete one DbFichitSettings
   *   }
   * })
   * 
   */
  delete<T extends DbFichitSettingsDeleteArgs>(args: Prisma.SelectSubset<T, DbFichitSettingsDeleteArgs<ExtArgs>>): Prisma.Prisma__DbFichitSettingsClient<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DbFichitSettings.
   * @param {DbFichitSettingsUpdateArgs} args - Arguments to update one DbFichitSettings.
   * @example
   * // Update one DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DbFichitSettingsUpdateArgs>(args: Prisma.SelectSubset<T, DbFichitSettingsUpdateArgs<ExtArgs>>): Prisma.Prisma__DbFichitSettingsClient<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DbFichitSettings.
   * @param {DbFichitSettingsDeleteManyArgs} args - Arguments to filter DbFichitSettings to delete.
   * @example
   * // Delete a few DbFichitSettings
   * const { count } = await prisma.dbFichitSettings.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DbFichitSettingsDeleteManyArgs>(args?: Prisma.SelectSubset<T, DbFichitSettingsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbFichitSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbFichitSettingsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DbFichitSettingsUpdateManyArgs>(args: Prisma.SelectSubset<T, DbFichitSettingsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbFichitSettings and returns the data updated in the database.
   * @param {DbFichitSettingsUpdateManyAndReturnArgs} args - Arguments to update many DbFichitSettings.
   * @example
   * // Update many DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DbFichitSettings and only return the `id`
   * const dbFichitSettingsWithIdOnly = await prisma.dbFichitSettings.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DbFichitSettingsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DbFichitSettingsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DbFichitSettings.
   * @param {DbFichitSettingsUpsertArgs} args - Arguments to update or create a DbFichitSettings.
   * @example
   * // Update or create a DbFichitSettings
   * const dbFichitSettings = await prisma.dbFichitSettings.upsert({
   *   create: {
   *     // ... data to create a DbFichitSettings
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DbFichitSettings we want to update
   *   }
   * })
   */
  upsert<T extends DbFichitSettingsUpsertArgs>(args: Prisma.SelectSubset<T, DbFichitSettingsUpsertArgs<ExtArgs>>): Prisma.Prisma__DbFichitSettingsClient<runtime.Types.Result.GetResult<Prisma.$DbFichitSettingsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DbFichitSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbFichitSettingsCountArgs} args - Arguments to filter DbFichitSettings to count.
   * @example
   * // Count the number of DbFichitSettings
   * const count = await prisma.dbFichitSettings.count({
   *   where: {
   *     // ... the filter for the DbFichitSettings we want to count
   *   }
   * })
  **/
  count<T extends DbFichitSettingsCountArgs>(
    args?: Prisma.Subset<T, DbFichitSettingsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DbFichitSettingsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DbFichitSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbFichitSettingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DbFichitSettingsAggregateArgs>(args: Prisma.Subset<T, DbFichitSettingsAggregateArgs>): Prisma.PrismaPromise<GetDbFichitSettingsAggregateType<T>>

  /**
   * Group by DbFichitSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbFichitSettingsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DbFichitSettingsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DbFichitSettingsGroupByArgs['orderBy'] }
      : { orderBy?: DbFichitSettingsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DbFichitSettingsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDbFichitSettingsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DbFichitSettings model
 */
readonly fields: DbFichitSettingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DbFichitSettings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DbFichitSettingsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  updatedBy<T extends Prisma.DbFichitSettings$updatedByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DbFichitSettings$updatedByArgs<ExtArgs>>): Prisma.Prisma__DbUserClient<runtime.Types.Result.GetResult<Prisma.$DbUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DbFichitSettings model
 */
export interface DbFichitSettingsFieldRefs {
  readonly id: Prisma.FieldRef<"DbFichitSettings", 'String'>
  readonly apiUrl: Prisma.FieldRef<"DbFichitSettings", 'String'>
  readonly apiKeyCipher: Prisma.FieldRef<"DbFichitSettings", 'String'>
  readonly updatedById: Prisma.FieldRef<"DbFichitSettings", 'String'>
  readonly updatedAt: Prisma.FieldRef<"DbFichitSettings", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DbFichitSettings findUnique
 */
export type DbFichitSettingsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsInclude<ExtArgs> | null
  /**
   * Filter, which DbFichitSettings to fetch.
   */
  where: Prisma.DbFichitSettingsWhereUniqueInput
}

/**
 * DbFichitSettings findUniqueOrThrow
 */
export type DbFichitSettingsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsInclude<ExtArgs> | null
  /**
   * Filter, which DbFichitSettings to fetch.
   */
  where: Prisma.DbFichitSettingsWhereUniqueInput
}

/**
 * DbFichitSettings findFirst
 */
export type DbFichitSettingsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsInclude<ExtArgs> | null
  /**
   * Filter, which DbFichitSettings to fetch.
   */
  where?: Prisma.DbFichitSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbFichitSettings to fetch.
   */
  orderBy?: Prisma.DbFichitSettingsOrderByWithRelationInput | Prisma.DbFichitSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbFichitSettings.
   */
  cursor?: Prisma.DbFichitSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbFichitSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbFichitSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbFichitSettings.
   */
  distinct?: Prisma.DbFichitSettingsScalarFieldEnum | Prisma.DbFichitSettingsScalarFieldEnum[]
}

/**
 * DbFichitSettings findFirstOrThrow
 */
export type DbFichitSettingsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsInclude<ExtArgs> | null
  /**
   * Filter, which DbFichitSettings to fetch.
   */
  where?: Prisma.DbFichitSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbFichitSettings to fetch.
   */
  orderBy?: Prisma.DbFichitSettingsOrderByWithRelationInput | Prisma.DbFichitSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbFichitSettings.
   */
  cursor?: Prisma.DbFichitSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbFichitSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbFichitSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbFichitSettings.
   */
  distinct?: Prisma.DbFichitSettingsScalarFieldEnum | Prisma.DbFichitSettingsScalarFieldEnum[]
}

/**
 * DbFichitSettings findMany
 */
export type DbFichitSettingsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsInclude<ExtArgs> | null
  /**
   * Filter, which DbFichitSettings to fetch.
   */
  where?: Prisma.DbFichitSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbFichitSettings to fetch.
   */
  orderBy?: Prisma.DbFichitSettingsOrderByWithRelationInput | Prisma.DbFichitSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DbFichitSettings.
   */
  cursor?: Prisma.DbFichitSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbFichitSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbFichitSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbFichitSettings.
   */
  distinct?: Prisma.DbFichitSettingsScalarFieldEnum | Prisma.DbFichitSettingsScalarFieldEnum[]
}

/**
 * DbFichitSettings create
 */
export type DbFichitSettingsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsInclude<ExtArgs> | null
  /**
   * The data needed to create a DbFichitSettings.
   */
  data?: Prisma.XOR<Prisma.DbFichitSettingsCreateInput, Prisma.DbFichitSettingsUncheckedCreateInput>
}

/**
 * DbFichitSettings createMany
 */
export type DbFichitSettingsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DbFichitSettings.
   */
  data: Prisma.DbFichitSettingsCreateManyInput | Prisma.DbFichitSettingsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DbFichitSettings createManyAndReturn
 */
export type DbFichitSettingsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * The data used to create many DbFichitSettings.
   */
  data: Prisma.DbFichitSettingsCreateManyInput | Prisma.DbFichitSettingsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DbFichitSettings update
 */
export type DbFichitSettingsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsInclude<ExtArgs> | null
  /**
   * The data needed to update a DbFichitSettings.
   */
  data: Prisma.XOR<Prisma.DbFichitSettingsUpdateInput, Prisma.DbFichitSettingsUncheckedUpdateInput>
  /**
   * Choose, which DbFichitSettings to update.
   */
  where: Prisma.DbFichitSettingsWhereUniqueInput
}

/**
 * DbFichitSettings updateMany
 */
export type DbFichitSettingsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DbFichitSettings.
   */
  data: Prisma.XOR<Prisma.DbFichitSettingsUpdateManyMutationInput, Prisma.DbFichitSettingsUncheckedUpdateManyInput>
  /**
   * Filter which DbFichitSettings to update
   */
  where?: Prisma.DbFichitSettingsWhereInput
  /**
   * Limit how many DbFichitSettings to update.
   */
  limit?: number
}

/**
 * DbFichitSettings updateManyAndReturn
 */
export type DbFichitSettingsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * The data used to update DbFichitSettings.
   */
  data: Prisma.XOR<Prisma.DbFichitSettingsUpdateManyMutationInput, Prisma.DbFichitSettingsUncheckedUpdateManyInput>
  /**
   * Filter which DbFichitSettings to update
   */
  where?: Prisma.DbFichitSettingsWhereInput
  /**
   * Limit how many DbFichitSettings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DbFichitSettings upsert
 */
export type DbFichitSettingsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsInclude<ExtArgs> | null
  /**
   * The filter to search for the DbFichitSettings to update in case it exists.
   */
  where: Prisma.DbFichitSettingsWhereUniqueInput
  /**
   * In case the DbFichitSettings found by the `where` argument doesn't exist, create a new DbFichitSettings with this data.
   */
  create: Prisma.XOR<Prisma.DbFichitSettingsCreateInput, Prisma.DbFichitSettingsUncheckedCreateInput>
  /**
   * In case the DbFichitSettings was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DbFichitSettingsUpdateInput, Prisma.DbFichitSettingsUncheckedUpdateInput>
}

/**
 * DbFichitSettings delete
 */
export type DbFichitSettingsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsInclude<ExtArgs> | null
  /**
   * Filter which DbFichitSettings to delete.
   */
  where: Prisma.DbFichitSettingsWhereUniqueInput
}

/**
 * DbFichitSettings deleteMany
 */
export type DbFichitSettingsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbFichitSettings to delete
   */
  where?: Prisma.DbFichitSettingsWhereInput
  /**
   * Limit how many DbFichitSettings to delete.
   */
  limit?: number
}

/**
 * DbFichitSettings.updatedBy
 */
export type DbFichitSettings$updatedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbUser
   */
  select?: Prisma.DbUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbUser
   */
  omit?: Prisma.DbUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbUserInclude<ExtArgs> | null
  where?: Prisma.DbUserWhereInput
}

/**
 * DbFichitSettings without action
 */
export type DbFichitSettingsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbFichitSettings
   */
  select?: Prisma.DbFichitSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbFichitSettings
   */
  omit?: Prisma.DbFichitSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbFichitSettingsInclude<ExtArgs> | null
}
