
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DbOrderAdjustment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DbOrderAdjustment
 * 
 */
export type DbOrderAdjustmentModel = runtime.Types.Result.DefaultSelection<Prisma.$DbOrderAdjustmentPayload>

export type AggregateDbOrderAdjustment = {
  _count: DbOrderAdjustmentCountAggregateOutputType | null
  _avg: DbOrderAdjustmentAvgAggregateOutputType | null
  _sum: DbOrderAdjustmentSumAggregateOutputType | null
  _min: DbOrderAdjustmentMinAggregateOutputType | null
  _max: DbOrderAdjustmentMaxAggregateOutputType | null
}

export type DbOrderAdjustmentAvgAggregateOutputType = {
  value: number | null
}

export type DbOrderAdjustmentSumAggregateOutputType = {
  value: number | null
}

export type DbOrderAdjustmentMinAggregateOutputType = {
  id: string | null
  orderId: string | null
  target: $Enums.DbAdjustmentTarget | null
  itemId: string | null
  type: $Enums.DbAdjustmentType | null
  value: number | null
  reason: string | null
  createdAt: Date | null
}

export type DbOrderAdjustmentMaxAggregateOutputType = {
  id: string | null
  orderId: string | null
  target: $Enums.DbAdjustmentTarget | null
  itemId: string | null
  type: $Enums.DbAdjustmentType | null
  value: number | null
  reason: string | null
  createdAt: Date | null
}

export type DbOrderAdjustmentCountAggregateOutputType = {
  id: number
  orderId: number
  target: number
  itemId: number
  type: number
  value: number
  reason: number
  createdAt: number
  _all: number
}


export type DbOrderAdjustmentAvgAggregateInputType = {
  value?: true
}

export type DbOrderAdjustmentSumAggregateInputType = {
  value?: true
}

export type DbOrderAdjustmentMinAggregateInputType = {
  id?: true
  orderId?: true
  target?: true
  itemId?: true
  type?: true
  value?: true
  reason?: true
  createdAt?: true
}

export type DbOrderAdjustmentMaxAggregateInputType = {
  id?: true
  orderId?: true
  target?: true
  itemId?: true
  type?: true
  value?: true
  reason?: true
  createdAt?: true
}

export type DbOrderAdjustmentCountAggregateInputType = {
  id?: true
  orderId?: true
  target?: true
  itemId?: true
  type?: true
  value?: true
  reason?: true
  createdAt?: true
  _all?: true
}

export type DbOrderAdjustmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbOrderAdjustment to aggregate.
   */
  where?: Prisma.DbOrderAdjustmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbOrderAdjustments to fetch.
   */
  orderBy?: Prisma.DbOrderAdjustmentOrderByWithRelationInput | Prisma.DbOrderAdjustmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DbOrderAdjustmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbOrderAdjustments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbOrderAdjustments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DbOrderAdjustments
  **/
  _count?: true | DbOrderAdjustmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DbOrderAdjustmentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DbOrderAdjustmentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DbOrderAdjustmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DbOrderAdjustmentMaxAggregateInputType
}

export type GetDbOrderAdjustmentAggregateType<T extends DbOrderAdjustmentAggregateArgs> = {
      [P in keyof T & keyof AggregateDbOrderAdjustment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDbOrderAdjustment[P]>
    : Prisma.GetScalarType<T[P], AggregateDbOrderAdjustment[P]>
}




export type DbOrderAdjustmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DbOrderAdjustmentWhereInput
  orderBy?: Prisma.DbOrderAdjustmentOrderByWithAggregationInput | Prisma.DbOrderAdjustmentOrderByWithAggregationInput[]
  by: Prisma.DbOrderAdjustmentScalarFieldEnum[] | Prisma.DbOrderAdjustmentScalarFieldEnum
  having?: Prisma.DbOrderAdjustmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DbOrderAdjustmentCountAggregateInputType | true
  _avg?: DbOrderAdjustmentAvgAggregateInputType
  _sum?: DbOrderAdjustmentSumAggregateInputType
  _min?: DbOrderAdjustmentMinAggregateInputType
  _max?: DbOrderAdjustmentMaxAggregateInputType
}

export type DbOrderAdjustmentGroupByOutputType = {
  id: string
  orderId: string
  target: $Enums.DbAdjustmentTarget
  itemId: string | null
  type: $Enums.DbAdjustmentType
  value: number
  reason: string | null
  createdAt: Date
  _count: DbOrderAdjustmentCountAggregateOutputType | null
  _avg: DbOrderAdjustmentAvgAggregateOutputType | null
  _sum: DbOrderAdjustmentSumAggregateOutputType | null
  _min: DbOrderAdjustmentMinAggregateOutputType | null
  _max: DbOrderAdjustmentMaxAggregateOutputType | null
}

export type GetDbOrderAdjustmentGroupByPayload<T extends DbOrderAdjustmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DbOrderAdjustmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DbOrderAdjustmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DbOrderAdjustmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DbOrderAdjustmentGroupByOutputType[P]>
      }
    >
  >



export type DbOrderAdjustmentWhereInput = {
  AND?: Prisma.DbOrderAdjustmentWhereInput | Prisma.DbOrderAdjustmentWhereInput[]
  OR?: Prisma.DbOrderAdjustmentWhereInput[]
  NOT?: Prisma.DbOrderAdjustmentWhereInput | Prisma.DbOrderAdjustmentWhereInput[]
  id?: Prisma.StringFilter<"DbOrderAdjustment"> | string
  orderId?: Prisma.StringFilter<"DbOrderAdjustment"> | string
  target?: Prisma.EnumDbAdjustmentTargetFilter<"DbOrderAdjustment"> | $Enums.DbAdjustmentTarget
  itemId?: Prisma.StringNullableFilter<"DbOrderAdjustment"> | string | null
  type?: Prisma.EnumDbAdjustmentTypeFilter<"DbOrderAdjustment"> | $Enums.DbAdjustmentType
  value?: Prisma.IntFilter<"DbOrderAdjustment"> | number
  reason?: Prisma.StringNullableFilter<"DbOrderAdjustment"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DbOrderAdjustment"> | Date | string
  order?: Prisma.XOR<Prisma.DbOrderScalarRelationFilter, Prisma.DbOrderWhereInput>
  item?: Prisma.XOR<Prisma.DbOrderItemNullableScalarRelationFilter, Prisma.DbOrderItemWhereInput> | null
}

export type DbOrderAdjustmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  target?: Prisma.SortOrder
  itemId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  value?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  order?: Prisma.DbOrderOrderByWithRelationInput
  item?: Prisma.DbOrderItemOrderByWithRelationInput
}

export type DbOrderAdjustmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DbOrderAdjustmentWhereInput | Prisma.DbOrderAdjustmentWhereInput[]
  OR?: Prisma.DbOrderAdjustmentWhereInput[]
  NOT?: Prisma.DbOrderAdjustmentWhereInput | Prisma.DbOrderAdjustmentWhereInput[]
  orderId?: Prisma.StringFilter<"DbOrderAdjustment"> | string
  target?: Prisma.EnumDbAdjustmentTargetFilter<"DbOrderAdjustment"> | $Enums.DbAdjustmentTarget
  itemId?: Prisma.StringNullableFilter<"DbOrderAdjustment"> | string | null
  type?: Prisma.EnumDbAdjustmentTypeFilter<"DbOrderAdjustment"> | $Enums.DbAdjustmentType
  value?: Prisma.IntFilter<"DbOrderAdjustment"> | number
  reason?: Prisma.StringNullableFilter<"DbOrderAdjustment"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DbOrderAdjustment"> | Date | string
  order?: Prisma.XOR<Prisma.DbOrderScalarRelationFilter, Prisma.DbOrderWhereInput>
  item?: Prisma.XOR<Prisma.DbOrderItemNullableScalarRelationFilter, Prisma.DbOrderItemWhereInput> | null
}, "id">

export type DbOrderAdjustmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  target?: Prisma.SortOrder
  itemId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  value?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.DbOrderAdjustmentCountOrderByAggregateInput
  _avg?: Prisma.DbOrderAdjustmentAvgOrderByAggregateInput
  _max?: Prisma.DbOrderAdjustmentMaxOrderByAggregateInput
  _min?: Prisma.DbOrderAdjustmentMinOrderByAggregateInput
  _sum?: Prisma.DbOrderAdjustmentSumOrderByAggregateInput
}

export type DbOrderAdjustmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.DbOrderAdjustmentScalarWhereWithAggregatesInput | Prisma.DbOrderAdjustmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.DbOrderAdjustmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DbOrderAdjustmentScalarWhereWithAggregatesInput | Prisma.DbOrderAdjustmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DbOrderAdjustment"> | string
  orderId?: Prisma.StringWithAggregatesFilter<"DbOrderAdjustment"> | string
  target?: Prisma.EnumDbAdjustmentTargetWithAggregatesFilter<"DbOrderAdjustment"> | $Enums.DbAdjustmentTarget
  itemId?: Prisma.StringNullableWithAggregatesFilter<"DbOrderAdjustment"> | string | null
  type?: Prisma.EnumDbAdjustmentTypeWithAggregatesFilter<"DbOrderAdjustment"> | $Enums.DbAdjustmentType
  value?: Prisma.IntWithAggregatesFilter<"DbOrderAdjustment"> | number
  reason?: Prisma.StringNullableWithAggregatesFilter<"DbOrderAdjustment"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DbOrderAdjustment"> | Date | string
}

export type DbOrderAdjustmentCreateInput = {
  id?: string
  target: $Enums.DbAdjustmentTarget
  type: $Enums.DbAdjustmentType
  value: number
  reason?: string | null
  createdAt?: Date | string
  order: Prisma.DbOrderCreateNestedOneWithoutAdjustmentsInput
  item?: Prisma.DbOrderItemCreateNestedOneWithoutAdjustmentsInput
}

export type DbOrderAdjustmentUncheckedCreateInput = {
  id?: string
  orderId: string
  target: $Enums.DbAdjustmentTarget
  itemId?: string | null
  type: $Enums.DbAdjustmentType
  value: number
  reason?: string | null
  createdAt?: Date | string
}

export type DbOrderAdjustmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.EnumDbAdjustmentTargetFieldUpdateOperationsInput | $Enums.DbAdjustmentTarget
  type?: Prisma.EnumDbAdjustmentTypeFieldUpdateOperationsInput | $Enums.DbAdjustmentType
  value?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.DbOrderUpdateOneRequiredWithoutAdjustmentsNestedInput
  item?: Prisma.DbOrderItemUpdateOneWithoutAdjustmentsNestedInput
}

export type DbOrderAdjustmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.EnumDbAdjustmentTargetFieldUpdateOperationsInput | $Enums.DbAdjustmentTarget
  itemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumDbAdjustmentTypeFieldUpdateOperationsInput | $Enums.DbAdjustmentType
  value?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbOrderAdjustmentCreateManyInput = {
  id?: string
  orderId: string
  target: $Enums.DbAdjustmentTarget
  itemId?: string | null
  type: $Enums.DbAdjustmentType
  value: number
  reason?: string | null
  createdAt?: Date | string
}

export type DbOrderAdjustmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.EnumDbAdjustmentTargetFieldUpdateOperationsInput | $Enums.DbAdjustmentTarget
  type?: Prisma.EnumDbAdjustmentTypeFieldUpdateOperationsInput | $Enums.DbAdjustmentType
  value?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbOrderAdjustmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.EnumDbAdjustmentTargetFieldUpdateOperationsInput | $Enums.DbAdjustmentTarget
  itemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumDbAdjustmentTypeFieldUpdateOperationsInput | $Enums.DbAdjustmentType
  value?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbOrderAdjustmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  target?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  value?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DbOrderAdjustmentAvgOrderByAggregateInput = {
  value?: Prisma.SortOrder
}

export type DbOrderAdjustmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  target?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  value?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DbOrderAdjustmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  target?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  value?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DbOrderAdjustmentSumOrderByAggregateInput = {
  value?: Prisma.SortOrder
}

export type DbOrderAdjustmentListRelationFilter = {
  every?: Prisma.DbOrderAdjustmentWhereInput
  some?: Prisma.DbOrderAdjustmentWhereInput
  none?: Prisma.DbOrderAdjustmentWhereInput
}

export type DbOrderAdjustmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type EnumDbAdjustmentTargetFieldUpdateOperationsInput = {
  set?: $Enums.DbAdjustmentTarget
}

export type EnumDbAdjustmentTypeFieldUpdateOperationsInput = {
  set?: $Enums.DbAdjustmentType
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type DbOrderAdjustmentCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutOrderInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutOrderInput> | Prisma.DbOrderAdjustmentCreateWithoutOrderInput[] | Prisma.DbOrderAdjustmentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.DbOrderAdjustmentCreateOrConnectWithoutOrderInput | Prisma.DbOrderAdjustmentCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.DbOrderAdjustmentCreateManyOrderInputEnvelope
  connect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
}

export type DbOrderAdjustmentUncheckedCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutOrderInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutOrderInput> | Prisma.DbOrderAdjustmentCreateWithoutOrderInput[] | Prisma.DbOrderAdjustmentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.DbOrderAdjustmentCreateOrConnectWithoutOrderInput | Prisma.DbOrderAdjustmentCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.DbOrderAdjustmentCreateManyOrderInputEnvelope
  connect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
}

export type DbOrderAdjustmentUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutOrderInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutOrderInput> | Prisma.DbOrderAdjustmentCreateWithoutOrderInput[] | Prisma.DbOrderAdjustmentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.DbOrderAdjustmentCreateOrConnectWithoutOrderInput | Prisma.DbOrderAdjustmentCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.DbOrderAdjustmentUpsertWithWhereUniqueWithoutOrderInput | Prisma.DbOrderAdjustmentUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.DbOrderAdjustmentCreateManyOrderInputEnvelope
  set?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  disconnect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  delete?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  connect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  update?: Prisma.DbOrderAdjustmentUpdateWithWhereUniqueWithoutOrderInput | Prisma.DbOrderAdjustmentUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.DbOrderAdjustmentUpdateManyWithWhereWithoutOrderInput | Prisma.DbOrderAdjustmentUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.DbOrderAdjustmentScalarWhereInput | Prisma.DbOrderAdjustmentScalarWhereInput[]
}

export type DbOrderAdjustmentUncheckedUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutOrderInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutOrderInput> | Prisma.DbOrderAdjustmentCreateWithoutOrderInput[] | Prisma.DbOrderAdjustmentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.DbOrderAdjustmentCreateOrConnectWithoutOrderInput | Prisma.DbOrderAdjustmentCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.DbOrderAdjustmentUpsertWithWhereUniqueWithoutOrderInput | Prisma.DbOrderAdjustmentUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.DbOrderAdjustmentCreateManyOrderInputEnvelope
  set?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  disconnect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  delete?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  connect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  update?: Prisma.DbOrderAdjustmentUpdateWithWhereUniqueWithoutOrderInput | Prisma.DbOrderAdjustmentUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.DbOrderAdjustmentUpdateManyWithWhereWithoutOrderInput | Prisma.DbOrderAdjustmentUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.DbOrderAdjustmentScalarWhereInput | Prisma.DbOrderAdjustmentScalarWhereInput[]
}

export type DbOrderAdjustmentCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutItemInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutItemInput> | Prisma.DbOrderAdjustmentCreateWithoutItemInput[] | Prisma.DbOrderAdjustmentUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.DbOrderAdjustmentCreateOrConnectWithoutItemInput | Prisma.DbOrderAdjustmentCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.DbOrderAdjustmentCreateManyItemInputEnvelope
  connect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
}

export type DbOrderAdjustmentUncheckedCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutItemInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutItemInput> | Prisma.DbOrderAdjustmentCreateWithoutItemInput[] | Prisma.DbOrderAdjustmentUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.DbOrderAdjustmentCreateOrConnectWithoutItemInput | Prisma.DbOrderAdjustmentCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.DbOrderAdjustmentCreateManyItemInputEnvelope
  connect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
}

export type DbOrderAdjustmentUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutItemInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutItemInput> | Prisma.DbOrderAdjustmentCreateWithoutItemInput[] | Prisma.DbOrderAdjustmentUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.DbOrderAdjustmentCreateOrConnectWithoutItemInput | Prisma.DbOrderAdjustmentCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.DbOrderAdjustmentUpsertWithWhereUniqueWithoutItemInput | Prisma.DbOrderAdjustmentUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.DbOrderAdjustmentCreateManyItemInputEnvelope
  set?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  disconnect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  delete?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  connect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  update?: Prisma.DbOrderAdjustmentUpdateWithWhereUniqueWithoutItemInput | Prisma.DbOrderAdjustmentUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.DbOrderAdjustmentUpdateManyWithWhereWithoutItemInput | Prisma.DbOrderAdjustmentUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.DbOrderAdjustmentScalarWhereInput | Prisma.DbOrderAdjustmentScalarWhereInput[]
}

export type DbOrderAdjustmentUncheckedUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutItemInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutItemInput> | Prisma.DbOrderAdjustmentCreateWithoutItemInput[] | Prisma.DbOrderAdjustmentUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.DbOrderAdjustmentCreateOrConnectWithoutItemInput | Prisma.DbOrderAdjustmentCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.DbOrderAdjustmentUpsertWithWhereUniqueWithoutItemInput | Prisma.DbOrderAdjustmentUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.DbOrderAdjustmentCreateManyItemInputEnvelope
  set?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  disconnect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  delete?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  connect?: Prisma.DbOrderAdjustmentWhereUniqueInput | Prisma.DbOrderAdjustmentWhereUniqueInput[]
  update?: Prisma.DbOrderAdjustmentUpdateWithWhereUniqueWithoutItemInput | Prisma.DbOrderAdjustmentUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.DbOrderAdjustmentUpdateManyWithWhereWithoutItemInput | Prisma.DbOrderAdjustmentUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.DbOrderAdjustmentScalarWhereInput | Prisma.DbOrderAdjustmentScalarWhereInput[]
}

export type DbOrderAdjustmentCreateWithoutOrderInput = {
  id?: string
  target: $Enums.DbAdjustmentTarget
  type: $Enums.DbAdjustmentType
  value: number
  reason?: string | null
  createdAt?: Date | string
  item?: Prisma.DbOrderItemCreateNestedOneWithoutAdjustmentsInput
}

export type DbOrderAdjustmentUncheckedCreateWithoutOrderInput = {
  id?: string
  target: $Enums.DbAdjustmentTarget
  itemId?: string | null
  type: $Enums.DbAdjustmentType
  value: number
  reason?: string | null
  createdAt?: Date | string
}

export type DbOrderAdjustmentCreateOrConnectWithoutOrderInput = {
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
  create: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutOrderInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutOrderInput>
}

export type DbOrderAdjustmentCreateManyOrderInputEnvelope = {
  data: Prisma.DbOrderAdjustmentCreateManyOrderInput | Prisma.DbOrderAdjustmentCreateManyOrderInput[]
  skipDuplicates?: boolean
}

export type DbOrderAdjustmentUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
  update: Prisma.XOR<Prisma.DbOrderAdjustmentUpdateWithoutOrderInput, Prisma.DbOrderAdjustmentUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutOrderInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutOrderInput>
}

export type DbOrderAdjustmentUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
  data: Prisma.XOR<Prisma.DbOrderAdjustmentUpdateWithoutOrderInput, Prisma.DbOrderAdjustmentUncheckedUpdateWithoutOrderInput>
}

export type DbOrderAdjustmentUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.DbOrderAdjustmentScalarWhereInput
  data: Prisma.XOR<Prisma.DbOrderAdjustmentUpdateManyMutationInput, Prisma.DbOrderAdjustmentUncheckedUpdateManyWithoutOrderInput>
}

export type DbOrderAdjustmentScalarWhereInput = {
  AND?: Prisma.DbOrderAdjustmentScalarWhereInput | Prisma.DbOrderAdjustmentScalarWhereInput[]
  OR?: Prisma.DbOrderAdjustmentScalarWhereInput[]
  NOT?: Prisma.DbOrderAdjustmentScalarWhereInput | Prisma.DbOrderAdjustmentScalarWhereInput[]
  id?: Prisma.StringFilter<"DbOrderAdjustment"> | string
  orderId?: Prisma.StringFilter<"DbOrderAdjustment"> | string
  target?: Prisma.EnumDbAdjustmentTargetFilter<"DbOrderAdjustment"> | $Enums.DbAdjustmentTarget
  itemId?: Prisma.StringNullableFilter<"DbOrderAdjustment"> | string | null
  type?: Prisma.EnumDbAdjustmentTypeFilter<"DbOrderAdjustment"> | $Enums.DbAdjustmentType
  value?: Prisma.IntFilter<"DbOrderAdjustment"> | number
  reason?: Prisma.StringNullableFilter<"DbOrderAdjustment"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DbOrderAdjustment"> | Date | string
}

export type DbOrderAdjustmentCreateWithoutItemInput = {
  id?: string
  target: $Enums.DbAdjustmentTarget
  type: $Enums.DbAdjustmentType
  value: number
  reason?: string | null
  createdAt?: Date | string
  order: Prisma.DbOrderCreateNestedOneWithoutAdjustmentsInput
}

export type DbOrderAdjustmentUncheckedCreateWithoutItemInput = {
  id?: string
  orderId: string
  target: $Enums.DbAdjustmentTarget
  type: $Enums.DbAdjustmentType
  value: number
  reason?: string | null
  createdAt?: Date | string
}

export type DbOrderAdjustmentCreateOrConnectWithoutItemInput = {
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
  create: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutItemInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutItemInput>
}

export type DbOrderAdjustmentCreateManyItemInputEnvelope = {
  data: Prisma.DbOrderAdjustmentCreateManyItemInput | Prisma.DbOrderAdjustmentCreateManyItemInput[]
  skipDuplicates?: boolean
}

export type DbOrderAdjustmentUpsertWithWhereUniqueWithoutItemInput = {
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
  update: Prisma.XOR<Prisma.DbOrderAdjustmentUpdateWithoutItemInput, Prisma.DbOrderAdjustmentUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.DbOrderAdjustmentCreateWithoutItemInput, Prisma.DbOrderAdjustmentUncheckedCreateWithoutItemInput>
}

export type DbOrderAdjustmentUpdateWithWhereUniqueWithoutItemInput = {
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
  data: Prisma.XOR<Prisma.DbOrderAdjustmentUpdateWithoutItemInput, Prisma.DbOrderAdjustmentUncheckedUpdateWithoutItemInput>
}

export type DbOrderAdjustmentUpdateManyWithWhereWithoutItemInput = {
  where: Prisma.DbOrderAdjustmentScalarWhereInput
  data: Prisma.XOR<Prisma.DbOrderAdjustmentUpdateManyMutationInput, Prisma.DbOrderAdjustmentUncheckedUpdateManyWithoutItemInput>
}

export type DbOrderAdjustmentCreateManyOrderInput = {
  id?: string
  target: $Enums.DbAdjustmentTarget
  itemId?: string | null
  type: $Enums.DbAdjustmentType
  value: number
  reason?: string | null
  createdAt?: Date | string
}

export type DbOrderAdjustmentUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.EnumDbAdjustmentTargetFieldUpdateOperationsInput | $Enums.DbAdjustmentTarget
  type?: Prisma.EnumDbAdjustmentTypeFieldUpdateOperationsInput | $Enums.DbAdjustmentType
  value?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  item?: Prisma.DbOrderItemUpdateOneWithoutAdjustmentsNestedInput
}

export type DbOrderAdjustmentUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.EnumDbAdjustmentTargetFieldUpdateOperationsInput | $Enums.DbAdjustmentTarget
  itemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumDbAdjustmentTypeFieldUpdateOperationsInput | $Enums.DbAdjustmentType
  value?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbOrderAdjustmentUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.EnumDbAdjustmentTargetFieldUpdateOperationsInput | $Enums.DbAdjustmentTarget
  itemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumDbAdjustmentTypeFieldUpdateOperationsInput | $Enums.DbAdjustmentType
  value?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbOrderAdjustmentCreateManyItemInput = {
  id?: string
  orderId: string
  target: $Enums.DbAdjustmentTarget
  type: $Enums.DbAdjustmentType
  value: number
  reason?: string | null
  createdAt?: Date | string
}

export type DbOrderAdjustmentUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.EnumDbAdjustmentTargetFieldUpdateOperationsInput | $Enums.DbAdjustmentTarget
  type?: Prisma.EnumDbAdjustmentTypeFieldUpdateOperationsInput | $Enums.DbAdjustmentType
  value?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.DbOrderUpdateOneRequiredWithoutAdjustmentsNestedInput
}

export type DbOrderAdjustmentUncheckedUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.EnumDbAdjustmentTargetFieldUpdateOperationsInput | $Enums.DbAdjustmentTarget
  type?: Prisma.EnumDbAdjustmentTypeFieldUpdateOperationsInput | $Enums.DbAdjustmentType
  value?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbOrderAdjustmentUncheckedUpdateManyWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.EnumDbAdjustmentTargetFieldUpdateOperationsInput | $Enums.DbAdjustmentTarget
  type?: Prisma.EnumDbAdjustmentTypeFieldUpdateOperationsInput | $Enums.DbAdjustmentType
  value?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DbOrderAdjustmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  target?: boolean
  itemId?: boolean
  type?: boolean
  value?: boolean
  reason?: boolean
  createdAt?: boolean
  order?: boolean | Prisma.DbOrderDefaultArgs<ExtArgs>
  item?: boolean | Prisma.DbOrderAdjustment$itemArgs<ExtArgs>
}, ExtArgs["result"]["dbOrderAdjustment"]>

export type DbOrderAdjustmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  target?: boolean
  itemId?: boolean
  type?: boolean
  value?: boolean
  reason?: boolean
  createdAt?: boolean
  order?: boolean | Prisma.DbOrderDefaultArgs<ExtArgs>
  item?: boolean | Prisma.DbOrderAdjustment$itemArgs<ExtArgs>
}, ExtArgs["result"]["dbOrderAdjustment"]>

export type DbOrderAdjustmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  target?: boolean
  itemId?: boolean
  type?: boolean
  value?: boolean
  reason?: boolean
  createdAt?: boolean
  order?: boolean | Prisma.DbOrderDefaultArgs<ExtArgs>
  item?: boolean | Prisma.DbOrderAdjustment$itemArgs<ExtArgs>
}, ExtArgs["result"]["dbOrderAdjustment"]>

export type DbOrderAdjustmentSelectScalar = {
  id?: boolean
  orderId?: boolean
  target?: boolean
  itemId?: boolean
  type?: boolean
  value?: boolean
  reason?: boolean
  createdAt?: boolean
}

export type DbOrderAdjustmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orderId" | "target" | "itemId" | "type" | "value" | "reason" | "createdAt", ExtArgs["result"]["dbOrderAdjustment"]>
export type DbOrderAdjustmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.DbOrderDefaultArgs<ExtArgs>
  item?: boolean | Prisma.DbOrderAdjustment$itemArgs<ExtArgs>
}
export type DbOrderAdjustmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.DbOrderDefaultArgs<ExtArgs>
  item?: boolean | Prisma.DbOrderAdjustment$itemArgs<ExtArgs>
}
export type DbOrderAdjustmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.DbOrderDefaultArgs<ExtArgs>
  item?: boolean | Prisma.DbOrderAdjustment$itemArgs<ExtArgs>
}

export type $DbOrderAdjustmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DbOrderAdjustment"
  objects: {
    order: Prisma.$DbOrderPayload<ExtArgs>
    item: Prisma.$DbOrderItemPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orderId: string
    target: $Enums.DbAdjustmentTarget
    itemId: string | null
    type: $Enums.DbAdjustmentType
    value: number
    reason: string | null
    createdAt: Date
  }, ExtArgs["result"]["dbOrderAdjustment"]>
  composites: {}
}

export type DbOrderAdjustmentGetPayload<S extends boolean | null | undefined | DbOrderAdjustmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload, S>

export type DbOrderAdjustmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DbOrderAdjustmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DbOrderAdjustmentCountAggregateInputType | true
  }

export interface DbOrderAdjustmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DbOrderAdjustment'], meta: { name: 'DbOrderAdjustment' } }
  /**
   * Find zero or one DbOrderAdjustment that matches the filter.
   * @param {DbOrderAdjustmentFindUniqueArgs} args - Arguments to find a DbOrderAdjustment
   * @example
   * // Get one DbOrderAdjustment
   * const dbOrderAdjustment = await prisma.dbOrderAdjustment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DbOrderAdjustmentFindUniqueArgs>(args: Prisma.SelectSubset<T, DbOrderAdjustmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DbOrderAdjustmentClient<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DbOrderAdjustment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DbOrderAdjustmentFindUniqueOrThrowArgs} args - Arguments to find a DbOrderAdjustment
   * @example
   * // Get one DbOrderAdjustment
   * const dbOrderAdjustment = await prisma.dbOrderAdjustment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DbOrderAdjustmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DbOrderAdjustmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbOrderAdjustmentClient<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbOrderAdjustment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbOrderAdjustmentFindFirstArgs} args - Arguments to find a DbOrderAdjustment
   * @example
   * // Get one DbOrderAdjustment
   * const dbOrderAdjustment = await prisma.dbOrderAdjustment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DbOrderAdjustmentFindFirstArgs>(args?: Prisma.SelectSubset<T, DbOrderAdjustmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__DbOrderAdjustmentClient<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbOrderAdjustment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbOrderAdjustmentFindFirstOrThrowArgs} args - Arguments to find a DbOrderAdjustment
   * @example
   * // Get one DbOrderAdjustment
   * const dbOrderAdjustment = await prisma.dbOrderAdjustment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DbOrderAdjustmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DbOrderAdjustmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbOrderAdjustmentClient<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DbOrderAdjustments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbOrderAdjustmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DbOrderAdjustments
   * const dbOrderAdjustments = await prisma.dbOrderAdjustment.findMany()
   * 
   * // Get first 10 DbOrderAdjustments
   * const dbOrderAdjustments = await prisma.dbOrderAdjustment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dbOrderAdjustmentWithIdOnly = await prisma.dbOrderAdjustment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DbOrderAdjustmentFindManyArgs>(args?: Prisma.SelectSubset<T, DbOrderAdjustmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DbOrderAdjustment.
   * @param {DbOrderAdjustmentCreateArgs} args - Arguments to create a DbOrderAdjustment.
   * @example
   * // Create one DbOrderAdjustment
   * const DbOrderAdjustment = await prisma.dbOrderAdjustment.create({
   *   data: {
   *     // ... data to create a DbOrderAdjustment
   *   }
   * })
   * 
   */
  create<T extends DbOrderAdjustmentCreateArgs>(args: Prisma.SelectSubset<T, DbOrderAdjustmentCreateArgs<ExtArgs>>): Prisma.Prisma__DbOrderAdjustmentClient<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DbOrderAdjustments.
   * @param {DbOrderAdjustmentCreateManyArgs} args - Arguments to create many DbOrderAdjustments.
   * @example
   * // Create many DbOrderAdjustments
   * const dbOrderAdjustment = await prisma.dbOrderAdjustment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DbOrderAdjustmentCreateManyArgs>(args?: Prisma.SelectSubset<T, DbOrderAdjustmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DbOrderAdjustments and returns the data saved in the database.
   * @param {DbOrderAdjustmentCreateManyAndReturnArgs} args - Arguments to create many DbOrderAdjustments.
   * @example
   * // Create many DbOrderAdjustments
   * const dbOrderAdjustment = await prisma.dbOrderAdjustment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DbOrderAdjustments and only return the `id`
   * const dbOrderAdjustmentWithIdOnly = await prisma.dbOrderAdjustment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DbOrderAdjustmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DbOrderAdjustmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DbOrderAdjustment.
   * @param {DbOrderAdjustmentDeleteArgs} args - Arguments to delete one DbOrderAdjustment.
   * @example
   * // Delete one DbOrderAdjustment
   * const DbOrderAdjustment = await prisma.dbOrderAdjustment.delete({
   *   where: {
   *     // ... filter to delete one DbOrderAdjustment
   *   }
   * })
   * 
   */
  delete<T extends DbOrderAdjustmentDeleteArgs>(args: Prisma.SelectSubset<T, DbOrderAdjustmentDeleteArgs<ExtArgs>>): Prisma.Prisma__DbOrderAdjustmentClient<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DbOrderAdjustment.
   * @param {DbOrderAdjustmentUpdateArgs} args - Arguments to update one DbOrderAdjustment.
   * @example
   * // Update one DbOrderAdjustment
   * const dbOrderAdjustment = await prisma.dbOrderAdjustment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DbOrderAdjustmentUpdateArgs>(args: Prisma.SelectSubset<T, DbOrderAdjustmentUpdateArgs<ExtArgs>>): Prisma.Prisma__DbOrderAdjustmentClient<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DbOrderAdjustments.
   * @param {DbOrderAdjustmentDeleteManyArgs} args - Arguments to filter DbOrderAdjustments to delete.
   * @example
   * // Delete a few DbOrderAdjustments
   * const { count } = await prisma.dbOrderAdjustment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DbOrderAdjustmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, DbOrderAdjustmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbOrderAdjustments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbOrderAdjustmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DbOrderAdjustments
   * const dbOrderAdjustment = await prisma.dbOrderAdjustment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DbOrderAdjustmentUpdateManyArgs>(args: Prisma.SelectSubset<T, DbOrderAdjustmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbOrderAdjustments and returns the data updated in the database.
   * @param {DbOrderAdjustmentUpdateManyAndReturnArgs} args - Arguments to update many DbOrderAdjustments.
   * @example
   * // Update many DbOrderAdjustments
   * const dbOrderAdjustment = await prisma.dbOrderAdjustment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DbOrderAdjustments and only return the `id`
   * const dbOrderAdjustmentWithIdOnly = await prisma.dbOrderAdjustment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DbOrderAdjustmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DbOrderAdjustmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DbOrderAdjustment.
   * @param {DbOrderAdjustmentUpsertArgs} args - Arguments to update or create a DbOrderAdjustment.
   * @example
   * // Update or create a DbOrderAdjustment
   * const dbOrderAdjustment = await prisma.dbOrderAdjustment.upsert({
   *   create: {
   *     // ... data to create a DbOrderAdjustment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DbOrderAdjustment we want to update
   *   }
   * })
   */
  upsert<T extends DbOrderAdjustmentUpsertArgs>(args: Prisma.SelectSubset<T, DbOrderAdjustmentUpsertArgs<ExtArgs>>): Prisma.Prisma__DbOrderAdjustmentClient<runtime.Types.Result.GetResult<Prisma.$DbOrderAdjustmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DbOrderAdjustments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbOrderAdjustmentCountArgs} args - Arguments to filter DbOrderAdjustments to count.
   * @example
   * // Count the number of DbOrderAdjustments
   * const count = await prisma.dbOrderAdjustment.count({
   *   where: {
   *     // ... the filter for the DbOrderAdjustments we want to count
   *   }
   * })
  **/
  count<T extends DbOrderAdjustmentCountArgs>(
    args?: Prisma.Subset<T, DbOrderAdjustmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DbOrderAdjustmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DbOrderAdjustment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbOrderAdjustmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DbOrderAdjustmentAggregateArgs>(args: Prisma.Subset<T, DbOrderAdjustmentAggregateArgs>): Prisma.PrismaPromise<GetDbOrderAdjustmentAggregateType<T>>

  /**
   * Group by DbOrderAdjustment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbOrderAdjustmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DbOrderAdjustmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DbOrderAdjustmentGroupByArgs['orderBy'] }
      : { orderBy?: DbOrderAdjustmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DbOrderAdjustmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDbOrderAdjustmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DbOrderAdjustment model
 */
readonly fields: DbOrderAdjustmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DbOrderAdjustment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DbOrderAdjustmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order<T extends Prisma.DbOrderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DbOrderDefaultArgs<ExtArgs>>): Prisma.Prisma__DbOrderClient<runtime.Types.Result.GetResult<Prisma.$DbOrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  item<T extends Prisma.DbOrderAdjustment$itemArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DbOrderAdjustment$itemArgs<ExtArgs>>): Prisma.Prisma__DbOrderItemClient<runtime.Types.Result.GetResult<Prisma.$DbOrderItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DbOrderAdjustment model
 */
export interface DbOrderAdjustmentFieldRefs {
  readonly id: Prisma.FieldRef<"DbOrderAdjustment", 'String'>
  readonly orderId: Prisma.FieldRef<"DbOrderAdjustment", 'String'>
  readonly target: Prisma.FieldRef<"DbOrderAdjustment", 'DbAdjustmentTarget'>
  readonly itemId: Prisma.FieldRef<"DbOrderAdjustment", 'String'>
  readonly type: Prisma.FieldRef<"DbOrderAdjustment", 'DbAdjustmentType'>
  readonly value: Prisma.FieldRef<"DbOrderAdjustment", 'Int'>
  readonly reason: Prisma.FieldRef<"DbOrderAdjustment", 'String'>
  readonly createdAt: Prisma.FieldRef<"DbOrderAdjustment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DbOrderAdjustment findUnique
 */
export type DbOrderAdjustmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentInclude<ExtArgs> | null
  /**
   * Filter, which DbOrderAdjustment to fetch.
   */
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
}

/**
 * DbOrderAdjustment findUniqueOrThrow
 */
export type DbOrderAdjustmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentInclude<ExtArgs> | null
  /**
   * Filter, which DbOrderAdjustment to fetch.
   */
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
}

/**
 * DbOrderAdjustment findFirst
 */
export type DbOrderAdjustmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentInclude<ExtArgs> | null
  /**
   * Filter, which DbOrderAdjustment to fetch.
   */
  where?: Prisma.DbOrderAdjustmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbOrderAdjustments to fetch.
   */
  orderBy?: Prisma.DbOrderAdjustmentOrderByWithRelationInput | Prisma.DbOrderAdjustmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbOrderAdjustments.
   */
  cursor?: Prisma.DbOrderAdjustmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbOrderAdjustments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbOrderAdjustments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbOrderAdjustments.
   */
  distinct?: Prisma.DbOrderAdjustmentScalarFieldEnum | Prisma.DbOrderAdjustmentScalarFieldEnum[]
}

/**
 * DbOrderAdjustment findFirstOrThrow
 */
export type DbOrderAdjustmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentInclude<ExtArgs> | null
  /**
   * Filter, which DbOrderAdjustment to fetch.
   */
  where?: Prisma.DbOrderAdjustmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbOrderAdjustments to fetch.
   */
  orderBy?: Prisma.DbOrderAdjustmentOrderByWithRelationInput | Prisma.DbOrderAdjustmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbOrderAdjustments.
   */
  cursor?: Prisma.DbOrderAdjustmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbOrderAdjustments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbOrderAdjustments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbOrderAdjustments.
   */
  distinct?: Prisma.DbOrderAdjustmentScalarFieldEnum | Prisma.DbOrderAdjustmentScalarFieldEnum[]
}

/**
 * DbOrderAdjustment findMany
 */
export type DbOrderAdjustmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentInclude<ExtArgs> | null
  /**
   * Filter, which DbOrderAdjustments to fetch.
   */
  where?: Prisma.DbOrderAdjustmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbOrderAdjustments to fetch.
   */
  orderBy?: Prisma.DbOrderAdjustmentOrderByWithRelationInput | Prisma.DbOrderAdjustmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DbOrderAdjustments.
   */
  cursor?: Prisma.DbOrderAdjustmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbOrderAdjustments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbOrderAdjustments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbOrderAdjustments.
   */
  distinct?: Prisma.DbOrderAdjustmentScalarFieldEnum | Prisma.DbOrderAdjustmentScalarFieldEnum[]
}

/**
 * DbOrderAdjustment create
 */
export type DbOrderAdjustmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentInclude<ExtArgs> | null
  /**
   * The data needed to create a DbOrderAdjustment.
   */
  data: Prisma.XOR<Prisma.DbOrderAdjustmentCreateInput, Prisma.DbOrderAdjustmentUncheckedCreateInput>
}

/**
 * DbOrderAdjustment createMany
 */
export type DbOrderAdjustmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DbOrderAdjustments.
   */
  data: Prisma.DbOrderAdjustmentCreateManyInput | Prisma.DbOrderAdjustmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DbOrderAdjustment createManyAndReturn
 */
export type DbOrderAdjustmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * The data used to create many DbOrderAdjustments.
   */
  data: Prisma.DbOrderAdjustmentCreateManyInput | Prisma.DbOrderAdjustmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DbOrderAdjustment update
 */
export type DbOrderAdjustmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentInclude<ExtArgs> | null
  /**
   * The data needed to update a DbOrderAdjustment.
   */
  data: Prisma.XOR<Prisma.DbOrderAdjustmentUpdateInput, Prisma.DbOrderAdjustmentUncheckedUpdateInput>
  /**
   * Choose, which DbOrderAdjustment to update.
   */
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
}

/**
 * DbOrderAdjustment updateMany
 */
export type DbOrderAdjustmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DbOrderAdjustments.
   */
  data: Prisma.XOR<Prisma.DbOrderAdjustmentUpdateManyMutationInput, Prisma.DbOrderAdjustmentUncheckedUpdateManyInput>
  /**
   * Filter which DbOrderAdjustments to update
   */
  where?: Prisma.DbOrderAdjustmentWhereInput
  /**
   * Limit how many DbOrderAdjustments to update.
   */
  limit?: number
}

/**
 * DbOrderAdjustment updateManyAndReturn
 */
export type DbOrderAdjustmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * The data used to update DbOrderAdjustments.
   */
  data: Prisma.XOR<Prisma.DbOrderAdjustmentUpdateManyMutationInput, Prisma.DbOrderAdjustmentUncheckedUpdateManyInput>
  /**
   * Filter which DbOrderAdjustments to update
   */
  where?: Prisma.DbOrderAdjustmentWhereInput
  /**
   * Limit how many DbOrderAdjustments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DbOrderAdjustment upsert
 */
export type DbOrderAdjustmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentInclude<ExtArgs> | null
  /**
   * The filter to search for the DbOrderAdjustment to update in case it exists.
   */
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
  /**
   * In case the DbOrderAdjustment found by the `where` argument doesn't exist, create a new DbOrderAdjustment with this data.
   */
  create: Prisma.XOR<Prisma.DbOrderAdjustmentCreateInput, Prisma.DbOrderAdjustmentUncheckedCreateInput>
  /**
   * In case the DbOrderAdjustment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DbOrderAdjustmentUpdateInput, Prisma.DbOrderAdjustmentUncheckedUpdateInput>
}

/**
 * DbOrderAdjustment delete
 */
export type DbOrderAdjustmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentInclude<ExtArgs> | null
  /**
   * Filter which DbOrderAdjustment to delete.
   */
  where: Prisma.DbOrderAdjustmentWhereUniqueInput
}

/**
 * DbOrderAdjustment deleteMany
 */
export type DbOrderAdjustmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbOrderAdjustments to delete
   */
  where?: Prisma.DbOrderAdjustmentWhereInput
  /**
   * Limit how many DbOrderAdjustments to delete.
   */
  limit?: number
}

/**
 * DbOrderAdjustment.item
 */
export type DbOrderAdjustment$itemArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderItem
   */
  select?: Prisma.DbOrderItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderItem
   */
  omit?: Prisma.DbOrderItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderItemInclude<ExtArgs> | null
  where?: Prisma.DbOrderItemWhereInput
}

/**
 * DbOrderAdjustment without action
 */
export type DbOrderAdjustmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbOrderAdjustment
   */
  select?: Prisma.DbOrderAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbOrderAdjustment
   */
  omit?: Prisma.DbOrderAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbOrderAdjustmentInclude<ExtArgs> | null
}
