
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DbPrinterConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DbPrinterConfig
 * 
 */
export type DbPrinterConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$DbPrinterConfigPayload>

export type AggregateDbPrinterConfig = {
  _count: DbPrinterConfigCountAggregateOutputType | null
  _avg: DbPrinterConfigAvgAggregateOutputType | null
  _sum: DbPrinterConfigSumAggregateOutputType | null
  _min: DbPrinterConfigMinAggregateOutputType | null
  _max: DbPrinterConfigMaxAggregateOutputType | null
}

export type DbPrinterConfigAvgAggregateOutputType = {
  port: number | null
}

export type DbPrinterConfigSumAggregateOutputType = {
  port: number | null
}

export type DbPrinterConfigMinAggregateOutputType = {
  id: string | null
  barId: string | null
  deviceKey: string | null
  ipAddress: string | null
  port: number | null
  lastSeenAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DbPrinterConfigMaxAggregateOutputType = {
  id: string | null
  barId: string | null
  deviceKey: string | null
  ipAddress: string | null
  port: number | null
  lastSeenAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DbPrinterConfigCountAggregateOutputType = {
  id: number
  barId: number
  deviceKey: number
  ipAddress: number
  port: number
  lastSeenAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DbPrinterConfigAvgAggregateInputType = {
  port?: true
}

export type DbPrinterConfigSumAggregateInputType = {
  port?: true
}

export type DbPrinterConfigMinAggregateInputType = {
  id?: true
  barId?: true
  deviceKey?: true
  ipAddress?: true
  port?: true
  lastSeenAt?: true
  createdAt?: true
  updatedAt?: true
}

export type DbPrinterConfigMaxAggregateInputType = {
  id?: true
  barId?: true
  deviceKey?: true
  ipAddress?: true
  port?: true
  lastSeenAt?: true
  createdAt?: true
  updatedAt?: true
}

export type DbPrinterConfigCountAggregateInputType = {
  id?: true
  barId?: true
  deviceKey?: true
  ipAddress?: true
  port?: true
  lastSeenAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DbPrinterConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbPrinterConfig to aggregate.
   */
  where?: Prisma.DbPrinterConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbPrinterConfigs to fetch.
   */
  orderBy?: Prisma.DbPrinterConfigOrderByWithRelationInput | Prisma.DbPrinterConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DbPrinterConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbPrinterConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbPrinterConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DbPrinterConfigs
  **/
  _count?: true | DbPrinterConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DbPrinterConfigAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DbPrinterConfigSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DbPrinterConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DbPrinterConfigMaxAggregateInputType
}

export type GetDbPrinterConfigAggregateType<T extends DbPrinterConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateDbPrinterConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDbPrinterConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateDbPrinterConfig[P]>
}




export type DbPrinterConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DbPrinterConfigWhereInput
  orderBy?: Prisma.DbPrinterConfigOrderByWithAggregationInput | Prisma.DbPrinterConfigOrderByWithAggregationInput[]
  by: Prisma.DbPrinterConfigScalarFieldEnum[] | Prisma.DbPrinterConfigScalarFieldEnum
  having?: Prisma.DbPrinterConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DbPrinterConfigCountAggregateInputType | true
  _avg?: DbPrinterConfigAvgAggregateInputType
  _sum?: DbPrinterConfigSumAggregateInputType
  _min?: DbPrinterConfigMinAggregateInputType
  _max?: DbPrinterConfigMaxAggregateInputType
}

export type DbPrinterConfigGroupByOutputType = {
  id: string
  barId: string
  deviceKey: string
  ipAddress: string | null
  port: number
  lastSeenAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: DbPrinterConfigCountAggregateOutputType | null
  _avg: DbPrinterConfigAvgAggregateOutputType | null
  _sum: DbPrinterConfigSumAggregateOutputType | null
  _min: DbPrinterConfigMinAggregateOutputType | null
  _max: DbPrinterConfigMaxAggregateOutputType | null
}

export type GetDbPrinterConfigGroupByPayload<T extends DbPrinterConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DbPrinterConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DbPrinterConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DbPrinterConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DbPrinterConfigGroupByOutputType[P]>
      }
    >
  >



export type DbPrinterConfigWhereInput = {
  AND?: Prisma.DbPrinterConfigWhereInput | Prisma.DbPrinterConfigWhereInput[]
  OR?: Prisma.DbPrinterConfigWhereInput[]
  NOT?: Prisma.DbPrinterConfigWhereInput | Prisma.DbPrinterConfigWhereInput[]
  id?: Prisma.StringFilter<"DbPrinterConfig"> | string
  barId?: Prisma.StringFilter<"DbPrinterConfig"> | string
  deviceKey?: Prisma.StringFilter<"DbPrinterConfig"> | string
  ipAddress?: Prisma.StringNullableFilter<"DbPrinterConfig"> | string | null
  port?: Prisma.IntFilter<"DbPrinterConfig"> | number
  lastSeenAt?: Prisma.DateTimeNullableFilter<"DbPrinterConfig"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DbPrinterConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DbPrinterConfig"> | Date | string
  bar?: Prisma.XOR<Prisma.DbBarScalarRelationFilter, Prisma.DbBarWhereInput>
}

export type DbPrinterConfigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  barId?: Prisma.SortOrder
  deviceKey?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  port?: Prisma.SortOrder
  lastSeenAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  bar?: Prisma.DbBarOrderByWithRelationInput
}

export type DbPrinterConfigWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  barId?: string
  AND?: Prisma.DbPrinterConfigWhereInput | Prisma.DbPrinterConfigWhereInput[]
  OR?: Prisma.DbPrinterConfigWhereInput[]
  NOT?: Prisma.DbPrinterConfigWhereInput | Prisma.DbPrinterConfigWhereInput[]
  deviceKey?: Prisma.StringFilter<"DbPrinterConfig"> | string
  ipAddress?: Prisma.StringNullableFilter<"DbPrinterConfig"> | string | null
  port?: Prisma.IntFilter<"DbPrinterConfig"> | number
  lastSeenAt?: Prisma.DateTimeNullableFilter<"DbPrinterConfig"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DbPrinterConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DbPrinterConfig"> | Date | string
  bar?: Prisma.XOR<Prisma.DbBarScalarRelationFilter, Prisma.DbBarWhereInput>
}, "id" | "barId">

export type DbPrinterConfigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  barId?: Prisma.SortOrder
  deviceKey?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  port?: Prisma.SortOrder
  lastSeenAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DbPrinterConfigCountOrderByAggregateInput
  _avg?: Prisma.DbPrinterConfigAvgOrderByAggregateInput
  _max?: Prisma.DbPrinterConfigMaxOrderByAggregateInput
  _min?: Prisma.DbPrinterConfigMinOrderByAggregateInput
  _sum?: Prisma.DbPrinterConfigSumOrderByAggregateInput
}

export type DbPrinterConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.DbPrinterConfigScalarWhereWithAggregatesInput | Prisma.DbPrinterConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.DbPrinterConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DbPrinterConfigScalarWhereWithAggregatesInput | Prisma.DbPrinterConfigScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DbPrinterConfig"> | string
  barId?: Prisma.StringWithAggregatesFilter<"DbPrinterConfig"> | string
  deviceKey?: Prisma.StringWithAggregatesFilter<"DbPrinterConfig"> | string
  ipAddress?: Prisma.StringNullableWithAggregatesFilter<"DbPrinterConfig"> | string | null
  port?: Prisma.IntWithAggregatesFilter<"DbPrinterConfig"> | number
  lastSeenAt?: Prisma.DateTimeNullableWithAggregatesFilter<"DbPrinterConfig"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DbPrinterConfig"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DbPrinterConfig"> | Date | string
}

export type DbPrinterConfigCreateInput = {
  id?: string
  deviceKey?: string
  ipAddress?: string | null
  port?: number
  lastSeenAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  bar: Prisma.DbBarCreateNestedOneWithoutPrinterInput
}

export type DbPrinterConfigUncheckedCreateInput = {
  id?: string
  barId: string
  deviceKey?: string
  ipAddress?: string | null
  port?: number
  lastSeenAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DbPrinterConfigUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deviceKey?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  port?: Prisma.IntFieldUpdateOperationsInput | number
  lastSeenAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bar?: Prisma.DbBarUpdateOneRequiredWithoutPrinterNestedInput
}

export type DbPrinterConfigUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  barId?: Prisma.StringFieldUpdateOperationsInput | string
  deviceKey?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  port?: Prisma.IntFieldUpdateOperationsInput | number
  lastSeenAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbPrinterConfigCreateManyInput = {
  id?: string
  barId: string
  deviceKey?: string
  ipAddress?: string | null
  port?: number
  lastSeenAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DbPrinterConfigUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deviceKey?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  port?: Prisma.IntFieldUpdateOperationsInput | number
  lastSeenAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbPrinterConfigUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  barId?: Prisma.StringFieldUpdateOperationsInput | string
  deviceKey?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  port?: Prisma.IntFieldUpdateOperationsInput | number
  lastSeenAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbPrinterConfigNullableScalarRelationFilter = {
  is?: Prisma.DbPrinterConfigWhereInput | null
  isNot?: Prisma.DbPrinterConfigWhereInput | null
}

export type DbPrinterConfigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  barId?: Prisma.SortOrder
  deviceKey?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  port?: Prisma.SortOrder
  lastSeenAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DbPrinterConfigAvgOrderByAggregateInput = {
  port?: Prisma.SortOrder
}

export type DbPrinterConfigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  barId?: Prisma.SortOrder
  deviceKey?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  port?: Prisma.SortOrder
  lastSeenAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DbPrinterConfigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  barId?: Prisma.SortOrder
  deviceKey?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  port?: Prisma.SortOrder
  lastSeenAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DbPrinterConfigSumOrderByAggregateInput = {
  port?: Prisma.SortOrder
}

export type DbPrinterConfigCreateNestedOneWithoutBarInput = {
  create?: Prisma.XOR<Prisma.DbPrinterConfigCreateWithoutBarInput, Prisma.DbPrinterConfigUncheckedCreateWithoutBarInput>
  connectOrCreate?: Prisma.DbPrinterConfigCreateOrConnectWithoutBarInput
  connect?: Prisma.DbPrinterConfigWhereUniqueInput
}

export type DbPrinterConfigUncheckedCreateNestedOneWithoutBarInput = {
  create?: Prisma.XOR<Prisma.DbPrinterConfigCreateWithoutBarInput, Prisma.DbPrinterConfigUncheckedCreateWithoutBarInput>
  connectOrCreate?: Prisma.DbPrinterConfigCreateOrConnectWithoutBarInput
  connect?: Prisma.DbPrinterConfigWhereUniqueInput
}

export type DbPrinterConfigUpdateOneWithoutBarNestedInput = {
  create?: Prisma.XOR<Prisma.DbPrinterConfigCreateWithoutBarInput, Prisma.DbPrinterConfigUncheckedCreateWithoutBarInput>
  connectOrCreate?: Prisma.DbPrinterConfigCreateOrConnectWithoutBarInput
  upsert?: Prisma.DbPrinterConfigUpsertWithoutBarInput
  disconnect?: Prisma.DbPrinterConfigWhereInput | boolean
  delete?: Prisma.DbPrinterConfigWhereInput | boolean
  connect?: Prisma.DbPrinterConfigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DbPrinterConfigUpdateToOneWithWhereWithoutBarInput, Prisma.DbPrinterConfigUpdateWithoutBarInput>, Prisma.DbPrinterConfigUncheckedUpdateWithoutBarInput>
}

export type DbPrinterConfigUncheckedUpdateOneWithoutBarNestedInput = {
  create?: Prisma.XOR<Prisma.DbPrinterConfigCreateWithoutBarInput, Prisma.DbPrinterConfigUncheckedCreateWithoutBarInput>
  connectOrCreate?: Prisma.DbPrinterConfigCreateOrConnectWithoutBarInput
  upsert?: Prisma.DbPrinterConfigUpsertWithoutBarInput
  disconnect?: Prisma.DbPrinterConfigWhereInput | boolean
  delete?: Prisma.DbPrinterConfigWhereInput | boolean
  connect?: Prisma.DbPrinterConfigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DbPrinterConfigUpdateToOneWithWhereWithoutBarInput, Prisma.DbPrinterConfigUpdateWithoutBarInput>, Prisma.DbPrinterConfigUncheckedUpdateWithoutBarInput>
}

export type DbPrinterConfigCreateWithoutBarInput = {
  id?: string
  deviceKey?: string
  ipAddress?: string | null
  port?: number
  lastSeenAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DbPrinterConfigUncheckedCreateWithoutBarInput = {
  id?: string
  deviceKey?: string
  ipAddress?: string | null
  port?: number
  lastSeenAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DbPrinterConfigCreateOrConnectWithoutBarInput = {
  where: Prisma.DbPrinterConfigWhereUniqueInput
  create: Prisma.XOR<Prisma.DbPrinterConfigCreateWithoutBarInput, Prisma.DbPrinterConfigUncheckedCreateWithoutBarInput>
}

export type DbPrinterConfigUpsertWithoutBarInput = {
  update: Prisma.XOR<Prisma.DbPrinterConfigUpdateWithoutBarInput, Prisma.DbPrinterConfigUncheckedUpdateWithoutBarInput>
  create: Prisma.XOR<Prisma.DbPrinterConfigCreateWithoutBarInput, Prisma.DbPrinterConfigUncheckedCreateWithoutBarInput>
  where?: Prisma.DbPrinterConfigWhereInput
}

export type DbPrinterConfigUpdateToOneWithWhereWithoutBarInput = {
  where?: Prisma.DbPrinterConfigWhereInput
  data: Prisma.XOR<Prisma.DbPrinterConfigUpdateWithoutBarInput, Prisma.DbPrinterConfigUncheckedUpdateWithoutBarInput>
}

export type DbPrinterConfigUpdateWithoutBarInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deviceKey?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  port?: Prisma.IntFieldUpdateOperationsInput | number
  lastSeenAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbPrinterConfigUncheckedUpdateWithoutBarInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deviceKey?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  port?: Prisma.IntFieldUpdateOperationsInput | number
  lastSeenAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DbPrinterConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  barId?: boolean
  deviceKey?: boolean
  ipAddress?: boolean
  port?: boolean
  lastSeenAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  bar?: boolean | Prisma.DbBarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dbPrinterConfig"]>

export type DbPrinterConfigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  barId?: boolean
  deviceKey?: boolean
  ipAddress?: boolean
  port?: boolean
  lastSeenAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  bar?: boolean | Prisma.DbBarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dbPrinterConfig"]>

export type DbPrinterConfigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  barId?: boolean
  deviceKey?: boolean
  ipAddress?: boolean
  port?: boolean
  lastSeenAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  bar?: boolean | Prisma.DbBarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dbPrinterConfig"]>

export type DbPrinterConfigSelectScalar = {
  id?: boolean
  barId?: boolean
  deviceKey?: boolean
  ipAddress?: boolean
  port?: boolean
  lastSeenAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DbPrinterConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "barId" | "deviceKey" | "ipAddress" | "port" | "lastSeenAt" | "createdAt" | "updatedAt", ExtArgs["result"]["dbPrinterConfig"]>
export type DbPrinterConfigInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bar?: boolean | Prisma.DbBarDefaultArgs<ExtArgs>
}
export type DbPrinterConfigIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bar?: boolean | Prisma.DbBarDefaultArgs<ExtArgs>
}
export type DbPrinterConfigIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bar?: boolean | Prisma.DbBarDefaultArgs<ExtArgs>
}

export type $DbPrinterConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DbPrinterConfig"
  objects: {
    bar: Prisma.$DbBarPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    barId: string
    deviceKey: string
    ipAddress: string | null
    port: number
    lastSeenAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dbPrinterConfig"]>
  composites: {}
}

export type DbPrinterConfigGetPayload<S extends boolean | null | undefined | DbPrinterConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload, S>

export type DbPrinterConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DbPrinterConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DbPrinterConfigCountAggregateInputType | true
  }

export interface DbPrinterConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DbPrinterConfig'], meta: { name: 'DbPrinterConfig' } }
  /**
   * Find zero or one DbPrinterConfig that matches the filter.
   * @param {DbPrinterConfigFindUniqueArgs} args - Arguments to find a DbPrinterConfig
   * @example
   * // Get one DbPrinterConfig
   * const dbPrinterConfig = await prisma.dbPrinterConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DbPrinterConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, DbPrinterConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DbPrinterConfigClient<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DbPrinterConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DbPrinterConfigFindUniqueOrThrowArgs} args - Arguments to find a DbPrinterConfig
   * @example
   * // Get one DbPrinterConfig
   * const dbPrinterConfig = await prisma.dbPrinterConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DbPrinterConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DbPrinterConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbPrinterConfigClient<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbPrinterConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbPrinterConfigFindFirstArgs} args - Arguments to find a DbPrinterConfig
   * @example
   * // Get one DbPrinterConfig
   * const dbPrinterConfig = await prisma.dbPrinterConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DbPrinterConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, DbPrinterConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__DbPrinterConfigClient<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbPrinterConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbPrinterConfigFindFirstOrThrowArgs} args - Arguments to find a DbPrinterConfig
   * @example
   * // Get one DbPrinterConfig
   * const dbPrinterConfig = await prisma.dbPrinterConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DbPrinterConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DbPrinterConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbPrinterConfigClient<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DbPrinterConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbPrinterConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DbPrinterConfigs
   * const dbPrinterConfigs = await prisma.dbPrinterConfig.findMany()
   * 
   * // Get first 10 DbPrinterConfigs
   * const dbPrinterConfigs = await prisma.dbPrinterConfig.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dbPrinterConfigWithIdOnly = await prisma.dbPrinterConfig.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DbPrinterConfigFindManyArgs>(args?: Prisma.SelectSubset<T, DbPrinterConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DbPrinterConfig.
   * @param {DbPrinterConfigCreateArgs} args - Arguments to create a DbPrinterConfig.
   * @example
   * // Create one DbPrinterConfig
   * const DbPrinterConfig = await prisma.dbPrinterConfig.create({
   *   data: {
   *     // ... data to create a DbPrinterConfig
   *   }
   * })
   * 
   */
  create<T extends DbPrinterConfigCreateArgs>(args: Prisma.SelectSubset<T, DbPrinterConfigCreateArgs<ExtArgs>>): Prisma.Prisma__DbPrinterConfigClient<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DbPrinterConfigs.
   * @param {DbPrinterConfigCreateManyArgs} args - Arguments to create many DbPrinterConfigs.
   * @example
   * // Create many DbPrinterConfigs
   * const dbPrinterConfig = await prisma.dbPrinterConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DbPrinterConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, DbPrinterConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DbPrinterConfigs and returns the data saved in the database.
   * @param {DbPrinterConfigCreateManyAndReturnArgs} args - Arguments to create many DbPrinterConfigs.
   * @example
   * // Create many DbPrinterConfigs
   * const dbPrinterConfig = await prisma.dbPrinterConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DbPrinterConfigs and only return the `id`
   * const dbPrinterConfigWithIdOnly = await prisma.dbPrinterConfig.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DbPrinterConfigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DbPrinterConfigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DbPrinterConfig.
   * @param {DbPrinterConfigDeleteArgs} args - Arguments to delete one DbPrinterConfig.
   * @example
   * // Delete one DbPrinterConfig
   * const DbPrinterConfig = await prisma.dbPrinterConfig.delete({
   *   where: {
   *     // ... filter to delete one DbPrinterConfig
   *   }
   * })
   * 
   */
  delete<T extends DbPrinterConfigDeleteArgs>(args: Prisma.SelectSubset<T, DbPrinterConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__DbPrinterConfigClient<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DbPrinterConfig.
   * @param {DbPrinterConfigUpdateArgs} args - Arguments to update one DbPrinterConfig.
   * @example
   * // Update one DbPrinterConfig
   * const dbPrinterConfig = await prisma.dbPrinterConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DbPrinterConfigUpdateArgs>(args: Prisma.SelectSubset<T, DbPrinterConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__DbPrinterConfigClient<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DbPrinterConfigs.
   * @param {DbPrinterConfigDeleteManyArgs} args - Arguments to filter DbPrinterConfigs to delete.
   * @example
   * // Delete a few DbPrinterConfigs
   * const { count } = await prisma.dbPrinterConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DbPrinterConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, DbPrinterConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbPrinterConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbPrinterConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DbPrinterConfigs
   * const dbPrinterConfig = await prisma.dbPrinterConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DbPrinterConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, DbPrinterConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbPrinterConfigs and returns the data updated in the database.
   * @param {DbPrinterConfigUpdateManyAndReturnArgs} args - Arguments to update many DbPrinterConfigs.
   * @example
   * // Update many DbPrinterConfigs
   * const dbPrinterConfig = await prisma.dbPrinterConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DbPrinterConfigs and only return the `id`
   * const dbPrinterConfigWithIdOnly = await prisma.dbPrinterConfig.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DbPrinterConfigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DbPrinterConfigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DbPrinterConfig.
   * @param {DbPrinterConfigUpsertArgs} args - Arguments to update or create a DbPrinterConfig.
   * @example
   * // Update or create a DbPrinterConfig
   * const dbPrinterConfig = await prisma.dbPrinterConfig.upsert({
   *   create: {
   *     // ... data to create a DbPrinterConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DbPrinterConfig we want to update
   *   }
   * })
   */
  upsert<T extends DbPrinterConfigUpsertArgs>(args: Prisma.SelectSubset<T, DbPrinterConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__DbPrinterConfigClient<runtime.Types.Result.GetResult<Prisma.$DbPrinterConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DbPrinterConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbPrinterConfigCountArgs} args - Arguments to filter DbPrinterConfigs to count.
   * @example
   * // Count the number of DbPrinterConfigs
   * const count = await prisma.dbPrinterConfig.count({
   *   where: {
   *     // ... the filter for the DbPrinterConfigs we want to count
   *   }
   * })
  **/
  count<T extends DbPrinterConfigCountArgs>(
    args?: Prisma.Subset<T, DbPrinterConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DbPrinterConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DbPrinterConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbPrinterConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DbPrinterConfigAggregateArgs>(args: Prisma.Subset<T, DbPrinterConfigAggregateArgs>): Prisma.PrismaPromise<GetDbPrinterConfigAggregateType<T>>

  /**
   * Group by DbPrinterConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbPrinterConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DbPrinterConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DbPrinterConfigGroupByArgs['orderBy'] }
      : { orderBy?: DbPrinterConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DbPrinterConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDbPrinterConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DbPrinterConfig model
 */
readonly fields: DbPrinterConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DbPrinterConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DbPrinterConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bar<T extends Prisma.DbBarDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DbBarDefaultArgs<ExtArgs>>): Prisma.Prisma__DbBarClient<runtime.Types.Result.GetResult<Prisma.$DbBarPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DbPrinterConfig model
 */
export interface DbPrinterConfigFieldRefs {
  readonly id: Prisma.FieldRef<"DbPrinterConfig", 'String'>
  readonly barId: Prisma.FieldRef<"DbPrinterConfig", 'String'>
  readonly deviceKey: Prisma.FieldRef<"DbPrinterConfig", 'String'>
  readonly ipAddress: Prisma.FieldRef<"DbPrinterConfig", 'String'>
  readonly port: Prisma.FieldRef<"DbPrinterConfig", 'Int'>
  readonly lastSeenAt: Prisma.FieldRef<"DbPrinterConfig", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"DbPrinterConfig", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DbPrinterConfig", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DbPrinterConfig findUnique
 */
export type DbPrinterConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigInclude<ExtArgs> | null
  /**
   * Filter, which DbPrinterConfig to fetch.
   */
  where: Prisma.DbPrinterConfigWhereUniqueInput
}

/**
 * DbPrinterConfig findUniqueOrThrow
 */
export type DbPrinterConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigInclude<ExtArgs> | null
  /**
   * Filter, which DbPrinterConfig to fetch.
   */
  where: Prisma.DbPrinterConfigWhereUniqueInput
}

/**
 * DbPrinterConfig findFirst
 */
export type DbPrinterConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigInclude<ExtArgs> | null
  /**
   * Filter, which DbPrinterConfig to fetch.
   */
  where?: Prisma.DbPrinterConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbPrinterConfigs to fetch.
   */
  orderBy?: Prisma.DbPrinterConfigOrderByWithRelationInput | Prisma.DbPrinterConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbPrinterConfigs.
   */
  cursor?: Prisma.DbPrinterConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbPrinterConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbPrinterConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbPrinterConfigs.
   */
  distinct?: Prisma.DbPrinterConfigScalarFieldEnum | Prisma.DbPrinterConfigScalarFieldEnum[]
}

/**
 * DbPrinterConfig findFirstOrThrow
 */
export type DbPrinterConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigInclude<ExtArgs> | null
  /**
   * Filter, which DbPrinterConfig to fetch.
   */
  where?: Prisma.DbPrinterConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbPrinterConfigs to fetch.
   */
  orderBy?: Prisma.DbPrinterConfigOrderByWithRelationInput | Prisma.DbPrinterConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbPrinterConfigs.
   */
  cursor?: Prisma.DbPrinterConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbPrinterConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbPrinterConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbPrinterConfigs.
   */
  distinct?: Prisma.DbPrinterConfigScalarFieldEnum | Prisma.DbPrinterConfigScalarFieldEnum[]
}

/**
 * DbPrinterConfig findMany
 */
export type DbPrinterConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigInclude<ExtArgs> | null
  /**
   * Filter, which DbPrinterConfigs to fetch.
   */
  where?: Prisma.DbPrinterConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbPrinterConfigs to fetch.
   */
  orderBy?: Prisma.DbPrinterConfigOrderByWithRelationInput | Prisma.DbPrinterConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DbPrinterConfigs.
   */
  cursor?: Prisma.DbPrinterConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbPrinterConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbPrinterConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbPrinterConfigs.
   */
  distinct?: Prisma.DbPrinterConfigScalarFieldEnum | Prisma.DbPrinterConfigScalarFieldEnum[]
}

/**
 * DbPrinterConfig create
 */
export type DbPrinterConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigInclude<ExtArgs> | null
  /**
   * The data needed to create a DbPrinterConfig.
   */
  data: Prisma.XOR<Prisma.DbPrinterConfigCreateInput, Prisma.DbPrinterConfigUncheckedCreateInput>
}

/**
 * DbPrinterConfig createMany
 */
export type DbPrinterConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DbPrinterConfigs.
   */
  data: Prisma.DbPrinterConfigCreateManyInput | Prisma.DbPrinterConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DbPrinterConfig createManyAndReturn
 */
export type DbPrinterConfigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * The data used to create many DbPrinterConfigs.
   */
  data: Prisma.DbPrinterConfigCreateManyInput | Prisma.DbPrinterConfigCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DbPrinterConfig update
 */
export type DbPrinterConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigInclude<ExtArgs> | null
  /**
   * The data needed to update a DbPrinterConfig.
   */
  data: Prisma.XOR<Prisma.DbPrinterConfigUpdateInput, Prisma.DbPrinterConfigUncheckedUpdateInput>
  /**
   * Choose, which DbPrinterConfig to update.
   */
  where: Prisma.DbPrinterConfigWhereUniqueInput
}

/**
 * DbPrinterConfig updateMany
 */
export type DbPrinterConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DbPrinterConfigs.
   */
  data: Prisma.XOR<Prisma.DbPrinterConfigUpdateManyMutationInput, Prisma.DbPrinterConfigUncheckedUpdateManyInput>
  /**
   * Filter which DbPrinterConfigs to update
   */
  where?: Prisma.DbPrinterConfigWhereInput
  /**
   * Limit how many DbPrinterConfigs to update.
   */
  limit?: number
}

/**
 * DbPrinterConfig updateManyAndReturn
 */
export type DbPrinterConfigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * The data used to update DbPrinterConfigs.
   */
  data: Prisma.XOR<Prisma.DbPrinterConfigUpdateManyMutationInput, Prisma.DbPrinterConfigUncheckedUpdateManyInput>
  /**
   * Filter which DbPrinterConfigs to update
   */
  where?: Prisma.DbPrinterConfigWhereInput
  /**
   * Limit how many DbPrinterConfigs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DbPrinterConfig upsert
 */
export type DbPrinterConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigInclude<ExtArgs> | null
  /**
   * The filter to search for the DbPrinterConfig to update in case it exists.
   */
  where: Prisma.DbPrinterConfigWhereUniqueInput
  /**
   * In case the DbPrinterConfig found by the `where` argument doesn't exist, create a new DbPrinterConfig with this data.
   */
  create: Prisma.XOR<Prisma.DbPrinterConfigCreateInput, Prisma.DbPrinterConfigUncheckedCreateInput>
  /**
   * In case the DbPrinterConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DbPrinterConfigUpdateInput, Prisma.DbPrinterConfigUncheckedUpdateInput>
}

/**
 * DbPrinterConfig delete
 */
export type DbPrinterConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigInclude<ExtArgs> | null
  /**
   * Filter which DbPrinterConfig to delete.
   */
  where: Prisma.DbPrinterConfigWhereUniqueInput
}

/**
 * DbPrinterConfig deleteMany
 */
export type DbPrinterConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbPrinterConfigs to delete
   */
  where?: Prisma.DbPrinterConfigWhereInput
  /**
   * Limit how many DbPrinterConfigs to delete.
   */
  limit?: number
}

/**
 * DbPrinterConfig without action
 */
export type DbPrinterConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbPrinterConfig
   */
  select?: Prisma.DbPrinterConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbPrinterConfig
   */
  omit?: Prisma.DbPrinterConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DbPrinterConfigInclude<ExtArgs> | null
}
