export enum ErrorCodes {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_CREATION_FAILED = 'USER_CREATION_FAILED',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  UNAUTHORIZED = 'UNAUTHORIZED',
  MISSING_BAR_ID = 'MISSING_BAR_ID',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',

  BAR_NOT_FOUND = 'BAR_NOT_FOUND',
  USER_ALREADY_MEMBER = 'USER_ALREADY_MEMBER',

  INVALID_TYPE = 'INVALID_TYPE',
  MIN_LENGTH = 'MIN_LENGTH',
  MAX_LENGTH = 'MAX_LENGTH',
  INVALID_EMAIL = 'INVALID_EMAIL',
  REQUIRED = 'REQUIRED',
  INVALID_ROLE = 'INVALID_ROLE',

  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
}
