export enum ErrorCodes {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_CREATION_FAILED = 'USER_CREATION_FAILED',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  UNAUTHORIZED = 'UNAUTHORIZED',
  MISSING_BAR_ID = 'MISSING_BAR_ID',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
}
