
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  DbOrderAdjustment: 'DbOrderAdjustment',
  DbUser: 'DbUser',
  DbEstablishment: 'DbEstablishment',
  DbEstablishmentSettings: 'DbEstablishmentSettings',
  DbUserPreferences: 'DbUserPreferences',
  DbEstablishmentMember: 'DbEstablishmentMember',
  DbShift: 'DbShift',
  DbShiftExchange: 'DbShiftExchange',
  DbCategory: 'DbCategory',
  DbProduct: 'DbProduct',
  DbCategoryTemplate: 'DbCategoryTemplate',
  DbProductTemplate: 'DbProductTemplate',
  DbTable: 'DbTable',
  DbOrder: 'DbOrder',
  DbOrderItem: 'DbOrderItem',
  DbPrinterConfig: 'DbPrinterConfig',
  DbPrintJob: 'DbPrintJob',
  DbEstablishmentSubscription: 'DbEstablishmentSubscription',
  DbTimeEntry: 'DbTimeEntry',
  DbAdminAuditLog: 'DbAdminAuditLog'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "dbOrderAdjustment" | "dbUser" | "dbEstablishment" | "dbEstablishmentSettings" | "dbUserPreferences" | "dbEstablishmentMember" | "dbShift" | "dbShiftExchange" | "dbCategory" | "dbProduct" | "dbCategoryTemplate" | "dbProductTemplate" | "dbTable" | "dbOrder" | "dbOrderItem" | "dbPrinterConfig" | "dbPrintJob" | "dbEstablishmentSubscription" | "dbTimeEntry" | "dbAdminAuditLog"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    DbOrderAdjustment: {
      payload: Prisma.$DbOrderAdjustmentPayload<ExtArgs>
      fields: Prisma.DbOrderAdjustmentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbOrderAdjustmentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbOrderAdjustmentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload>
        }
        findFirst: {
          args: Prisma.DbOrderAdjustmentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbOrderAdjustmentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload>
        }
        findMany: {
          args: Prisma.DbOrderAdjustmentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload>[]
        }
        create: {
          args: Prisma.DbOrderAdjustmentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload>
        }
        createMany: {
          args: Prisma.DbOrderAdjustmentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbOrderAdjustmentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload>[]
        }
        delete: {
          args: Prisma.DbOrderAdjustmentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload>
        }
        update: {
          args: Prisma.DbOrderAdjustmentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload>
        }
        deleteMany: {
          args: Prisma.DbOrderAdjustmentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbOrderAdjustmentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbOrderAdjustmentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload>[]
        }
        upsert: {
          args: Prisma.DbOrderAdjustmentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderAdjustmentPayload>
        }
        aggregate: {
          args: Prisma.DbOrderAdjustmentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbOrderAdjustment>
        }
        groupBy: {
          args: Prisma.DbOrderAdjustmentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbOrderAdjustmentGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbOrderAdjustmentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbOrderAdjustmentCountAggregateOutputType> | number
        }
      }
    }
    DbUser: {
      payload: Prisma.$DbUserPayload<ExtArgs>
      fields: Prisma.DbUserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbUserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbUserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload>
        }
        findFirst: {
          args: Prisma.DbUserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbUserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload>
        }
        findMany: {
          args: Prisma.DbUserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload>[]
        }
        create: {
          args: Prisma.DbUserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload>
        }
        createMany: {
          args: Prisma.DbUserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbUserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload>[]
        }
        delete: {
          args: Prisma.DbUserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload>
        }
        update: {
          args: Prisma.DbUserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload>
        }
        deleteMany: {
          args: Prisma.DbUserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbUserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbUserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload>[]
        }
        upsert: {
          args: Prisma.DbUserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPayload>
        }
        aggregate: {
          args: Prisma.DbUserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbUser>
        }
        groupBy: {
          args: Prisma.DbUserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbUserGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbUserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbUserCountAggregateOutputType> | number
        }
      }
    }
    DbEstablishment: {
      payload: Prisma.$DbEstablishmentPayload<ExtArgs>
      fields: Prisma.DbEstablishmentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbEstablishmentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbEstablishmentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload>
        }
        findFirst: {
          args: Prisma.DbEstablishmentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbEstablishmentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload>
        }
        findMany: {
          args: Prisma.DbEstablishmentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload>[]
        }
        create: {
          args: Prisma.DbEstablishmentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload>
        }
        createMany: {
          args: Prisma.DbEstablishmentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbEstablishmentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload>[]
        }
        delete: {
          args: Prisma.DbEstablishmentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload>
        }
        update: {
          args: Prisma.DbEstablishmentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload>
        }
        deleteMany: {
          args: Prisma.DbEstablishmentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbEstablishmentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbEstablishmentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload>[]
        }
        upsert: {
          args: Prisma.DbEstablishmentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentPayload>
        }
        aggregate: {
          args: Prisma.DbEstablishmentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbEstablishment>
        }
        groupBy: {
          args: Prisma.DbEstablishmentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbEstablishmentGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbEstablishmentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbEstablishmentCountAggregateOutputType> | number
        }
      }
    }
    DbEstablishmentSettings: {
      payload: Prisma.$DbEstablishmentSettingsPayload<ExtArgs>
      fields: Prisma.DbEstablishmentSettingsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbEstablishmentSettingsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbEstablishmentSettingsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload>
        }
        findFirst: {
          args: Prisma.DbEstablishmentSettingsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbEstablishmentSettingsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload>
        }
        findMany: {
          args: Prisma.DbEstablishmentSettingsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload>[]
        }
        create: {
          args: Prisma.DbEstablishmentSettingsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload>
        }
        createMany: {
          args: Prisma.DbEstablishmentSettingsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbEstablishmentSettingsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload>[]
        }
        delete: {
          args: Prisma.DbEstablishmentSettingsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload>
        }
        update: {
          args: Prisma.DbEstablishmentSettingsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload>
        }
        deleteMany: {
          args: Prisma.DbEstablishmentSettingsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbEstablishmentSettingsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbEstablishmentSettingsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload>[]
        }
        upsert: {
          args: Prisma.DbEstablishmentSettingsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSettingsPayload>
        }
        aggregate: {
          args: Prisma.DbEstablishmentSettingsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbEstablishmentSettings>
        }
        groupBy: {
          args: Prisma.DbEstablishmentSettingsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbEstablishmentSettingsGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbEstablishmentSettingsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbEstablishmentSettingsCountAggregateOutputType> | number
        }
      }
    }
    DbUserPreferences: {
      payload: Prisma.$DbUserPreferencesPayload<ExtArgs>
      fields: Prisma.DbUserPreferencesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbUserPreferencesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbUserPreferencesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload>
        }
        findFirst: {
          args: Prisma.DbUserPreferencesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbUserPreferencesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload>
        }
        findMany: {
          args: Prisma.DbUserPreferencesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload>[]
        }
        create: {
          args: Prisma.DbUserPreferencesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload>
        }
        createMany: {
          args: Prisma.DbUserPreferencesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbUserPreferencesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload>[]
        }
        delete: {
          args: Prisma.DbUserPreferencesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload>
        }
        update: {
          args: Prisma.DbUserPreferencesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload>
        }
        deleteMany: {
          args: Prisma.DbUserPreferencesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbUserPreferencesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbUserPreferencesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload>[]
        }
        upsert: {
          args: Prisma.DbUserPreferencesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbUserPreferencesPayload>
        }
        aggregate: {
          args: Prisma.DbUserPreferencesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbUserPreferences>
        }
        groupBy: {
          args: Prisma.DbUserPreferencesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbUserPreferencesGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbUserPreferencesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbUserPreferencesCountAggregateOutputType> | number
        }
      }
    }
    DbEstablishmentMember: {
      payload: Prisma.$DbEstablishmentMemberPayload<ExtArgs>
      fields: Prisma.DbEstablishmentMemberFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbEstablishmentMemberFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbEstablishmentMemberFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload>
        }
        findFirst: {
          args: Prisma.DbEstablishmentMemberFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbEstablishmentMemberFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload>
        }
        findMany: {
          args: Prisma.DbEstablishmentMemberFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload>[]
        }
        create: {
          args: Prisma.DbEstablishmentMemberCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload>
        }
        createMany: {
          args: Prisma.DbEstablishmentMemberCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbEstablishmentMemberCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload>[]
        }
        delete: {
          args: Prisma.DbEstablishmentMemberDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload>
        }
        update: {
          args: Prisma.DbEstablishmentMemberUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload>
        }
        deleteMany: {
          args: Prisma.DbEstablishmentMemberDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbEstablishmentMemberUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbEstablishmentMemberUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload>[]
        }
        upsert: {
          args: Prisma.DbEstablishmentMemberUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentMemberPayload>
        }
        aggregate: {
          args: Prisma.DbEstablishmentMemberAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbEstablishmentMember>
        }
        groupBy: {
          args: Prisma.DbEstablishmentMemberGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbEstablishmentMemberGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbEstablishmentMemberCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbEstablishmentMemberCountAggregateOutputType> | number
        }
      }
    }
    DbShift: {
      payload: Prisma.$DbShiftPayload<ExtArgs>
      fields: Prisma.DbShiftFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbShiftFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbShiftFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload>
        }
        findFirst: {
          args: Prisma.DbShiftFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbShiftFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload>
        }
        findMany: {
          args: Prisma.DbShiftFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload>[]
        }
        create: {
          args: Prisma.DbShiftCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload>
        }
        createMany: {
          args: Prisma.DbShiftCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbShiftCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload>[]
        }
        delete: {
          args: Prisma.DbShiftDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload>
        }
        update: {
          args: Prisma.DbShiftUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload>
        }
        deleteMany: {
          args: Prisma.DbShiftDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbShiftUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbShiftUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload>[]
        }
        upsert: {
          args: Prisma.DbShiftUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftPayload>
        }
        aggregate: {
          args: Prisma.DbShiftAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbShift>
        }
        groupBy: {
          args: Prisma.DbShiftGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbShiftGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbShiftCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbShiftCountAggregateOutputType> | number
        }
      }
    }
    DbShiftExchange: {
      payload: Prisma.$DbShiftExchangePayload<ExtArgs>
      fields: Prisma.DbShiftExchangeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbShiftExchangeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbShiftExchangeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload>
        }
        findFirst: {
          args: Prisma.DbShiftExchangeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbShiftExchangeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload>
        }
        findMany: {
          args: Prisma.DbShiftExchangeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload>[]
        }
        create: {
          args: Prisma.DbShiftExchangeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload>
        }
        createMany: {
          args: Prisma.DbShiftExchangeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbShiftExchangeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload>[]
        }
        delete: {
          args: Prisma.DbShiftExchangeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload>
        }
        update: {
          args: Prisma.DbShiftExchangeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload>
        }
        deleteMany: {
          args: Prisma.DbShiftExchangeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbShiftExchangeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbShiftExchangeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload>[]
        }
        upsert: {
          args: Prisma.DbShiftExchangeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbShiftExchangePayload>
        }
        aggregate: {
          args: Prisma.DbShiftExchangeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbShiftExchange>
        }
        groupBy: {
          args: Prisma.DbShiftExchangeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbShiftExchangeGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbShiftExchangeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbShiftExchangeCountAggregateOutputType> | number
        }
      }
    }
    DbCategory: {
      payload: Prisma.$DbCategoryPayload<ExtArgs>
      fields: Prisma.DbCategoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbCategoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbCategoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload>
        }
        findFirst: {
          args: Prisma.DbCategoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbCategoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload>
        }
        findMany: {
          args: Prisma.DbCategoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload>[]
        }
        create: {
          args: Prisma.DbCategoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload>
        }
        createMany: {
          args: Prisma.DbCategoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbCategoryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload>[]
        }
        delete: {
          args: Prisma.DbCategoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload>
        }
        update: {
          args: Prisma.DbCategoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload>
        }
        deleteMany: {
          args: Prisma.DbCategoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbCategoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbCategoryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload>[]
        }
        upsert: {
          args: Prisma.DbCategoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryPayload>
        }
        aggregate: {
          args: Prisma.DbCategoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbCategory>
        }
        groupBy: {
          args: Prisma.DbCategoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbCategoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbCategoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbCategoryCountAggregateOutputType> | number
        }
      }
    }
    DbProduct: {
      payload: Prisma.$DbProductPayload<ExtArgs>
      fields: Prisma.DbProductFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbProductFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbProductFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload>
        }
        findFirst: {
          args: Prisma.DbProductFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbProductFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload>
        }
        findMany: {
          args: Prisma.DbProductFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload>[]
        }
        create: {
          args: Prisma.DbProductCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload>
        }
        createMany: {
          args: Prisma.DbProductCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbProductCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload>[]
        }
        delete: {
          args: Prisma.DbProductDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload>
        }
        update: {
          args: Prisma.DbProductUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload>
        }
        deleteMany: {
          args: Prisma.DbProductDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbProductUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbProductUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload>[]
        }
        upsert: {
          args: Prisma.DbProductUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductPayload>
        }
        aggregate: {
          args: Prisma.DbProductAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbProduct>
        }
        groupBy: {
          args: Prisma.DbProductGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbProductGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbProductCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbProductCountAggregateOutputType> | number
        }
      }
    }
    DbCategoryTemplate: {
      payload: Prisma.$DbCategoryTemplatePayload<ExtArgs>
      fields: Prisma.DbCategoryTemplateFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbCategoryTemplateFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbCategoryTemplateFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload>
        }
        findFirst: {
          args: Prisma.DbCategoryTemplateFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbCategoryTemplateFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload>
        }
        findMany: {
          args: Prisma.DbCategoryTemplateFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload>[]
        }
        create: {
          args: Prisma.DbCategoryTemplateCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload>
        }
        createMany: {
          args: Prisma.DbCategoryTemplateCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbCategoryTemplateCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload>[]
        }
        delete: {
          args: Prisma.DbCategoryTemplateDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload>
        }
        update: {
          args: Prisma.DbCategoryTemplateUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload>
        }
        deleteMany: {
          args: Prisma.DbCategoryTemplateDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbCategoryTemplateUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbCategoryTemplateUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload>[]
        }
        upsert: {
          args: Prisma.DbCategoryTemplateUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbCategoryTemplatePayload>
        }
        aggregate: {
          args: Prisma.DbCategoryTemplateAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbCategoryTemplate>
        }
        groupBy: {
          args: Prisma.DbCategoryTemplateGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbCategoryTemplateGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbCategoryTemplateCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbCategoryTemplateCountAggregateOutputType> | number
        }
      }
    }
    DbProductTemplate: {
      payload: Prisma.$DbProductTemplatePayload<ExtArgs>
      fields: Prisma.DbProductTemplateFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbProductTemplateFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbProductTemplateFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload>
        }
        findFirst: {
          args: Prisma.DbProductTemplateFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbProductTemplateFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload>
        }
        findMany: {
          args: Prisma.DbProductTemplateFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload>[]
        }
        create: {
          args: Prisma.DbProductTemplateCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload>
        }
        createMany: {
          args: Prisma.DbProductTemplateCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbProductTemplateCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload>[]
        }
        delete: {
          args: Prisma.DbProductTemplateDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload>
        }
        update: {
          args: Prisma.DbProductTemplateUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload>
        }
        deleteMany: {
          args: Prisma.DbProductTemplateDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbProductTemplateUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbProductTemplateUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload>[]
        }
        upsert: {
          args: Prisma.DbProductTemplateUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbProductTemplatePayload>
        }
        aggregate: {
          args: Prisma.DbProductTemplateAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbProductTemplate>
        }
        groupBy: {
          args: Prisma.DbProductTemplateGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbProductTemplateGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbProductTemplateCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbProductTemplateCountAggregateOutputType> | number
        }
      }
    }
    DbTable: {
      payload: Prisma.$DbTablePayload<ExtArgs>
      fields: Prisma.DbTableFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbTableFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbTableFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload>
        }
        findFirst: {
          args: Prisma.DbTableFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbTableFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload>
        }
        findMany: {
          args: Prisma.DbTableFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload>[]
        }
        create: {
          args: Prisma.DbTableCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload>
        }
        createMany: {
          args: Prisma.DbTableCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbTableCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload>[]
        }
        delete: {
          args: Prisma.DbTableDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload>
        }
        update: {
          args: Prisma.DbTableUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload>
        }
        deleteMany: {
          args: Prisma.DbTableDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbTableUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbTableUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload>[]
        }
        upsert: {
          args: Prisma.DbTableUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTablePayload>
        }
        aggregate: {
          args: Prisma.DbTableAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbTable>
        }
        groupBy: {
          args: Prisma.DbTableGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbTableGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbTableCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbTableCountAggregateOutputType> | number
        }
      }
    }
    DbOrder: {
      payload: Prisma.$DbOrderPayload<ExtArgs>
      fields: Prisma.DbOrderFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbOrderFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbOrderFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload>
        }
        findFirst: {
          args: Prisma.DbOrderFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbOrderFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload>
        }
        findMany: {
          args: Prisma.DbOrderFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload>[]
        }
        create: {
          args: Prisma.DbOrderCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload>
        }
        createMany: {
          args: Prisma.DbOrderCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbOrderCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload>[]
        }
        delete: {
          args: Prisma.DbOrderDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload>
        }
        update: {
          args: Prisma.DbOrderUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload>
        }
        deleteMany: {
          args: Prisma.DbOrderDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbOrderUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbOrderUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload>[]
        }
        upsert: {
          args: Prisma.DbOrderUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderPayload>
        }
        aggregate: {
          args: Prisma.DbOrderAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbOrder>
        }
        groupBy: {
          args: Prisma.DbOrderGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbOrderGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbOrderCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbOrderCountAggregateOutputType> | number
        }
      }
    }
    DbOrderItem: {
      payload: Prisma.$DbOrderItemPayload<ExtArgs>
      fields: Prisma.DbOrderItemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbOrderItemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbOrderItemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload>
        }
        findFirst: {
          args: Prisma.DbOrderItemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbOrderItemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload>
        }
        findMany: {
          args: Prisma.DbOrderItemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload>[]
        }
        create: {
          args: Prisma.DbOrderItemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload>
        }
        createMany: {
          args: Prisma.DbOrderItemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbOrderItemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload>[]
        }
        delete: {
          args: Prisma.DbOrderItemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload>
        }
        update: {
          args: Prisma.DbOrderItemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload>
        }
        deleteMany: {
          args: Prisma.DbOrderItemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbOrderItemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbOrderItemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload>[]
        }
        upsert: {
          args: Prisma.DbOrderItemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbOrderItemPayload>
        }
        aggregate: {
          args: Prisma.DbOrderItemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbOrderItem>
        }
        groupBy: {
          args: Prisma.DbOrderItemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbOrderItemGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbOrderItemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbOrderItemCountAggregateOutputType> | number
        }
      }
    }
    DbPrinterConfig: {
      payload: Prisma.$DbPrinterConfigPayload<ExtArgs>
      fields: Prisma.DbPrinterConfigFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbPrinterConfigFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbPrinterConfigFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload>
        }
        findFirst: {
          args: Prisma.DbPrinterConfigFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbPrinterConfigFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload>
        }
        findMany: {
          args: Prisma.DbPrinterConfigFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload>[]
        }
        create: {
          args: Prisma.DbPrinterConfigCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload>
        }
        createMany: {
          args: Prisma.DbPrinterConfigCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbPrinterConfigCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload>[]
        }
        delete: {
          args: Prisma.DbPrinterConfigDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload>
        }
        update: {
          args: Prisma.DbPrinterConfigUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload>
        }
        deleteMany: {
          args: Prisma.DbPrinterConfigDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbPrinterConfigUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbPrinterConfigUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload>[]
        }
        upsert: {
          args: Prisma.DbPrinterConfigUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrinterConfigPayload>
        }
        aggregate: {
          args: Prisma.DbPrinterConfigAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbPrinterConfig>
        }
        groupBy: {
          args: Prisma.DbPrinterConfigGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbPrinterConfigGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbPrinterConfigCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbPrinterConfigCountAggregateOutputType> | number
        }
      }
    }
    DbPrintJob: {
      payload: Prisma.$DbPrintJobPayload<ExtArgs>
      fields: Prisma.DbPrintJobFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbPrintJobFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbPrintJobFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload>
        }
        findFirst: {
          args: Prisma.DbPrintJobFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbPrintJobFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload>
        }
        findMany: {
          args: Prisma.DbPrintJobFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload>[]
        }
        create: {
          args: Prisma.DbPrintJobCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload>
        }
        createMany: {
          args: Prisma.DbPrintJobCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbPrintJobCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload>[]
        }
        delete: {
          args: Prisma.DbPrintJobDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload>
        }
        update: {
          args: Prisma.DbPrintJobUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload>
        }
        deleteMany: {
          args: Prisma.DbPrintJobDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbPrintJobUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbPrintJobUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload>[]
        }
        upsert: {
          args: Prisma.DbPrintJobUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbPrintJobPayload>
        }
        aggregate: {
          args: Prisma.DbPrintJobAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbPrintJob>
        }
        groupBy: {
          args: Prisma.DbPrintJobGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbPrintJobGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbPrintJobCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbPrintJobCountAggregateOutputType> | number
        }
      }
    }
    DbEstablishmentSubscription: {
      payload: Prisma.$DbEstablishmentSubscriptionPayload<ExtArgs>
      fields: Prisma.DbEstablishmentSubscriptionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbEstablishmentSubscriptionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbEstablishmentSubscriptionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload>
        }
        findFirst: {
          args: Prisma.DbEstablishmentSubscriptionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbEstablishmentSubscriptionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload>
        }
        findMany: {
          args: Prisma.DbEstablishmentSubscriptionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload>[]
        }
        create: {
          args: Prisma.DbEstablishmentSubscriptionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload>
        }
        createMany: {
          args: Prisma.DbEstablishmentSubscriptionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbEstablishmentSubscriptionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload>[]
        }
        delete: {
          args: Prisma.DbEstablishmentSubscriptionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload>
        }
        update: {
          args: Prisma.DbEstablishmentSubscriptionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload>
        }
        deleteMany: {
          args: Prisma.DbEstablishmentSubscriptionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbEstablishmentSubscriptionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbEstablishmentSubscriptionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload>[]
        }
        upsert: {
          args: Prisma.DbEstablishmentSubscriptionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbEstablishmentSubscriptionPayload>
        }
        aggregate: {
          args: Prisma.DbEstablishmentSubscriptionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbEstablishmentSubscription>
        }
        groupBy: {
          args: Prisma.DbEstablishmentSubscriptionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbEstablishmentSubscriptionGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbEstablishmentSubscriptionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbEstablishmentSubscriptionCountAggregateOutputType> | number
        }
      }
    }
    DbTimeEntry: {
      payload: Prisma.$DbTimeEntryPayload<ExtArgs>
      fields: Prisma.DbTimeEntryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbTimeEntryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbTimeEntryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload>
        }
        findFirst: {
          args: Prisma.DbTimeEntryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbTimeEntryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload>
        }
        findMany: {
          args: Prisma.DbTimeEntryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload>[]
        }
        create: {
          args: Prisma.DbTimeEntryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload>
        }
        createMany: {
          args: Prisma.DbTimeEntryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbTimeEntryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload>[]
        }
        delete: {
          args: Prisma.DbTimeEntryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload>
        }
        update: {
          args: Prisma.DbTimeEntryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload>
        }
        deleteMany: {
          args: Prisma.DbTimeEntryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbTimeEntryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbTimeEntryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload>[]
        }
        upsert: {
          args: Prisma.DbTimeEntryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbTimeEntryPayload>
        }
        aggregate: {
          args: Prisma.DbTimeEntryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbTimeEntry>
        }
        groupBy: {
          args: Prisma.DbTimeEntryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbTimeEntryGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbTimeEntryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbTimeEntryCountAggregateOutputType> | number
        }
      }
    }
    DbAdminAuditLog: {
      payload: Prisma.$DbAdminAuditLogPayload<ExtArgs>
      fields: Prisma.DbAdminAuditLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DbAdminAuditLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DbAdminAuditLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload>
        }
        findFirst: {
          args: Prisma.DbAdminAuditLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DbAdminAuditLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload>
        }
        findMany: {
          args: Prisma.DbAdminAuditLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload>[]
        }
        create: {
          args: Prisma.DbAdminAuditLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload>
        }
        createMany: {
          args: Prisma.DbAdminAuditLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DbAdminAuditLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload>[]
        }
        delete: {
          args: Prisma.DbAdminAuditLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload>
        }
        update: {
          args: Prisma.DbAdminAuditLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload>
        }
        deleteMany: {
          args: Prisma.DbAdminAuditLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DbAdminAuditLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DbAdminAuditLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload>[]
        }
        upsert: {
          args: Prisma.DbAdminAuditLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DbAdminAuditLogPayload>
        }
        aggregate: {
          args: Prisma.DbAdminAuditLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDbAdminAuditLog>
        }
        groupBy: {
          args: Prisma.DbAdminAuditLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbAdminAuditLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.DbAdminAuditLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DbAdminAuditLogCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const DbOrderAdjustmentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  target: 'target',
  itemId: 'itemId',
  type: 'type',
  value: 'value',
  reason: 'reason',
  createdAt: 'createdAt'
} as const

export type DbOrderAdjustmentScalarFieldEnum = (typeof DbOrderAdjustmentScalarFieldEnum)[keyof typeof DbOrderAdjustmentScalarFieldEnum]


export const DbUserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  googleId: 'googleId',
  name: 'name',
  photoUrl: 'photoUrl',
  active: 'active',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbUserScalarFieldEnum = (typeof DbUserScalarFieldEnum)[keyof typeof DbUserScalarFieldEnum]


export const DbEstablishmentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbEstablishmentScalarFieldEnum = (typeof DbEstablishmentScalarFieldEnum)[keyof typeof DbEstablishmentScalarFieldEnum]


export const DbEstablishmentSettingsScalarFieldEnum = {
  id: 'id',
  establishmentId: 'establishmentId',
  modules: 'modules',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbEstablishmentSettingsScalarFieldEnum = (typeof DbEstablishmentSettingsScalarFieldEnum)[keyof typeof DbEstablishmentSettingsScalarFieldEnum]


export const DbUserPreferencesScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  language: 'language',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbUserPreferencesScalarFieldEnum = (typeof DbUserPreferencesScalarFieldEnum)[keyof typeof DbUserPreferencesScalarFieldEnum]


export const DbEstablishmentMemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  establishmentId: 'establishmentId',
  role: 'role',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type DbEstablishmentMemberScalarFieldEnum = (typeof DbEstablishmentMemberScalarFieldEnum)[keyof typeof DbEstablishmentMemberScalarFieldEnum]


export const DbShiftScalarFieldEnum = {
  id: 'id',
  startTime: 'startTime',
  endTime: 'endTime',
  userId: 'userId',
  establishmentId: 'establishmentId',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbShiftScalarFieldEnum = (typeof DbShiftScalarFieldEnum)[keyof typeof DbShiftScalarFieldEnum]


export const DbShiftExchangeScalarFieldEnum = {
  id: 'id',
  shiftId: 'shiftId',
  requesterId: 'requesterId',
  targetId: 'targetId',
  status: 'status',
  createdAt: 'createdAt'
} as const

export type DbShiftExchangeScalarFieldEnum = (typeof DbShiftExchangeScalarFieldEnum)[keyof typeof DbShiftExchangeScalarFieldEnum]


export const DbCategoryScalarFieldEnum = {
  id: 'id',
  establishmentId: 'establishmentId',
  name: 'name',
  icon: 'icon',
  deletedAt: 'deletedAt'
} as const

export type DbCategoryScalarFieldEnum = (typeof DbCategoryScalarFieldEnum)[keyof typeof DbCategoryScalarFieldEnum]


export const DbProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  price: 'price',
  categoryId: 'categoryId',
  currentStock: 'currentStock',
  minStockAlert: 'minStockAlert',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type DbProductScalarFieldEnum = (typeof DbProductScalarFieldEnum)[keyof typeof DbProductScalarFieldEnum]


export const DbCategoryTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbCategoryTemplateScalarFieldEnum = (typeof DbCategoryTemplateScalarFieldEnum)[keyof typeof DbCategoryTemplateScalarFieldEnum]


export const DbProductTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  price: 'price',
  categoryId: 'categoryId',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbProductTemplateScalarFieldEnum = (typeof DbProductTemplateScalarFieldEnum)[keyof typeof DbProductTemplateScalarFieldEnum]


export const DbTableScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  establishmentId: 'establishmentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbTableScalarFieldEnum = (typeof DbTableScalarFieldEnum)[keyof typeof DbTableScalarFieldEnum]


export const DbOrderScalarFieldEnum = {
  id: 'id',
  establishmentId: 'establishmentId',
  tableId: 'tableId',
  tableName: 'tableName',
  status: 'status',
  totalAmount: 'totalAmount',
  amountPaidCash: 'amountPaidCash',
  amountPaidCard: 'amountPaidCard',
  paymentMethod: 'paymentMethod',
  notes: 'notes',
  tipAmount: 'tipAmount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbOrderScalarFieldEnum = (typeof DbOrderScalarFieldEnum)[keyof typeof DbOrderScalarFieldEnum]


export const DbOrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  quantity: 'quantity',
  priceAtPurchase: 'priceAtPurchase',
  paidQuantity: 'paidQuantity',
  paidQuantityCash: 'paidQuantityCash',
  paidQuantityCard: 'paidQuantityCard',
  servedQuantity: 'servedQuantity',
  paymentStatus: 'paymentStatus',
  deliveryStatus: 'deliveryStatus',
  paymentMethod: 'paymentMethod',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbOrderItemScalarFieldEnum = (typeof DbOrderItemScalarFieldEnum)[keyof typeof DbOrderItemScalarFieldEnum]


export const DbPrinterConfigScalarFieldEnum = {
  id: 'id',
  establishmentId: 'establishmentId',
  deviceKey: 'deviceKey',
  ipAddress: 'ipAddress',
  port: 'port',
  lastSeenAt: 'lastSeenAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbPrinterConfigScalarFieldEnum = (typeof DbPrinterConfigScalarFieldEnum)[keyof typeof DbPrinterConfigScalarFieldEnum]


export const DbPrintJobScalarFieldEnum = {
  id: 'id',
  establishmentId: 'establishmentId',
  payload: 'payload',
  status: 'status',
  attempts: 'attempts',
  error: 'error',
  createdAt: 'createdAt',
  claimedAt: 'claimedAt',
  completedAt: 'completedAt'
} as const

export type DbPrintJobScalarFieldEnum = (typeof DbPrintJobScalarFieldEnum)[keyof typeof DbPrintJobScalarFieldEnum]


export const DbEstablishmentSubscriptionScalarFieldEnum = {
  id: 'id',
  establishmentId: 'establishmentId',
  plan: 'plan',
  status: 'status',
  stripeCustomerId: 'stripeCustomerId',
  stripeSubscriptionId: 'stripeSubscriptionId',
  currentPeriodStart: 'currentPeriodStart',
  currentPeriodEnd: 'currentPeriodEnd',
  trialEndsAt: 'trialEndsAt',
  canceledAt: 'canceledAt',
  manualPlan: 'manualPlan',
  manualGrantExpiresAt: 'manualGrantExpiresAt',
  manualGrantReason: 'manualGrantReason',
  manualGrantedById: 'manualGrantedById',
  manualGrantedAt: 'manualGrantedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbEstablishmentSubscriptionScalarFieldEnum = (typeof DbEstablishmentSubscriptionScalarFieldEnum)[keyof typeof DbEstablishmentSubscriptionScalarFieldEnum]


export const DbTimeEntryScalarFieldEnum = {
  id: 'id',
  establishmentId: 'establishmentId',
  userId: 'userId',
  userSnapshot: 'userSnapshot',
  shiftId: 'shiftId',
  type: 'type',
  action: 'action',
  occurredAt: 'occurredAt',
  recordedAt: 'recordedAt',
  workdayDate: 'workdayDate',
  source: 'source',
  latitude: 'latitude',
  longitude: 'longitude',
  rootId: 'rootId',
  supersedesId: 'supersedesId',
  actorId: 'actorId',
  reason: 'reason',
  sequence: 'sequence',
  prevHash: 'prevHash',
  hash: 'hash'
} as const

export type DbTimeEntryScalarFieldEnum = (typeof DbTimeEntryScalarFieldEnum)[keyof typeof DbTimeEntryScalarFieldEnum]


export const DbAdminAuditLogScalarFieldEnum = {
  id: 'id',
  actorId: 'actorId',
  action: 'action',
  targetType: 'targetType',
  targetId: 'targetId',
  targetLabel: 'targetLabel',
  reason: 'reason',
  metadata: 'metadata',
  createdAt: 'createdAt'
} as const

export type DbAdminAuditLogScalarFieldEnum = (typeof DbAdminAuditLogScalarFieldEnum)[keyof typeof DbAdminAuditLogScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DbAdjustmentTarget'
 */
export type EnumDbAdjustmentTargetFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbAdjustmentTarget'>
    


/**
 * Reference to a field of type 'DbAdjustmentTarget[]'
 */
export type ListEnumDbAdjustmentTargetFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbAdjustmentTarget[]'>
    


/**
 * Reference to a field of type 'DbAdjustmentType'
 */
export type EnumDbAdjustmentTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbAdjustmentType'>
    


/**
 * Reference to a field of type 'DbAdjustmentType[]'
 */
export type ListEnumDbAdjustmentTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbAdjustmentType[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'DbRole'
 */
export type EnumDbRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbRole'>
    


/**
 * Reference to a field of type 'DbRole[]'
 */
export type ListEnumDbRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbRole[]'>
    


/**
 * Reference to a field of type 'DbEstablishmentModule[]'
 */
export type ListEnumDbEstablishmentModuleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbEstablishmentModule[]'>
    


/**
 * Reference to a field of type 'DbEstablishmentModule'
 */
export type EnumDbEstablishmentModuleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbEstablishmentModule'>
    


/**
 * Reference to a field of type 'DbEstablishmentRole'
 */
export type EnumDbEstablishmentRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbEstablishmentRole'>
    


/**
 * Reference to a field of type 'DbEstablishmentRole[]'
 */
export type ListEnumDbEstablishmentRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbEstablishmentRole[]'>
    


/**
 * Reference to a field of type 'DbTableStatus'
 */
export type EnumDbTableStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbTableStatus'>
    


/**
 * Reference to a field of type 'DbTableStatus[]'
 */
export type ListEnumDbTableStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbTableStatus[]'>
    


/**
 * Reference to a field of type 'DbOrderStatus'
 */
export type EnumDbOrderStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbOrderStatus'>
    


/**
 * Reference to a field of type 'DbOrderStatus[]'
 */
export type ListEnumDbOrderStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbOrderStatus[]'>
    


/**
 * Reference to a field of type 'DbPaymentMethod'
 */
export type EnumDbPaymentMethodFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbPaymentMethod'>
    


/**
 * Reference to a field of type 'DbPaymentMethod[]'
 */
export type ListEnumDbPaymentMethodFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbPaymentMethod[]'>
    


/**
 * Reference to a field of type 'DbPaymentStatus'
 */
export type EnumDbPaymentStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbPaymentStatus'>
    


/**
 * Reference to a field of type 'DbPaymentStatus[]'
 */
export type ListEnumDbPaymentStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbPaymentStatus[]'>
    


/**
 * Reference to a field of type 'DbDeliveryStatus'
 */
export type EnumDbDeliveryStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbDeliveryStatus'>
    


/**
 * Reference to a field of type 'DbDeliveryStatus[]'
 */
export type ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbDeliveryStatus[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'DbPrintJobStatus'
 */
export type EnumDbPrintJobStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbPrintJobStatus'>
    


/**
 * Reference to a field of type 'DbPrintJobStatus[]'
 */
export type ListEnumDbPrintJobStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbPrintJobStatus[]'>
    


/**
 * Reference to a field of type 'DbSubscriptionPlan'
 */
export type EnumDbSubscriptionPlanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbSubscriptionPlan'>
    


/**
 * Reference to a field of type 'DbSubscriptionPlan[]'
 */
export type ListEnumDbSubscriptionPlanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbSubscriptionPlan[]'>
    


/**
 * Reference to a field of type 'DbSubscriptionStatus'
 */
export type EnumDbSubscriptionStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbSubscriptionStatus'>
    


/**
 * Reference to a field of type 'DbSubscriptionStatus[]'
 */
export type ListEnumDbSubscriptionStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DbSubscriptionStatus[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    


/**
 * Reference to a field of type 'BigInt'
 */
export type BigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt'>
    


/**
 * Reference to a field of type 'BigInt[]'
 */
export type ListBigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  dbOrderAdjustment?: Prisma.DbOrderAdjustmentOmit
  dbUser?: Prisma.DbUserOmit
  dbEstablishment?: Prisma.DbEstablishmentOmit
  dbEstablishmentSettings?: Prisma.DbEstablishmentSettingsOmit
  dbUserPreferences?: Prisma.DbUserPreferencesOmit
  dbEstablishmentMember?: Prisma.DbEstablishmentMemberOmit
  dbShift?: Prisma.DbShiftOmit
  dbShiftExchange?: Prisma.DbShiftExchangeOmit
  dbCategory?: Prisma.DbCategoryOmit
  dbProduct?: Prisma.DbProductOmit
  dbCategoryTemplate?: Prisma.DbCategoryTemplateOmit
  dbProductTemplate?: Prisma.DbProductTemplateOmit
  dbTable?: Prisma.DbTableOmit
  dbOrder?: Prisma.DbOrderOmit
  dbOrderItem?: Prisma.DbOrderItemOmit
  dbPrinterConfig?: Prisma.DbPrinterConfigOmit
  dbPrintJob?: Prisma.DbPrintJobOmit
  dbEstablishmentSubscription?: Prisma.DbEstablishmentSubscriptionOmit
  dbTimeEntry?: Prisma.DbTimeEntryOmit
  dbAdminAuditLog?: Prisma.DbAdminAuditLogOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

