export const RealtimeEvents = {
  productCreated: 'productCreated',
  productUpdated: 'productUpdated',
  productStockChanged: 'productStockChanged',
  productDeleted: 'productDeleted',
  catalogueImported: 'catalogueImported',
  categoryCreated: 'categoryCreated',
  categoryUpdated: 'categoryUpdated',
  categoryDeleted: 'categoryDeleted',
  memberInvited: 'memberInvited',
  memberRemoved: 'memberRemoved',
  memberRoleChanged: 'memberRoleChanged',
  tableStatusChanged: 'tableStatusChanged',
  tableCreated: 'tableCreated',
  tableUpdated: 'tableUpdated',
  tableDeleted: 'tableDeleted',
  orderCreated: 'orderCreated',
  orderUpdated: 'orderUpdated',
  orderItemAdded: 'orderItemAdded',
  orderClosed: 'orderClosed',
  orderCancelled: 'orderCancelled',
  orderDeleted: 'orderDeleted',
  orderTipUpdated: 'orderTipUpdated',
  orderAdjustmentsUpdated: 'orderAdjustmentsUpdated',
  shiftCreated: 'shiftCreated',
  shiftDeleted: 'shiftDeleted',
  subscriptionUpdated: 'subscriptionUpdated',
} as const;

export type RealtimeEvents = keyof typeof RealtimeEvents;
