
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const BarRole = {
  OWNER: 'OWNER',
  STAFF: 'STAFF'
} as const

export type BarRole = (typeof BarRole)[keyof typeof BarRole]


export const Role = {
  USER: 'USER',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const TableStatus = {
  FREE: 'FREE',
  OCCUPIED: 'OCCUPIED'
} as const

export type TableStatus = (typeof TableStatus)[keyof typeof TableStatus]


export const OrderStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const PaymentStatus = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const DeliveryStatus = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  SERVED: 'SERVED'
} as const

export type DeliveryStatus = (typeof DeliveryStatus)[keyof typeof DeliveryStatus]
