export {
  BarRole,
  DeliveryStatus,
  ErrorCodes,
  OrderStatus,
  PaymentMethod,
  PaymentStatus,
  Role,
  ShiftExchangeStatus,
  TableStatus,
} from '@coaster/common';
import { BarPermission as CommonBarPermission, SocketEvents as CommonSocketEvents } from '@coaster/common';

export const SocketEvents = {
  JOIN_BAR: CommonSocketEvents.joinBar,
  LEAVE_BAR: CommonSocketEvents.leaveBar,
  JOINED: CommonSocketEvents.joined,
  LEFT: CommonSocketEvents.left,
  PRODUCT_CREATED: CommonSocketEvents.productCreated,
  PRODUCT_STOCK_CHANGED: CommonSocketEvents.productStockChanged,
  PRODUCT_UPDATED: CommonSocketEvents.productUpdated,
  PRODUCT_DELETED: CommonSocketEvents.productDeleted,
  CATEGORY_CREATED: CommonSocketEvents.categoryCreated,
  CATEGORY_UPDATED: CommonSocketEvents.categoryUpdated,
  CATEGORY_DELETED: CommonSocketEvents.categoryDeleted,
  MEMBER_INVITED: CommonSocketEvents.memberInvited,
  MEMBER_REMOVED: CommonSocketEvents.memberRemoved,
  TABLE_STATUS_CHANGED: CommonSocketEvents.tableStatusChanged,
  TABLE_CREATED: CommonSocketEvents.tableCreated,
  TABLE_UPDATED: CommonSocketEvents.tableUpdated,
  TABLE_DELETED: CommonSocketEvents.tableDeleted,
  ORDER_CREATED: CommonSocketEvents.orderCreated,
  ORDER_UPDATED: CommonSocketEvents.orderUpdated,
  ORDER_ITEM_ADDED: CommonSocketEvents.orderItemAdded,
  ORDER_CLOSED: CommonSocketEvents.orderClosed,
  ORDER_CANCELLED: CommonSocketEvents.orderCancelled,
  ORDER_DELETED: CommonSocketEvents.orderDeleted,
  SHIFT_CREATED: CommonSocketEvents.shiftCreated,
  SHIFT_DELETED: CommonSocketEvents.shiftDeleted,
} as const;

export const BarPermission = {
  VIEW_DASHBOARD: CommonBarPermission.BAR_VIEW_DASHBOARD,
  INVITE_MEMBER: CommonBarPermission.BAR_INVITE_MEMBER,
  REMOVE_MEMBER: CommonBarPermission.BAR_REMOVE_MEMBER,
  VIEW_MEMBERS: CommonBarPermission.BAR_VIEW_MEMBERS,
  OPEN_TABLE: CommonBarPermission.BAR_OPEN_TABLE,
  VIEW_TABLES: CommonBarPermission.BAR_VIEW_TABLES,
  CREATE_TABLE: CommonBarPermission.BAR_CREATE_TABLE,
  UPDATE_TABLE: CommonBarPermission.BAR_UPDATE_TABLE,
  DELETE_TABLE: CommonBarPermission.BAR_DELETE_TABLE,
  CREATE_ORDER: CommonBarPermission.BAR_CREATE_ORDER,
  VIEW_ORDERS: CommonBarPermission.BAR_VIEW_ORDERS,
  UPDATE_ORDER: CommonBarPermission.BAR_UPDATE_ORDER,
  DELETE_ORDER: CommonBarPermission.BAR_DELETE_ORDER,
  DELETE_ORDER_ITEM: CommonBarPermission.BAR_DELETE_ORDER_ITEM,
  CHECKOUT_ORDER: CommonBarPermission.BAR_CHECKOUT_ORDER,
  CANCEL_ORDER: CommonBarPermission.BAR_CANCEL_ORDER,
  MOVE_ORDER_TABLE: CommonBarPermission.BAR_MOVE_ORDER_TABLE,
  MERGE_ORDERS: CommonBarPermission.BAR_MERGE_ORDERS,
  VIEW_PRODUCTS: CommonBarPermission.BAR_VIEW_PRODUCTS,
  CREATE_PRODUCT: CommonBarPermission.BAR_CREATE_PRODUCT,
  UPDATE_PRODUCT: CommonBarPermission.BAR_UPDATE_PRODUCT,
  UPDATE_PRODUCT_STOCK: CommonBarPermission.BAR_UPDATE_PRODUCT_STOCK,
  DELETE_PRODUCT: CommonBarPermission.BAR_DELETE_PRODUCT,
  VIEW_CATEGORIES: CommonBarPermission.BAR_VIEW_CATEGORIES,
  CREATE_CATEGORY: CommonBarPermission.BAR_CREATE_CATEGORY,
  UPDATE_CATEGORY: CommonBarPermission.BAR_UPDATE_CATEGORY,
  DELETE_CATEGORY: CommonBarPermission.BAR_DELETE_CATEGORY,
  VIEW_SHIFTS: CommonBarPermission.BAR_VIEW_SHIFTS,
  CREATE_SHIFT: CommonBarPermission.BAR_CREATE_SHIFT,
  DELETE_SHIFT: CommonBarPermission.BAR_DELETE_SHIFT,
  VIEW_EXCHANGES: CommonBarPermission.BAR_VIEW_EXCHANGES,
  CREATE_EXCHANGE: CommonBarPermission.BAR_CREATE_EXCHANGE,
  ACCEPT_EXCHANGE: CommonBarPermission.BAR_ACCEPT_EXCHANGE,
  DELETE_EXCHANGE: CommonBarPermission.BAR_DELETE_EXCHANGE,
  IMPORT_TEMPLATES: CommonBarPermission.BAR_IMPORT_TEMPLATES,
} as const;
