export const AdminAuditAction = {
  ESTABLISHMENT_PLAN_GRANTED: 'ESTABLISHMENT_PLAN_GRANTED',
  ESTABLISHMENT_PLAN_REVOKED: 'ESTABLISHMENT_PLAN_REVOKED',
  ESTABLISHMENT_RENAMED: 'ESTABLISHMENT_RENAMED',
  ESTABLISHMENT_MEMBER_ROLE_CHANGED: 'ESTABLISHMENT_MEMBER_ROLE_CHANGED',
  ESTABLISHMENT_MODULES_CHANGED: 'ESTABLISHMENT_MODULES_CHANGED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_ACTIVATION_CHANGED: 'USER_ACTIVATION_CHANGED',
  TIME_ENTRY_CREATED: 'TIME_ENTRY_CREATED',
  TIME_ENTRY_AMENDED: 'TIME_ENTRY_AMENDED',
  TIME_ENTRY_VOIDED: 'TIME_ENTRY_VOIDED',
} as const;

export type AdminAuditAction = (typeof AdminAuditAction)[keyof typeof AdminAuditAction];

export const AdminAuditTargetType = {
  ESTABLISHMENT: 'ESTABLISHMENT',
  USER: 'USER',
  TIME_ENTRY: 'TIME_ENTRY',
} as const;

export type AdminAuditTargetType = (typeof AdminAuditTargetType)[keyof typeof AdminAuditTargetType];
