export type BarPermission =
  | 'bar:view-dashboard'
  | 'bar:invite-member'
  | 'bar:remove-member'
  | 'bar:view-members'
  | 'bar:open-table'
  | 'bar:view-tables'
  | 'bar:create-table'
  | 'bar:update-table'
  | 'bar:delete-table'
  | 'bar:create-order'
  | 'bar:view-orders'
  | 'bar:update-order'
  | 'bar:delete-order'
  | 'bar:delete-order-item'
  | 'bar:checkout-order'
  | 'bar:cancel-order'
  | 'bar:move-order-table'
  | 'bar:merge-orders'
  | 'bar:view-products'
  | 'bar:create-product'
  | 'bar:update-product'
  | 'bar:update-product-stock'
  | 'bar:delete-product'
  | 'bar:view-categories'
  | 'bar:create-category'
  | 'bar:update-category'
  | 'bar:delete-category'
  | 'bar:view-shifts'
  | 'bar:create-shift'
  | 'bar:delete-shift'
  | 'bar:view-exchanges'
  | 'bar:create-exchange'
  | 'bar:accept-exchange'
  | 'bar:delete-exchange'
  | 'bar:import-templates';

export type BarPermissionType = BarPermission;
