export const EstablishmentPermission = {
  ESTABLISHMENT_VIEW_DASHBOARD: 'establishment:view-dashboard',
  ESTABLISHMENT_INVITE_MEMBER: 'establishment:invite-member',
  ESTABLISHMENT_REMOVE_MEMBER: 'establishment:remove-member',
  ESTABLISHMENT_UPDATE_MEMBER_ROLE: 'establishment:update-member-role',
  ESTABLISHMENT_VIEW_MEMBERS: 'establishment:view-members',
  ESTABLISHMENT_OPEN_TABLE: 'establishment:open-table',
  ESTABLISHMENT_VIEW_TABLES: 'establishment:view-tables',
  ESTABLISHMENT_CREATE_TABLE: 'establishment:create-table',
  ESTABLISHMENT_UPDATE_TABLE: 'establishment:update-table',
  ESTABLISHMENT_DELETE_TABLE: 'establishment:delete-table',
  ESTABLISHMENT_CREATE_ORDER: 'establishment:create-order',
  ESTABLISHMENT_VIEW_ORDERS: 'establishment:view-orders',
  ESTABLISHMENT_UPDATE_ORDER: 'establishment:update-order',
  ESTABLISHMENT_DELETE_ORDER: 'establishment:delete-order',
  ESTABLISHMENT_DELETE_ORDER_ITEM: 'establishment:delete-order-item',
  ESTABLISHMENT_CHECKOUT_ORDER: 'establishment:checkout-order',
  ESTABLISHMENT_CANCEL_ORDER: 'establishment:cancel-order',
  ESTABLISHMENT_MOVE_ORDER_TABLE: 'establishment:move-order-table',
  ESTABLISHMENT_MERGE_ORDERS: 'establishment:merge-orders',
  ESTABLISHMENT_VIEW_PRODUCTS: 'establishment:view-products',
  ESTABLISHMENT_CREATE_PRODUCT: 'establishment:create-product',
  ESTABLISHMENT_UPDATE_PRODUCT: 'establishment:update-product',
  ESTABLISHMENT_UPDATE_PRODUCT_STOCK: 'establishment:update-product-stock',
  ESTABLISHMENT_DELETE_PRODUCT: 'establishment:delete-product',
  ESTABLISHMENT_VIEW_CATEGORIES: 'establishment:view-categories',
  ESTABLISHMENT_CREATE_CATEGORY: 'establishment:create-category',
  ESTABLISHMENT_UPDATE_CATEGORY: 'establishment:update-category',
  ESTABLISHMENT_DELETE_CATEGORY: 'establishment:delete-category',
  ESTABLISHMENT_VIEW_SHIFTS: 'establishment:view-shifts',
  ESTABLISHMENT_CREATE_SHIFT: 'establishment:create-shift',
  ESTABLISHMENT_DELETE_SHIFT: 'establishment:delete-shift',
  ESTABLISHMENT_CLOCK_IN: 'establishment:clock-in',
  ESTABLISHMENT_AMEND_OWN_TIME_ENTRY: 'establishment:amend-own-time-entry',
  ESTABLISHMENT_VIEW_TIME_ENTRIES: 'establishment:view-time-entries',
  ESTABLISHMENT_MANAGE_TIME_ENTRIES: 'establishment:manage-time-entries',
  ESTABLISHMENT_VIEW_EXCHANGES: 'establishment:view-exchanges',
  ESTABLISHMENT_CREATE_EXCHANGE: 'establishment:create-exchange',
  ESTABLISHMENT_ACCEPT_EXCHANGE: 'establishment:accept-exchange',
  ESTABLISHMENT_DELETE_EXCHANGE: 'establishment:delete-exchange',
  ESTABLISHMENT_IMPORT_TEMPLATES: 'establishment:import-templates',
  ESTABLISHMENT_VIEW_PRINTER: 'establishment:view-printer',
  ESTABLISHMENT_MANAGE_PRINTER: 'establishment:manage-printer',
  ESTABLISHMENT_MANAGE_BILLING: 'establishment:manage-billing',
  ESTABLISHMENT_MANAGE_SETTINGS: 'establishment:manage-settings',
} as const;

export type EstablishmentPermission = (typeof EstablishmentPermission)[keyof typeof EstablishmentPermission];

export type EstablishmentPermissionType = EstablishmentPermission;
