
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import type * as Prisma from "./internal/prismaNamespace.js"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumDbRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.DbRole | Prisma.EnumDbRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbRoleFilter<$PrismaModel> | $Enums.DbRole
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type EnumDbRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbRole | Prisma.EnumDbRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbRoleWithAggregatesFilter<$PrismaModel> | $Enums.DbRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbRoleFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type EnumDbBarRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.DbBarRole | Prisma.EnumDbBarRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel> | $Enums.DbBarRole
}

export type EnumDbBarRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbBarRole | Prisma.EnumDbBarRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbBarRoleWithAggregatesFilter<$PrismaModel> | $Enums.DbBarRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel>
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type EnumDbTableStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbTableStatus | Prisma.EnumDbTableStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel> | $Enums.DbTableStatus
}

export type EnumDbTableStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbTableStatus | Prisma.EnumDbTableStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbTableStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbTableStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel>
}

export type EnumDbOrderStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbOrderStatus | Prisma.EnumDbOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel> | $Enums.DbOrderStatus
}

export type EnumDbOrderStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbOrderStatus | Prisma.EnumDbOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbOrderStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbOrderStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel>
}

export type EnumDbPaymentStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentStatus | Prisma.EnumDbPaymentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel> | $Enums.DbPaymentStatus
}

export type EnumDbDeliveryStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbDeliveryStatus | Prisma.EnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel> | $Enums.DbDeliveryStatus
}

export type EnumDbPaymentStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentStatus | Prisma.EnumDbPaymentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbPaymentStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel>
}

export type EnumDbDeliveryStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbDeliveryStatus | Prisma.EnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbDeliveryStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbDeliveryStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumDbRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.DbRole | Prisma.EnumDbRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbRoleFilter<$PrismaModel> | $Enums.DbRole
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedEnumDbRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbRole | Prisma.EnumDbRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbRoleWithAggregatesFilter<$PrismaModel> | $Enums.DbRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbRoleFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedEnumDbBarRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.DbBarRole | Prisma.EnumDbBarRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel> | $Enums.DbBarRole
}

export type NestedEnumDbBarRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbBarRole | Prisma.EnumDbBarRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbBarRoleWithAggregatesFilter<$PrismaModel> | $Enums.DbBarRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedEnumDbTableStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbTableStatus | Prisma.EnumDbTableStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel> | $Enums.DbTableStatus
}

export type NestedEnumDbTableStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbTableStatus | Prisma.EnumDbTableStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbTableStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbTableStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel>
}

export type NestedEnumDbOrderStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbOrderStatus | Prisma.EnumDbOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel> | $Enums.DbOrderStatus
}

export type NestedEnumDbOrderStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbOrderStatus | Prisma.EnumDbOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbOrderStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbOrderStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel>
}

export type NestedEnumDbPaymentStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentStatus | Prisma.EnumDbPaymentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel> | $Enums.DbPaymentStatus
}

export type NestedEnumDbDeliveryStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbDeliveryStatus | Prisma.EnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel> | $Enums.DbDeliveryStatus
}

export type NestedEnumDbPaymentStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentStatus | Prisma.EnumDbPaymentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbPaymentStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel>
}

export type NestedEnumDbDeliveryStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbDeliveryStatus | Prisma.EnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbDeliveryStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbDeliveryStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel>
}


