
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const DbBarRole = {
  OWNER: 'OWNER',
  STAFF: 'STAFF'
} as const

export type DbBarRole = (typeof DbBarRole)[keyof typeof DbBarRole]


export const DbRole = {
  USER: 'USER',
  ADMIN: 'ADMIN'
} as const

export type DbRole = (typeof DbRole)[keyof typeof DbRole]


export const DbTableStatus = {
  FREE: 'FREE',
  OCCUPIED: 'OCCUPIED'
} as const

export type DbTableStatus = (typeof DbTableStatus)[keyof typeof DbTableStatus]


export const DbOrderStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED'
} as const

export type DbOrderStatus = (typeof DbOrderStatus)[keyof typeof DbOrderStatus]


export const DbPaymentStatus = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID'
} as const

export type DbPaymentStatus = (typeof DbPaymentStatus)[keyof typeof DbPaymentStatus]


export const DbDeliveryStatus = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  SERVED: 'SERVED'
} as const

export type DbDeliveryStatus = (typeof DbDeliveryStatus)[keyof typeof DbDeliveryStatus]
