
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import type * as Prisma from "./internal/prismaNamespace.js"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type EnumDbAdjustmentTargetFilter<$PrismaModel = never> = {
  equals?: $Enums.DbAdjustmentTarget | Prisma.EnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  in?: $Enums.DbAdjustmentTarget[] | Prisma.ListEnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbAdjustmentTarget[] | Prisma.ListEnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbAdjustmentTargetFilter<$PrismaModel> | $Enums.DbAdjustmentTarget
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type EnumDbAdjustmentTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.DbAdjustmentType | Prisma.EnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.DbAdjustmentType[] | Prisma.ListEnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbAdjustmentType[] | Prisma.ListEnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbAdjustmentTypeFilter<$PrismaModel> | $Enums.DbAdjustmentType
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type EnumDbAdjustmentTargetWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbAdjustmentTarget | Prisma.EnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  in?: $Enums.DbAdjustmentTarget[] | Prisma.ListEnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbAdjustmentTarget[] | Prisma.ListEnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbAdjustmentTargetWithAggregatesFilter<$PrismaModel> | $Enums.DbAdjustmentTarget
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbAdjustmentTargetFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbAdjustmentTargetFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type EnumDbAdjustmentTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbAdjustmentType | Prisma.EnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.DbAdjustmentType[] | Prisma.ListEnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbAdjustmentType[] | Prisma.ListEnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbAdjustmentTypeWithAggregatesFilter<$PrismaModel> | $Enums.DbAdjustmentType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbAdjustmentTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbAdjustmentTypeFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumDbRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.DbRole | Prisma.EnumDbRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbRoleFilter<$PrismaModel> | $Enums.DbRole
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type EnumDbRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbRole | Prisma.EnumDbRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbRoleWithAggregatesFilter<$PrismaModel> | $Enums.DbRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbRoleFilter<$PrismaModel>
}

export type EnumDbBarRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.DbBarRole | Prisma.EnumDbBarRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel> | $Enums.DbBarRole
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type EnumDbBarRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbBarRole | Prisma.EnumDbBarRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbBarRoleWithAggregatesFilter<$PrismaModel> | $Enums.DbBarRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type EnumDbTableStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbTableStatus | Prisma.EnumDbTableStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel> | $Enums.DbTableStatus
}

export type EnumDbTableStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbTableStatus | Prisma.EnumDbTableStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbTableStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbTableStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel>
}

export type EnumDbOrderStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbOrderStatus | Prisma.EnumDbOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel> | $Enums.DbOrderStatus
}

export type EnumDbPaymentMethodFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentMethod | Prisma.EnumDbPaymentMethodFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentMethod[] | Prisma.ListEnumDbPaymentMethodFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentMethod[] | Prisma.ListEnumDbPaymentMethodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentMethodFilter<$PrismaModel> | $Enums.DbPaymentMethod
}

export type EnumDbOrderStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbOrderStatus | Prisma.EnumDbOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbOrderStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbOrderStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel>
}

export type EnumDbPaymentMethodWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentMethod | Prisma.EnumDbPaymentMethodFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentMethod[] | Prisma.ListEnumDbPaymentMethodFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentMethod[] | Prisma.ListEnumDbPaymentMethodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentMethodWithAggregatesFilter<$PrismaModel> | $Enums.DbPaymentMethod
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbPaymentMethodFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbPaymentMethodFilter<$PrismaModel>
}

export type EnumDbPaymentStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentStatus | Prisma.EnumDbPaymentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel> | $Enums.DbPaymentStatus
}

export type EnumDbDeliveryStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbDeliveryStatus | Prisma.EnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel> | $Enums.DbDeliveryStatus
}

export type EnumDbPaymentStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentStatus | Prisma.EnumDbPaymentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbPaymentStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel>
}

export type EnumDbDeliveryStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbDeliveryStatus | Prisma.EnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbDeliveryStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbDeliveryStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel>
}

export type EnumDbSubscriptionPlanFilter<$PrismaModel = never> = {
  equals?: $Enums.DbSubscriptionPlan | Prisma.EnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  in?: $Enums.DbSubscriptionPlan[] | Prisma.ListEnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbSubscriptionPlan[] | Prisma.ListEnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbSubscriptionPlanFilter<$PrismaModel> | $Enums.DbSubscriptionPlan
}

export type EnumDbSubscriptionStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbSubscriptionStatus | Prisma.EnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbSubscriptionStatus[] | Prisma.ListEnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbSubscriptionStatus[] | Prisma.ListEnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbSubscriptionStatusFilter<$PrismaModel> | $Enums.DbSubscriptionStatus
}

export type EnumDbSubscriptionPlanWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbSubscriptionPlan | Prisma.EnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  in?: $Enums.DbSubscriptionPlan[] | Prisma.ListEnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbSubscriptionPlan[] | Prisma.ListEnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbSubscriptionPlanWithAggregatesFilter<$PrismaModel> | $Enums.DbSubscriptionPlan
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbSubscriptionPlanFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbSubscriptionPlanFilter<$PrismaModel>
}

export type EnumDbSubscriptionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbSubscriptionStatus | Prisma.EnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbSubscriptionStatus[] | Prisma.ListEnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbSubscriptionStatus[] | Prisma.ListEnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbSubscriptionStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbSubscriptionStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbSubscriptionStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbSubscriptionStatusFilter<$PrismaModel>
}

export type JsonFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonFilterBase<$PrismaModel>>, 'path'>>

export type JsonFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type JsonWithAggregatesFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonWithAggregatesFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonWithAggregatesFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonWithAggregatesFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonWithAggregatesFilterBase<$PrismaModel>>, 'path'>>

export type JsonWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedJsonFilter<$PrismaModel>
  _max?: Prisma.NestedJsonFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedEnumDbAdjustmentTargetFilter<$PrismaModel = never> = {
  equals?: $Enums.DbAdjustmentTarget | Prisma.EnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  in?: $Enums.DbAdjustmentTarget[] | Prisma.ListEnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbAdjustmentTarget[] | Prisma.ListEnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbAdjustmentTargetFilter<$PrismaModel> | $Enums.DbAdjustmentTarget
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedEnumDbAdjustmentTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.DbAdjustmentType | Prisma.EnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.DbAdjustmentType[] | Prisma.ListEnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbAdjustmentType[] | Prisma.ListEnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbAdjustmentTypeFilter<$PrismaModel> | $Enums.DbAdjustmentType
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedEnumDbAdjustmentTargetWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbAdjustmentTarget | Prisma.EnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  in?: $Enums.DbAdjustmentTarget[] | Prisma.ListEnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbAdjustmentTarget[] | Prisma.ListEnumDbAdjustmentTargetFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbAdjustmentTargetWithAggregatesFilter<$PrismaModel> | $Enums.DbAdjustmentTarget
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbAdjustmentTargetFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbAdjustmentTargetFilter<$PrismaModel>
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumDbAdjustmentTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbAdjustmentType | Prisma.EnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.DbAdjustmentType[] | Prisma.ListEnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbAdjustmentType[] | Prisma.ListEnumDbAdjustmentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbAdjustmentTypeWithAggregatesFilter<$PrismaModel> | $Enums.DbAdjustmentType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbAdjustmentTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbAdjustmentTypeFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumDbRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.DbRole | Prisma.EnumDbRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbRoleFilter<$PrismaModel> | $Enums.DbRole
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedEnumDbRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbRole | Prisma.EnumDbRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbRole[] | Prisma.ListEnumDbRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbRoleWithAggregatesFilter<$PrismaModel> | $Enums.DbRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbRoleFilter<$PrismaModel>
}

export type NestedEnumDbBarRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.DbBarRole | Prisma.EnumDbBarRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel> | $Enums.DbBarRole
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedEnumDbBarRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbBarRole | Prisma.EnumDbBarRoleFieldRefInput<$PrismaModel>
  in?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbBarRole[] | Prisma.ListEnumDbBarRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbBarRoleWithAggregatesFilter<$PrismaModel> | $Enums.DbBarRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbBarRoleFilter<$PrismaModel>
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedEnumDbTableStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbTableStatus | Prisma.EnumDbTableStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel> | $Enums.DbTableStatus
}

export type NestedEnumDbTableStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbTableStatus | Prisma.EnumDbTableStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbTableStatus[] | Prisma.ListEnumDbTableStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbTableStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbTableStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbTableStatusFilter<$PrismaModel>
}

export type NestedEnumDbOrderStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbOrderStatus | Prisma.EnumDbOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel> | $Enums.DbOrderStatus
}

export type NestedEnumDbPaymentMethodFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentMethod | Prisma.EnumDbPaymentMethodFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentMethod[] | Prisma.ListEnumDbPaymentMethodFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentMethod[] | Prisma.ListEnumDbPaymentMethodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentMethodFilter<$PrismaModel> | $Enums.DbPaymentMethod
}

export type NestedEnumDbOrderStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbOrderStatus | Prisma.EnumDbOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbOrderStatus[] | Prisma.ListEnumDbOrderStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbOrderStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbOrderStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbOrderStatusFilter<$PrismaModel>
}

export type NestedEnumDbPaymentMethodWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentMethod | Prisma.EnumDbPaymentMethodFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentMethod[] | Prisma.ListEnumDbPaymentMethodFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentMethod[] | Prisma.ListEnumDbPaymentMethodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentMethodWithAggregatesFilter<$PrismaModel> | $Enums.DbPaymentMethod
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbPaymentMethodFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbPaymentMethodFilter<$PrismaModel>
}

export type NestedEnumDbPaymentStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentStatus | Prisma.EnumDbPaymentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel> | $Enums.DbPaymentStatus
}

export type NestedEnumDbDeliveryStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbDeliveryStatus | Prisma.EnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel> | $Enums.DbDeliveryStatus
}

export type NestedEnumDbPaymentStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbPaymentStatus | Prisma.EnumDbPaymentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbPaymentStatus[] | Prisma.ListEnumDbPaymentStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbPaymentStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbPaymentStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbPaymentStatusFilter<$PrismaModel>
}

export type NestedEnumDbDeliveryStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbDeliveryStatus | Prisma.EnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbDeliveryStatus[] | Prisma.ListEnumDbDeliveryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbDeliveryStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbDeliveryStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbDeliveryStatusFilter<$PrismaModel>
}

export type NestedEnumDbSubscriptionPlanFilter<$PrismaModel = never> = {
  equals?: $Enums.DbSubscriptionPlan | Prisma.EnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  in?: $Enums.DbSubscriptionPlan[] | Prisma.ListEnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbSubscriptionPlan[] | Prisma.ListEnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbSubscriptionPlanFilter<$PrismaModel> | $Enums.DbSubscriptionPlan
}

export type NestedEnumDbSubscriptionStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DbSubscriptionStatus | Prisma.EnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbSubscriptionStatus[] | Prisma.ListEnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbSubscriptionStatus[] | Prisma.ListEnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbSubscriptionStatusFilter<$PrismaModel> | $Enums.DbSubscriptionStatus
}

export type NestedEnumDbSubscriptionPlanWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbSubscriptionPlan | Prisma.EnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  in?: $Enums.DbSubscriptionPlan[] | Prisma.ListEnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbSubscriptionPlan[] | Prisma.ListEnumDbSubscriptionPlanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbSubscriptionPlanWithAggregatesFilter<$PrismaModel> | $Enums.DbSubscriptionPlan
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbSubscriptionPlanFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbSubscriptionPlanFilter<$PrismaModel>
}

export type NestedEnumDbSubscriptionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DbSubscriptionStatus | Prisma.EnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.DbSubscriptionStatus[] | Prisma.ListEnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.DbSubscriptionStatus[] | Prisma.ListEnumDbSubscriptionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDbSubscriptionStatusWithAggregatesFilter<$PrismaModel> | $Enums.DbSubscriptionStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDbSubscriptionStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDbSubscriptionStatusFilter<$PrismaModel>
}

export type NestedJsonFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<NestedJsonFilterBase<$PrismaModel>>, Exclude<keyof Required<NestedJsonFilterBase<$PrismaModel>>, 'path'>>,
    Required<NestedJsonFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<NestedJsonFilterBase<$PrismaModel>>, 'path'>>

export type NestedJsonFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}


