-- Generado desde starter-catalogue.ts: repone los iconos que se quedaron sin poner
-- o con un nombre que Material no renderiza. Nunca pisa un icono ya elegido a mano.

UPDATE "Category" SET "icon" = v.icon
FROM (VALUES
  ('Cafetería', 'coffee'),
  ('Refrescos y Aguas', 'water_drop'),
  ('Cervezas', 'sports_bar'),
  ('Vinos y Licores', 'wine_bar'),
  ('Tapas y Raciones', 'tapas'),
  ('Bocadillos y Hamburguesas', 'lunch_dining'),
  ('Postres', 'cake')
) AS v(name, icon)
WHERE "Category"."name" = v.name
  AND ("Category"."icon" IS NULL OR "Category"."icon" !~ '^[a-z][a-z0-9_]*$');

UPDATE "Product" SET "icon" = v.icon
FROM (VALUES
  ('Café Solo', 'coffee'),
  ('Café Espresso', 'coffee'),
  ('Café Cortado', 'coffee'),
  ('Infusión / Té', 'emoji_food_beverage'),
  ('Café con Leche', 'local_cafe'),
  ('Colacao', 'local_cafe'),
  ('Capuccino', 'local_cafe'),
  ('Carajillo', 'coffee'),
  ('Agua Mineral 500ml', 'water_drop'),
  ('Agua con Gas', 'water_drop'),
  ('Fanta Limón', 'local_drink'),
  ('Fanta Naranja', 'local_drink'),
  ('Tónica', 'local_drink'),
  ('Coca-Cola Original', 'local_drink'),
  ('Coca-Cola Zero', 'local_drink'),
  ('Sprite', 'local_drink'),
  ('Aquarius Limón', 'local_drink'),
  ('Nestea', 'emoji_food_beverage'),
  ('Caña de Cerveza (Estrella Galicia)', 'sports_bar'),
  ('Tercio Mahou 0,0 Tostada', 'sports_bar'),
  ('Tercio Heineken 0,0', 'sports_bar'),
  ('Tercio Mahou Cinco Estrellas', 'sports_bar'),
  ('Tercio Estrella Galicia', 'sports_bar'),
  ('Tercio Mahou Rosé', 'sports_bar'),
  ('Tercio Heineken', 'sports_bar'),
  ('Doble de Cerveza (Estrella Galicia)', 'sports_bar'),
  ('Tercio El Águila Sin Filtrar', 'sports_bar'),
  ('Tercio Coronita', 'sports_bar'),
  ('Tercio 1906 Reserva Especial', 'sports_bar'),
  ('Tercio Alhambra Reserva 1925', 'sports_bar'),
  ('Tinto de Verano', 'wine_bar'),
  ('Tercio Paulaner (Trigo)', 'sports_bar'),
  ('Chupito de Licor de Hierbas', 'liquor'),
  ('Chupito de Jägermeister', 'liquor'),
  ('Copa de Vino Blanco (Rueda)', 'wine_bar'),
  ('Copa de Vino Tinto (Rioja)', 'wine_bar'),
  ('Copa de Vermut de la Casa', 'wine_bar'),
  ('Copa de Baileys', 'liquor'),
  ('Ginebra Beefeater (Sola)', 'liquor'),
  ('Ron Barceló Añejo (Solo)', 'liquor'),
  ('Vodka Absolut (Solo)', 'liquor'),
  ('Whisky J&B (Solo)', 'liquor'),
  ('Ron Santa Teresa (Solo)', 'liquor'),
  ('Whisky Jack Daniel''s (Solo)', 'liquor'),
  ('Ron Havana Club 7 (Solo)', 'liquor'),
  ('Gin Tonic Beefeater', 'local_bar'),
  ('Ron Barceló con Cola', 'local_bar'),
  ('Vodka Absolut con Refresco', 'local_bar'),
  ('Whisky J&B con Refresco', 'local_bar'),
  ('Ginebra Hendrick''s (Sola)', 'liquor'),
  ('Ron Santa Teresa con Cola', 'local_bar'),
  ('Whisky Jack Daniel''s con Cola', 'local_bar'),
  ('Ron Havana 7 con Cola', 'local_bar'),
  ('Whisky Macallan 12 (Solo)', 'liquor'),
  ('Gin Tonic Hendrick''s', 'local_bar'),
  ('Botella de Vino Blanco (Rueda)', 'wine_bar'),
  ('Botella de Vino Tinto (Rioja)', 'wine_bar'),
  ('Pimientos del Padrón', 'nutrition'),
  ('Ensaladilla Rusa', 'tapas'),
  ('Alitas de Pollo', 'tapas'),
  ('Patatas Bravas', 'tapas'),
  ('Croquetas de Jamón (6 ud)', 'tapas'),
  ('Calamares a la Romana', 'set_meal'),
  ('Tabla de Quesos', 'dinner_dining'),
  ('Tabla de Jamón Ibérico', 'dinner_dining'),
  ('Sándwich Mixto', 'breakfast_dining'),
  ('Bocadillo Tortilla de Patatas', 'bakery_dining'),
  ('Perrito Caliente', 'lunch_dining'),
  ('Bocadillo de Calamares', 'bakery_dining'),
  ('Bocadillo Chivito', 'bakery_dining'),
  ('Hamburguesa Clásica con Queso', 'lunch_dining'),
  ('Hamburguesa Especial Coaster', 'lunch_dining'),
  ('Flan Casero', 'cake'),
  ('Helado Variado', 'icecream'),
  ('Tarta de Chocolate', 'cake'),
  ('Tarta de Queso', 'cake')
) AS v(name, icon)
WHERE "Product"."name" = v.name AND "Product"."icon" IS NULL;
